* KEY PHRASES FOR EMAIL

This book is designed to help you in your work.

We advise you to read it regularly and keep it within easy reach.

Do not hesitate to contact ECSPLICITE if you have any questions.

Phone: 0825 096 860

Email: contact@ecsplicite.com

Key phrases for Email, by Laurent Sorgato

is a book from the series Effective Communication

Copyright SGDL 2003

All rights reserved. No part of this publication may be reproduced,

stored in a retrieval system, or transmitted, in any form or by any
means, electronic, mechanical, photocopying, recording or otherwise,

without the prior written permission of the author.

This book is sold subject to the condition that it shall not, by way of
trade

or otherwise, be lent, resold, hired out, or otherwise circulated

without the publisher's prior consent in any form of binding or cover

other than that in which it is published, and without a similar
condition

being imposed on the subsequent purchaser.

Proudly printed in France

* ECSPLICITE -- KEY PHRASES FOR EMAIL
** THE DATE

- 27 JAN 2006

- 15 Nov 2004

- 3 APR 72

- 14 October 2002

- March 2, 2008

- 4th June, 1982

- December 22nd, 2000

- The 1st of May, 2005

** SALUTATIAN

- Hi guys!

- Hi everybody!

- Hi Bob!

- Hello!

- Hello Sue,

- Greetings everyone!

- Dear Mary,

- Dear John,

- Dear Ms. Grey:

- Dear Mr. Brown:

- Dear Mr. Black and Ms. White,

- Dear Personnel Supervisor,

- Dear Logistics Department,

- Dear WARO Corporation:

- To Whom It May Concern:

** THE CONTENT
*** Opening
**** Starting
 - I'm writing in connection with our order n° 1234AB5-6 dated 10 July
 for three (3) fuse boxes ref. n° 5678CD90-5.

 - I'm writing in connection with your advertisement in the 5 May issue
 of the Buffalo Tribune for an experienced electronics technician for
 your maintenance department.

 - This is in reference to your invoice #654321 which we received
 yesterday.

 - Further to our meeting last Monday, I asked our Customer Support Dept.
 about the problem you had with the XYZ model.

 - Following our telephone conversation yesterday, I'm writing to confirm
 my reservation for a single room with bath for 3 nights, arrival 31 July
 and departure 3 August.

 - With reference to your order n° 1234AB5-6, ref. n° 7890PH13-7 (item
 n°5, 16 switches) is no longer available. It has been replaced by switch
 ref. n° 7890PH14-9.

 - You are probably aware of the recent cuts in the training budget.

 - I'm writing to enquire about the price and delivery date for an A3
 paper tray ref. n°

 1234AB5-6 for our WARO ZT3 photocopier.

 - WARO is interested in organizing a 5-day ski holiday for 50 to 70
 employees, arriving 15

 December and leaving 20 December. We would like your best offer for a
 complete package including accommodations, full board and ski-lift
 passes.

 - Your article in the Detroit Post concerning our product has been
 brought to our attention.

**** Acknonwlweding
 - We got your email asking us to modify the design.

 - We received your request to reschedule delivery of our order n°
 1234AB5-6.

 - This is to acknowledge receipt of payment for your order no. 963852.

 - We were pleased to learn of your recent promotion.

 - We were sorry to hear that you are no longer selling solvents.
**** Thanking
 - Thank you for your e-mail of 29 May.

 - Thanks for sending the completed form back so quickly.

 - We got the updated file today. Thanks for taking care of the problem
 so soon.

 - Thank you for enquiring about our products.

*** Requesting action
**** Usual business
     - Please fax us a copy of the original contract.

     - Please let us know when the batch is ready to ship.

     - Please send us the address of the local distributor for this area.

     - Please could you confirm that these specs are still valid.

     - Please could you enroll John Greene in the Total Immersion English
     Course ref. n° 326/74 beginning on 20 July.
**** Special favors
        - Could you possibly come in early tomorrow?

        - Would you mind helping us with closing this month?

        - We would be grateful if you could call us to arrange an appointment at
        your earliest convenience.

        - I would appreciate it if you could refax this month's test results
        asap.

        - It would be helpful if you could shorten the lead time by 24 hours.

        - I'm writing in connection with Mary Brown's reservation for a double
        room for 3 nights starting 2 July. Please cancel this booking and
        reserve a single for 5 nights. She'll be arriving on 31 July and leaving
        on the morning of 5 August instead.

        - I'm writing in connection with our order n° 5248TY. Unfortunately, we
        haven't received items n° 5, 8 and 11. Please could you ship them
        without delay or call our Production Dept.

        to reschedule the shipment dates.

**** Giving Good/bad news
           - I'm glad to say that production is back on schedule.

           - We're happy to announce that we've reached our target a week ahead of
           schedule.

           - We are pleased to inform you that you have been accepted for our
           Internship Program for the coming year beginning 1 September and ending
           30 June.

           - Fortunately, no one was injured in the accident.

           - Luckily, the old gaskets are just the right size for the new model.

           - The bad news is that the whole system crashed again. The good news is
           that the back-up system works and we didn't lose any data this time.

           - The good news is we're ready to ship your order. The bad news is the
           SNCF is on strike again.

           - I'm sorry to tell you that they've decided to terminate your research
           program.

           - I'm writing in connection with order n° 33668UI. I regret to inform
           you that we have been forced to raise our prices because of the increase
           in the cost of aluminium.

**** Saying what can/can't be done and why
            - If your order is for over $10,000.00, you qualify for our 10%
            discount.

            - Unfortunately, owing to the instability of the monetary market, we are
            not able to accept payment in US Dollars.

            - I'm writing in connection with Paul Smith's reservation for the
            English Course ref. n°

            32G/97 beginning on 20 July. Unfortunately, he won't be able to attend
            this session because of a change in the vacation schedule at the plant.
            Please could you send a list of the Total Immersion Courses in August
            for which he is still eligible?

            - I'm writing in connection with order n° 1234CV dated 11 February for
            20 jacks ref. n°

            56987M-5. Unfortunately, we have been forced to delay shipment due to
            the pilot's strike in France.

**** Stressing important points
            - I would like to highlight the new features of our user-friendly
            software packages.

            - We would like to draw your attention to our 7.2% discount on orders
            over US$20,000.

            - I would like to stress that we have always settled our invoices by the
            due date.

            - I would like to point out that these results were obtained under
            perfect conditions.

            - We would like to emphasize that we did everything possible to avoid
            this situation.

            - I want to underline my opposition to this proposal.

            - We need to focus on the discrepancies in the stock inventory.

**** Reminding
            - Don't forget to call us as soon as everything's up and running again.

            - Remember to unplug it before you open the back.

            - I'm afraid I must remind you that the protocol is being followed.

            - We do not appear to have received our copy of this month's issue of
            Network News Magazine.
**** Urgency and necessity
            - Please send the completed form back at your earliest convenience.

            - It is essential that you choose the color as soon as possible.

            - We will be forced to seek a legal solution to this matter.

            - We will stop all payments without further delay.

            - Stop production immediately.

**** Helping
            - Would you like us to prepare an estimate?

            - We are willing to bear part of the cost.

            - We would be willing to participate financially.

            - Please feel free to contact me if you need further information.

            - Please don't hesitate to call us if you have any questions.

            ECSPLICITE -- KEY PHRASES FOR EMAIL
**** Making complaints
            - We're having trouble connecting to internet.

            - We're having difficulty logging on.

            - We have to inform you that the service during the dinner was
            unsatisfactory.

            - Unfortunately, we haven't received payment for this invoice. Please
            could you settle your account without delay.

            - Unfortunately, we have received the wrong supplies and must return
            them under separate cover. Please credit our account for these items and
            call our production manager today with a new delivery date. A copy of
            our original order is attached for your convenience.

**** Warning
            - If the defective parts are not replaced without delay, we will be
            forced to take legal action.

            - Unless the shipping date is maintained, we will be forced to cancel
            our order.

            - Without reply within a week, we'll have to reconsider our partnership.

**** Answering complaints
            - I would like to apologize.

            - We are very sorry to have given you reason to complain.

            - We have investigated your complaint and discovered that an error was
            made in our Logistics Department.

            - We shipped a replacement for the defective part today.

**** Apologies
            - I'm sorry I couldn't call yesterday.

            - I'm afraid there's been a delay.

            - We apologize for any inconvenience caused and are taking steps to
            ensure this type of incident does not reoccur.

            - We apologize for sending last month's test results by mistake.

            - We must apologize for the delay in shipping your order. This is due to
            circumstances beyond our control. We are extremely sorry for any
            inconvenience this may have caused.

            - We are extremely sorry for the mix-up at our Shipping Office. Thank
            you for having returned the merchandise as soon as you noticed the
            mistake. Your complete shipment will be dispatched today. Please accept
            our apologies once again.

**** Misunderstandings
            - There seem to be some misunderstandings.

            - We were under the impression that all the meals were covered in the
            price quoted.

            - We were not aware that there were any problems.

            ECSPLICITE -- KEY PHRASES FOR EMAIL

**** Attaching documents and files
            - Here are the yield figures for October.

            - I'm attaching a copy of the contract for your convenience.

            - Please find attached our invoice n° 12345 for US$4,967.30.

            - You'll find hereafter our quotation for the repair work on your roof.

            - We are attaching the list of parts to be checked against your
            inventory under 'LIST.DOC'.
**** Concluding
            - I hope this information will help you.

            - Please do not hesitate to contact us if you have any further
            questions.

            - Once again, we apologize.

            - Please accept our apologies once again.

            - We hope that this hasn't caused you any inconvenience.

            - We are extremely sorry for the inconvenience caused.

            - I'm looking forward to seeing you there.

            - We look forward to doing business with you again in the near future.

** COMPLIMENTARY CLOSE
          - Rgds,

          - Regards,

          - Best wishes,

          - Best regards,

          - Kind regards,

          - Warm regards,

          - With apologies once again,

          - Sincerely,

          - Sincerely yours,

          - Yours sincerely,

          - Yours faithfully,
