* New Concept English 4
Fluency in English
* Unit 1
** Lesson 1 Finding fossil man 
Why are legends handed down by storytellers useful?
We can read of things that happened 5,000 years ago in the Near East,
where people first learned to write. But there are some parts of the
word where even now people cannot write. The only way that they can
preserve their history is to recount it as sagas -- legends handed down
from one generation of another. These legends are useful because they
can tell us something about migrations of people who lived long ago, but
none could write down what they did. Anthropologists wondered where the
remote ancestors of the Polynesian peoples now living in the Pacific
Islands came from. The sagas of these people explain that some of them
came from Indonesia about 2,000 years ago.
But the first people who were like ourselves lived so long ago that even
their sagas, if they had any, are forgotten. So archaeologists have
neither history nor legends to help them to find out where the first
'modern men' came from.
Fortunately, however, ancient men made tools of stone, especially flint,
because this is easier to shape than other kinds. They may also have
used wood and skins, but these have rotted away. Stone does not decay,
and so the tools of long ago have remained when even the bones of the
men who made them have disappeared without trace.
ROBIN PLACE Finding fossil man
fossil man (title) adj. 
recount v. 
saga n. 
legend n. 
migration n. 
anthropologist n. 
archaeologist n. 
ancestor n. 
Polynesian adj.
Indonesia n. 
flint n. 
rot n. 
5,000
,
2,000
** Lesson 2 Spare that spider
How much of each year do spiders spend killing insects?
Why, you may wonder, should spiders be our friends? Because they destroy
so many insects, and insects include some of the greatest enemies of the
human race. Insects would make it impossible for us to live in the
world; they would devour all our crops and kill our flocks and herds, if
it were not for the protection we get from insect-eating animals. We owe
a lot to the birds and beasts who eat insects but all of them put
together kill only a fraction of the number destroyed by spiders.
Moreover, unlike some of the other insect eaters, spiders never do the
harm to us or our belongings.
Spiders are not insects, as many people think, nor even nearly related
to them. One can tell the difference almost at a glance, for a spider
always has eight legs and insect never more than six.
How many spiders are engaged in this work no our behalf? One authority
on spiders made a census of the spiders in grass field in the south of
England, and he estimated that there were more than 2,250,000 in one
acre; that is something like 6,000,000 spiders of different kinds on a
football pitch. Spiders are busy for at least half the year in killing
insects. It is impossible to make more than the wildest guess at how
many they kill, but they are hungry creatures, not content with only
three meals a day. It has been estimated that the weight of all the
insects destroyed by spiders in Britain in one year would be greater
than the total weight of all the human beings in the country.
T. H. GILLESPLE Spare that spider from The Listener
New words and expressions
beast n. 
census n. 
acre n. 
content adj. 
86
225600
** Lesson 3 Matterhorn man
What was the main objective of early mountain climbers?
Modern alpinists try to climb mountains by a route which will give them
good sport, and the more difficult it is, the more highly it is
regarded. In the pioneering days, however, this was not the case at all.
The early climbers were looking for the easiest way to the top, because
the summit was the prize they sought, especially if it and never been
attained before. It is true that during their explorations they often
faced difficulties and dangers of the most perilous nature, equipped in
a manner with would make a modern climber shudder at the thought, but
they did not go out of their way to court such excitement. They had a
single aim, a solitary goal -- the top!
It is hard for us to realize nowadays how difficult it was for the
pioneers. Except for one or two places such as Zermatt and Chamonix,
which had rapidly become popular, Alpine village tended to be
impoverished settlements cut off from civilization by the high
mountains. Such inns as there were generally dirty and flea-ridden; the
food simply local cheese accompanied by bread often twelve months old,
all washed down with coarse wine. Often a valley boasted no inn at all,
and climbers found shelter wherever they could -- sometimes with the
local priest (who was usually as poor as his parishioners), sometimes
with shepherds or cheese-makers. Invariably the background was the same:
dirt and poverty, and very uncomfortable. For men accustomed to eating
seven-course dinners and sleeping between fine linen sheets at home, the
change to the Alps must have very hard indeed.
WALTER UNSWORTH Matterhorn Man
Matterhorn n. 
alpinist n. 
pioneer v.  n. 
summit n. 
attain v. 
perilous adj. 
shudder v. 
court v. 
solitary adj. 
impoverish v. 
Alpine adj. 
flea-ridden adj. 
coarse adj. 
boast v. 
parishioner n. 
shepherd n. 
linen n. 
the Alps n. 
--
-- 
7
** Lesson 4 Seeing hands
First listen and answer the following question.
How did Vera discover she had this gift of second sight?
Several cases have been reported in Russia recently of people who can
detect colours with their fingers, and even see through solid and walls.
One case concerns and eleven-year-old schoolgirl, Vera Petrova, who has
normal vision but who can also perceive things with different parts of
her skin, and through solid walls. This ability was first noticed by her
father. One day she came into his office and happened to put her hands
on the door of a locked safe. Suddenly she asked her father why he kept
so many old newspapers locked away there, and even described the way
they were done up in bundles.
Vera's curious talent was brought to the notice of a scientific research
institute in the town of Ulyanovsk, near where she lives, and in April
she was given a series of tests by a special commission of the Ministry
of Health of the Russian Federal Republic. During these tests she was
able to read a newspaper through an opaque screen and, stranger still,
by moving her elbow over a child's game of Lotto she was able to
describe the figures and colours printed on it; and, in another
instance, wearing stockings and slippers, to make out with her foot the
outlines and colours of a picture hidden under a carpet. Other
experiments showed that her knees and shoulders had a similar
sensitivity. During all these tests Vera was blindfold; and, indeed,
except when blindfold she lacked the ability to perceive things with her
skin. It was also found that although she could perceive things with her
fingers this ability ceased the moment her hands were wet.
ERIC DE MAUNY Seeing hands from The Listener
New words and expressions
solid adj. 
safe n. 
Ulyanovsk n. 
commission n. 
opaque adj. 
lotto n. 
slipper n. 
blindfold adj.& adv. 
.11
4
** Lesson 5 Youth
First listen and then answer the following question:
How does the writer like to treat young people?
People are always talking about 'the problem of youth'. If there is one
-- which I take leave to doubt -- then it is older people who create it,
not the young themselves. Let us get down to fundamentals and agree that
the young are after all human beings -- people just like their elders.
There is only one difference between an old man and a young one: the
young man has a glorious future before him and the old one has a
splendid future behind him: and maybe that is where the rub is.
When I was a teenager, I felt that I was just young and uncertain --
that I was a new boy in a huge school, and I would have been very
pleased to be regarded as something so interesting as a problem. For one
thing, being a problem gives you a certain identity, and that is one of
the things the young are busily engaged in seeking.
I find young people exciting. They have an air of freedom, and they not
a dreary commitment to mean ambitions or love of comfort. They are not
anxious social climbers, and they have no devotion to material things.
All this seems to me to link them with life, and the origins of things.
It's as if they were, in some sense, cosmic beings in violent and lovely
contrast with us suburban creatures. All that is in my mind when I meet
a young person. He may be conceited, ill-mannered, presumptuous or
fatuous, but I do not turn for protection to dreary cliches about
respect of elders -- as if mere age were a reason for respect. I accept
that we are equals, and I will argue with him, as an equal, if I think
he is wrong.
FIELDEN HUGHES from Out of the Air, The Listener
New words and expression 
leave n. 
fundamentals n. 
glorious adj. 
splendid adj. 
rub n. 
identity n. 
dreary adj. 
commitment n. 
mean adj. 
social climber 
devotion n. 
cosmic adj. 
suburban adj. 
conceited adj. 
presumptuous adj. 
fatuous adj. 
cliche n. 
-- 
--
--
** Lesson 6 The sporting spirit
.
How does the writer describe sport at the international level?
I am always amazed when I hear people saying that sport creates goodwill
between the nations, and that if only the common peoples of the would
could meet one another at football or cricket, they would have no
inclination to meet on the hattlefield. Even if one didn't know from
concrete examples (the 1936 Olympic Games, for instance) that
international sporting contests lead to orgies of hatred, one could
deduce if from general principles.
Nearly all the sports practised nowadays are competitive. You play to
win, and the game has little meaning unless you do your utmost to win.
On the village green, where you pick up sides and no feeling of local
patriotism is involved, it is possible to play simply for the fun and
exercise: but as soon as a the question of prestige arises, as soon as
you feel that you and some larger unit will be disgraced if you lose,
the most savage combative instincts are aroused. Anyone who has played
even in a school football match knows this. At the international level,
sport is frankly mimic warfare. But the significant thing is not the
behaviour of the players but the attitude of the spectators: and, behind
the spectators, of the nations who work themselves into furies over
these absurd contests, and seriously believe -- at any rate for short
periods -- that running, jumping and kicking a ball are tests of
national virtue.
GEORGE ORWELL The sporting spirit
New words and expression
goodwill n. 
cricket n. 
inclination n. 
contest n. 
orgy n. 
deduce v. 
competitive adj. 
patriotism n. 
disgrace v. 
savage adj. 
combative adj. 
mimic warfare 
behaviour n. 
absurd adj. 
1936
--  -- 
** Lesson 7 Bats
In what way does echo-location in bats play an utilitarian role?
Not all sounds made by animals serve as language, and we have only to
turn to that extraordinary discovery of echo-location in bats to see a
case in which the voice plays a strictly utilitarian role.
To get a full appreciation of what this means we must turn first to some
recent human inventions. Everyone knows that if he shouts in the
vicinity of a wall or a mountainside, an echo will come back. The
further off this solid obstruction, the longer time will elapse for the
return of the echo. A sound made by tapping on the hull of a ship will
be reflected from the sea bottom, and by measuring the time interval
between the taps and the receipt of the echoes, the depth of the sea at
that point can be calculated. So was born the echo-sounding apparatus,
now in general use in ships. Every solid object will reflect a sound,
varying according to the size and nature of the object. A shoal of fish
will do this. So it is a comparatively simple step from locating the sea
bottom to locating a shoal of fish. With experience, and with improved
apparatus, it is now possible not only to locate a shoal but to tell if
it is herring, cod, or other well-known fish, by the pattern of its
echo.
It has been found that certain bats emit squeaks and by receiving the
echoes, they can locate and steer clear of obstacles -- or locate flying
insects on which they feed. This echo-location in bats is often compared
with radar, the principle of which is similar.
MAURICE BURTON Curiosities of animal life
New words and expressions
bat n. 
strictly adv. 
utilitarian adj.
appreciation n. 
elapse v. 
hull n. 
interval n. 
receipt n. 
apparatus n. 
shoal n. 
herring n. 
cod n. 
squeak n. 
** Lesson 8 Trading standards
What makes trading between rich countries difficult?
Chickens slaughtered in the United States, claim officials in Brussels,
are not fit to grace European tables. No, say the American: our fowl are
fine, we simply clean them in a different way. These days, it is
differences in national regulations, far more than tariffs, that put
sand in the wheels of trade between rich countries. It is not just
farmers who are complaining. An electric razor that meets the European
Union's safety standards must be approved by American testers before it
can be sold in the United States, and an American-made dialysis machine
needs the EU's okay before is hits the market in Europe.
As it happens, a razor that is safe in Europe is unlikely to electrocute
Americans. So, ask businesses on both sides of the Atlantic, why have
two lots of tests where one would do? Politicians agree, in principle,
so America and the EU have been trying to reach a deal which would
eliminate the need to double-test many products. They hope to finish in
time for a trade summit between America and the EU on May 28TH. Although
negotiators are optimistic, the details are complex enough that they may
be hard-pressed to get a deal at all.
Why? One difficulty is to construct the agreements. The Americans would
happily reach one accord on standards for medical devices and them
hammer out different pacts covering, say, electronic goods and drug
manufacturing. The EU -- following fine continental traditions -- wants
agreement on general principles, which could be applied to many types of
products and perhaps extended to other countries.
From: The Economist, May 24th, 1997
slaughter v. 
fit adj. 
grace v. ...
tariff n. 
standard n. 
dialysis n. 
electrocute v. 
eliminate v. 
accord n. 
device n. 
hammer out v. 
pact n. 
528
--  --
** Lesson 9 Royal espionage
What important thing did King Alfred learn when he penetrated the Danish
camp of Guthrum?
Alfred the Great acted his own spy, visiting Danish camps disguised as a
minstrel. In those days wandering minstrels were welcome everywhere.
They were not fighting men, and their harp was their passport. Alfred
had learned many of their ballads in his youth, and could vary his
programme with acrobatic tricks and simple conjuring.
While Alfred's little army slowly began to gather at Athelney, the king
himself set out to penetrate the camp of Guthrum, the commander of the
Danish invaders. There had settled down for the winter at Chippenham:
thither Alfred went. He noticed at once that discipline was slack: the
Danes had the self-confidence of conquerors, and their security
precautions were casual. They lived well, on the proceeds of raids on
neighbouring regions. There they collected women as well as food and
drink, and a life of ease had made them soft.
Alfred stayed in the camp a week before he returned to Athelney. The
force there assembled was trivial compared with the Danish horde. But
Alfred had deduced that the Danes were no longer fit for prolonged
battle: and that their commissariat had no organization, but depended on
irregular raids.
So, faced with the Danish advance, Alfred did not risk open battle but
harried the enemy. He was constantly on the move, drawing the Danes
after him. His patrols halted the raiding parties: hunger assailed the
Danish army. Now Alfred began a long series of skirmishes -- and within
a month the Danes had surrendered. The episode could reasonably serve as
a unique epic of royal espionage!
BERNARD NEWMAN Spies in Britain
espionage n. 
Alfred 871-899 
Danish adj. 
minstrel n. 
wandering adj. 
harp n. 
ballad n. 
acrobatic adj. 
conjuring n. 
Athelney n. 
Chippenham n. 
thither adv. 
Dane n. 
slack adj. 
conqueror n. 
casual adj. 
precaution n. 
proceeds n. 
assemble v. 
trivial adj. 
prolonged adj. 
commissariat n. 
episode n. 
epic n. 
harry v. 
assail v. 
skirmish n. 
.
** Lesson 10 Silicon valley
What does the computer industry thrive on apart from anarchy?
Technology trends may push Silicon Valley back to the future. Carver
Mead, a pioneer in integrated circuits and a professor of computer
science at the California Institute of Technology, notes there are now
work-stations that enable engineers to design, test and produce chips
right on their desks, much the way an editor creates a newsletter on a
Macintosh. As the time and cost of making a chip drop to a few days and
a few hundred dollars, engineers may soon be free to let their
imaginations soar without being penalized by expensive failures. Mead
predicts that inventors will be able to perfect powerful customized
chips over a weekend at the office -- spawning a new generation of
garage start-ups and giving the U.S. a jump on its foreign rivals in
getting new products to market fast. 'We're got more garages with smart
people,' Mead observes. 'We really thrive on anarchy.'
And on Asians. Already, orientals and Asian Americans constitute the
majority of the engineering staffs at many Valley firms. And Chinese,
Korean, Filipino and Indian engineers are graduating in droves from
California's colleges. As the heads of next-generation start-ups, these
Asian innovators can draw on customs and languages to forge righter
links with crucial Pacific Rim markets. For instance, Alex Au, a
Stanford Ph. D. from Hong Kong, has set up a Taiwan factory to challenge
Japan's near lock on the memory-chip market. India-born N.Damodar
Reddy's tiny California company reopened an AT & T chip plant in Kansas
City last spring with financing from the state of Missouri. Before it
becomes a retirement village, Silicon Valley may prove a classroom for
building a global business.
US NEWS AND WORLD REPORT, October 2, 1989
silicon n. 
integrated adj. 
circuit n. 
California n. 
workstation n. 
chip n. 
newsletter n. 
Macintosh n. 
penalize v. 
customize v. 
spawn v. 
thrive v. 
anarchy n. 
oriental n. 
constitute v. 
drove n. 
innovator n. 
forge v. 
memory-chip n. 
Kansas n. 
Missouri n. 
. --
--
--
.N..
** Lesson 11 How to grow old
What, according to the author, is the best way to overcome the fear of
death as you get older?
Some old people are oppressed by the fear of death. In the young there
is a justification for this feeling. Young men who have reason to fear
that they will be killed in battle may justifiably feel bitter in the
thought that they have cheated of the best things that life has to
offer. But in an old man who has known human joys and sorrows, and has
achieved whatever work it was in him to do, the fear of death is
somewhat abject and ignoble. The best way to overcome it -- so at least
it seems to me -- is to make your interests gradually wider and more
impersonal, until bit by bit the walls of the ego recede, and your life
becomes increasingly merged in the universal life. An individual human
existence should be like a river -- small at first, narrowly contained
within its banks, and rushing passionately past boulders and over
waterfalls. Gradually the river grows wider, the banks recede, the
waters flow more quietly, and in the end, without any visible break,
they become merged in the sea, and painlessly lose their individual
being. The man who, in old age, can see his life in this way, will not
suffer from the fear of death, since the things he cares for will
continue. And if, with the decay of vitality, weariness increases, the
thought of rest will be not unwelcome. I should wish to die while still
at work, knowing that others will carry on what I can no longer do, and
content in the thought that what was possible has been done.
BERTRAND RUSSELL How to grow old from Portraits from Memory
oppress v. 
justification n. 
justifiably adv. 
cheat v. 
abject adj. 
ignoble adj. 
impersonal adj. 
ego n. 
receded v. 
increasing adv. 
passionately adv. 
painlessly adv. 
vitality n. 
weariness n. 
--  --
** Lesson 12 Banks and their customers
Why is there no risk to the customer when a bank prints the customer's
name on his cheques?
When anyone opens a current account at a bank, he is lending the bank
money, repayment of which he may demand at any time, either in cash or
by drawing a cheque in favour of another person. Primarily, the
banker-customer relationship is that of debtor and creditor -- who is
which depending on whether the customer's account is in credit or is
overdrawn. But, in addition to that basically simple concept, the bank
and its customer owe a large number of obligations to one another. Many
of these obligations can give in to problems and complications but a
bank customer, unlike, say, a buyer of goods, cannot complain that the
law is loaded against him.
The bank must obey its customer's instructions, and not those of anyone
else. When, for example, a customer first opens an account, he instructs
the bank to debit his account only in respect of cheques draw by
himself. He gives the bank specimens of his signature, and there is a
very firm rule that the bank has no right or authority to pay out a
customer's money on a cheques on which its customer's signature has been
forged. It makes no difference that the forgery may have been a very
skilful one: the bank must recognize its customer's signature. For this
reason there is no risk to the customer in the practice, adopted by
banks, of printing the customer's name on his cheques. If this
facilitates forgery, it is the bank which will lose, not the customer.
GORDON BARRIE and AUBREY L. DLAMOND The Consumer Society and the Law
current adj. 
account n. 
cash n. 
debtor n. 
debtor n. 
creditor n. 
obligation n. 
complication n. 
debit v. ...
specimen n. 
forge v. 
forgery n. 
adopt v. 
facilitate v. 
* Unit 2
** Lesson 13 The search for oil
What do oilmen want to achieve as soon as they strike oil?
The deepest holes of all made for oil, and they go down to as much as
25,0000 feet. But we not need to send men down to get the oil our, as we
must with other mineral deposits. The holes are only borings, less than
a foot in diameter. My particular experience is largely in oil, and the
search for oil has done more to improve deep drilling than any other
mining activity. When is has been decided where we are going to drill,
we put up at the surface an oil derrick. It has to be tall because it is
like a giant block and tackle, and we have to lower into the ground and
haul out of the ground great lengths of drill pipe which are rotated by
an engine at the top and are fitted with a cutting bit at the bottom.
The geologist needs to know what rocks the drill has reached, so every
so often a sample is obtained with a coring bit. It cuts a clean
cylinder of rock, from which can be seen the strata the drill has been
cutting through. Once we get down to the oil, it usually flows to the
surface because great pressure, either from or water, is pushing it.
This pressure must be under control, and we control it by means of the
mud which we circulate down the drill pipe. We endeavour to avoid the
old, romantic idea of a gusher, which wastes oil and gas. We want it to
stay down the hole until we can lead it off in a controlled manner.
T.F.GASKELL The Search for the Earth's Minerals from Discovery
mineral adj. 
boring n. 
derrick n. 
block and tackle 
haul v. 
rotate v. 
cutting bit 
geologist n. 
coring 
cylinder n. 
strata n. []([]stratumstrata [])
circulate v. 
gusher n. 
25,0001
** Lesson 14 The Butterfly Effect
Why do small errors make it impossible to predict the weather system
with a high degree of accuracy?
Beyond two or three days, the world's best weather forecasts are
speculative, and beyond six or seven they are worthless.
The Butterfly Effect is the reason. For small pieces of weather -- and
to a global forecaster, small can mean thunderstorms and blizzards --
any prediction deteriorates rapidly. Errors and uncertainties multiply,
cascading upward through a chain of turbulent features, from dust devils
and squalls up to continent-size eddies that only satellites can see.
The modern weather models work with a grid of points of the order of
sixty miles apart, and even so, some starting data has to guessed, since
ground stations and satellites cannot see everywhere. But suppose the
earth could be covered with sensors spaced one foot apart, rising at
one-foot intervals all the way to the top of the atmosphere. Suppose
every sensor gives perfectly accurate readings of temperature, pressure,
humidity, and any other quantity a meteorologist would want. Precisely
at noon an infinitely powerful computer takes all the data and
calculates what will happen at each point at 12.01, then 1202, then
12.03...
The computer will still be unable to predict whether Princeton, New
Jersey, will have sun or rain on a day one month away. At noon the
spaces between the sensors will hide fluctuations that the computer will
not know about, tiny deviations from the average. By 12.01, those
fluctuations will already have created small errors one foot away. Soon
the errors will have multiplied to the ten-foot scale, and so on up to
the size of the globe.
JAMES GLEICK, Chaos
forecast n. 
speculative adj. 
blizzard n. 
deteriorate v. 
multiply v. 
cascade v. 
turbulent adj. 
dust devil 
squall n. 
eddy n. 
grid n. 
sensor n. 
humidity n. 
meteorologist n. 
Princeton n. 
New Jersey n. 
fluctuation n. 
deviation n. 
--
--
6011120112021203
11201110
** Lesson 15 Secrecy in industry
Why is secrecy particularly important in the chemical industries?
Two factors weigh heavily against the effectiveness of scientific
research in industry. One is the general atmosphere of secrecy in which
it is carried out, the other the lack of freedom of the individual
research worker. In so far as any inquiry is a secret one, it naturally
limits all those engaged in carrying it out from effective contact with
their fellow scientists either in other countries or in universities, or
even, often enough, in other departments of the same firm. The degree of
secrecy naturally varies considerably. Some of the bigger firms are
engaged in researches which are of such general and fundamental nature
that it is a positive advantage to them not to keep them secret. Yet a
great many processes depending on such research are sought for with
complete secrecy until the stage at which patents can be taken out. Even
more processes are never patented at all but kept as secret processes.
This applies particularly to chemical industries, where chance
discoveries play a much larger part than they do in physical and
mechanical industries. Sometimes the secrecy goes to such an extent that
the whole nature of the research cannot be mentioned. Many firms, for
instance, have great difficulty in obtaining technical or scientific
books from libraries because they are unwilling to have names entered as
having taken out such and such a book, for fear the agents of other
firms should be able to trace the kind of research they are likely to be
undertaking.
J.D. BERNAL The Social Function of Science
New words and expressions
secrecy n. 
effectiveness n. 
inquiry n. 
positive adj. 
process n. 
patent n.  v. 
agent n. 
** Lesson 16 The modern city
What is the author's main argument about the modern city?
In the organization of industrial life the influence of the factory upon
the physiological and mental state of the workers has been completely
neglected. Modern industry is based on the conception of the maximum
production at lowest cost, in order that an individual or a group of
individuals may earn as much money as possible. It has expanded without
any idea of the true nature of the human beings who run the machines,
and without giving any consideration to the effects produced on the
individuals and on their descendants by the artificial mode of existence
imposed by the factory. The great cities have been built with no regard
for us. The shape and dimensions of the skyscrapers depend entirely on
the necessity of obtaining the maximum income per square foot of ground,
and of offering to the tenants offices and apartments that please them.
This caused the construction of gigantic buildings where too large
masses of human beings are crowded together. Civilized men like such a
way of living. While they enjoy the comfort and banal luxury of their
dwelling, they do not realize that they are deprived of the necessities
of life. The modern city consists of monstrous edifices and of dark,
narrow streets full of petrol fumes and toxic gases, torn by the noise
of the taxicabs, lorries and buses, and thronged ceaselessly by great
crowds. Obviously, it has not been planned for the good of its
inhabitants.
ALEXIS CARREL Man, the Unknown
physiological adj. 
maximum adj. 
consideration n. 
descendant n. 
artificial n. 
impose v. 
dimension n. 
skyscraper n. 
tenant n. 
civilized adj. 
banal adj. 
luxury n. 
deprive v. 
monstrous adj. 
edifice n. 
toxic adj. 
ceaselessly adv. 
throng v. 
** Lesson 17 A man-made disease
What factor helped to spread the disease of myxomatosis?
In the early days of the settlement of Australia, enterprising settlers
unwisely introduced the European rabbit. This rabbit had no natural
enemies in the Antipodes, so that it multiplied with that promiscuous
abandon characteristic of rabbits. It overran a whole continent. It
caused devastation by burrowing and by devouring the herbage which might
have maintained millions of sheep and cattle. Scientists discovered that
this particular variety of rabbit (and apparently no other animal) was
susceptible to a fatal virus disease, myxomatosis. By infecting animals
and letting them loose in the burrows, local epidemics of this disease
could be created. Later it was found that there was a type of mosquito
which acted as the carrier of this disease and passed it on to the
rabbits. So while the rest of the world was trying to get rid of
mosquitoes, Australia was encouraging this one. It effectively spread
the disease all over the continent and drastically reduced the rabbit
population. It later became apparent that rabbits were developing a
degree of resistance to this disease, so that the rabbit population was
unlikely to be completely exterminated. There were hopes, however, that
the problem of the rabbit would become manageable.
Ironically, Europe, which had bequeathed the rabbit as a pest to
Australia, acquired this man-made disease as a pestilence. A French
physician decided to get rid of the wild rabbits on his own estate and
introduced myxomatosis. It did not, however, remain within the confines
of his estate. It spread through France, Where wild rabbits are not
generally regarded as a pest but as sport and a useful food supply, and
it spread to Britain where wild rabbits are regarded as a pest but where
domesticated rabbits, equally susceptible to the disease, are the basis
of a profitable fur industry. The question became one of whether Man
could control the disease he had invented.
RITCHIE CALDER Science Makes Sense
settlement n. 
enterprising adj. 
settler n. 
Antipodes n. 
promiscuous adj. 
abandon n. 
overrun v. 
devastation n. 
burrow v. 
susceptible adj. 
virus n. 
myxomatosis n. 
infect v. 
epidemic n. 
mosquito n. 
carrier n. 
exterminate v. 
ironically adv. 
bequeath v. ...
pest n. 
pestilence n. 
confine n. 
domesticate v. 
** Lesson 18 Porpoises
What would you say is the main characteristic of porpoises?
There has long been a superstition among mariners that porpoises will
save drowning men by pushing them to the surface, or protect them from
sharks by surrounding them in defensive formation. Marine Studio
biologists have pointed out that, however intelligent they may be, it is
probably a mistake to credit dolphins with any motive of lifesaving. On
the occasions when they have pushed to shore an unconscious human being
they have much more likely done it out of curiosity or for sport, as in
riding the bow waves of a ship. In 1928 some porpoises were photographer
working like beavers to push ashore a waterlogged mattress. If, as has
been reported, they have protected humans from sharks, it may have been
because curiosity attracted them and because the scent of a possible
meal attracted the sharks. Porpoises and sharks are natural enemies. It
is possible that upon such an occasion a battle ensued, with the sharks
being driven away or killed.
Whether it be bird, fish or beast, the porpoise is intrigued with
anything that is alive. They are constantly after the turtles, who
peacefully submit to all sorts of indignities. One young calf especially
enjoyed raising a turtle to the surface with his snout and then shoving
him across the tank like an aquaplane. Almost any day a young porpoise
may be seen trying to turn a 300-pound sea turtle over by sticking his
snout under the edge of his shell and pushing up for dear life. This is
not easy, and may require two porpoises working together. In another
game, as the turtle swims across the oceanarium, the first porpoise
swoops down from above and butts his shell with his belly. This knocks
the turtle down several feet. He no sooner recovers his equilibrium than
the next porpoise comes along and hits him another crack. Eventually the
turtle has been butted all the way down to the floor of the tank. He is
now satisfied merely to try to stand up, but as soon as he does so a
porpoise knocks him flat. The turtle at last gives up by pulling his
feet under his shell and the game is over.
RALPH NADING HILL Window in the Sea
porpoise n. 
mariner n. 
shark n. 
formation n. 
dolphin n. 
unconscious adj. 
beaver n. 
ashore adv. 
waterlogged adj. 
scent n. 
ensue v. 
intrigue v. 
indignity n. 
snout n. 
shove v. 
aquaplane n. 
oceanarium n. 
swoop v. 
belly n. 
equilibrium n. 
butt v. 
crack n. 
1928
3004
** Lesson 19 The stuff of dreams
What is going on when a person experiences rapid eye-movements during
sleep?
It is fairly clear that sleeping period must have some function, and
because there is so much of it the function would seem to e important.
Speculations about is nature have been going on for literally thousands
of years, and one odd finding that makes the problem puzzling is that it
looks very much as if sleeping is not simply a matter of giving the body
a rest. 'Rest', in terms of muscle relaxation and so on, can be achieved
by a brief period lying, or even sitting down. The body's tissues are
self-repairing and self-restoring to a degree, and function best when
more or less continuously active. In fact a basic amount of movement
occurs during sleep which is specifically concerned with preventing
muscle inactivity.
If it is not a question of resting the body, then perhaps it is the
brain that needs resting? This might be a plausible hypothesis were it
not for two factors. First the electroencephalograph (which is simply a
device for recording the electrical activity of the brain by attaching
electrodes to the scalp) shows that while there is a change in the
pattern of activity during sleep, there is no evidence that the total
amount of activity is any less. The second factor is more interesting
and more fundamental. Some years ago an American psychiatrist named
William Dement published experiments dealing with the recording of
eye-movements during sleep. He showed that the average individual's
sleep cycle is punctuated with peculiar bursts of eye-movements, some
drifting and slow, others jerky and rapid. People woken during these
periods of eye-movements generally reported that they had been dreaming.
When woken at other times they reported no dreams. If one group of
people were disturbed from their eye-movement sleep for several nights
on end, and another group were disturbed for an equal period of time but
when they were no exhibiting eye-movements, the first group began to
show some personality disorders while the others seemed more or less
unaffected. The implications of all this were that it was not the
disturbance of sleep that mattered, but the disturbance of dreaming.
CHRISTOPHER EVANS The stuff of dreams from The Listener
speculation n. 
literally adv. 
odd adj. 
tissue n. 
plausible adj. 
hypothesis n. 
electroencephalograph n. 
electrode n. 
scalp n. 
psychiatrist n. 
punctuate v. 
jerky adj. 
disorder n. 
implication n. 
** Lesson 20 Snake poison
What are the two different ways in which snake poison acts?
How it came about that snakes manufactured poison is a mystery. Over the
periods their saliva, a mild, digestive juice like our own, was
converted into a poison that defies analysis even today. It was not
forced upon them by the survival competition; they could have caught and
lived on prey without using poison, just as the thousands of
non-poisonous snakes still do. Poison to a snake is merely a luxury; it
enables it to get its food with very little effort, no more effort than
one bite. And why only snakes? Cats, for instance, would be greatly
helped; no running fights with large, fierce rats or tussles with grown
rabbits -- just a bite and no more effort needed. In fact, it would be
an assistance to all carnivores though it would be a two-edged weapon
when they fought each other. But, of the vertebrates, unpredictable
Nature selected only snakes (and one lizard). One wonders saliva into
why Nature, with respect from that of others, as other on the blood.
In the conversion of saliva into poison, one might suppose that a fixed
process took place. It did not; some snakes manufacture a poison
different in every respect from that of others, as different as arsenic
is from strychnine, and having different effects. One poison acts on the
nerves, the other on the blood.
The makers of the nerve poison include the mambas and the cobras and
their venom is called neurotoxic. Vipers (adders) and rattlesnakes
manufacture the blood poison, which is known as haemolytic. Both poisons
are unpleasant, but by far the more unpleasant is the blood poison. It
is said that the nerve poison is the more primitive of the two, that the
blood poison is, so to speak, a newer product from an improved formula.
Be that as it may, the nerve poison does its business with man far more
quickly than the blood poison. This, however, means nothing. Snakes did
not acquire their poison for use against man but for use against prey
such as rats and mice, and the effects on these of viperine poison is
almost immediate.
JOHN CROMPTON The snake
saliva n. 
digestive adj. 
defy v. 
analysis n. 
prey n. 
fierce adj. 
tussle n. 
carnivore n. 
vertebrate n. 
lizard n. 
concoct v. 
potency n. 
conversion n. 
arsenic n. 
strychnine n. 
mamba n. 
cobra n. 
venom n. 
neurotoxic adj. 
viper n. 
adder n. 
rattlesnake n. 
haemolytic adj. 
viperine adj. 
** Lesson 21 William S. Hart and the early 'Western' film
.S. '
How did William Hart's childhood prepare him for his acting role in
Western films?
William S. hart was, perhaps, the greatest of all Western stars, fro
unlike Gary Cooper and John Wayne he appeared in nothing but Westerns.
From 1914 to 1924 he was supreme and unchallenged. It was Hart who
created the basic formula of the Western film, and devised the
protagonist he played in every film he made, the good-had man, the
accidental-noble outlaw, or the honest-but-framed cowboy, or the sheriff
made suspect by vicious gossip; in short, the individual in conflict
with himself and his frontier environment.
Unlike most of his contemporaries in Hollywood, Hart actually knew
something of the old West. He had lived in it as a child when it was
already disappearing, and his hero was firmly rooted in his memories and
experiences, and in both the history and the mythology of the vanished
frontier. And although no period or place in American history has been
more absurdly romanticized, myth and reality did join hands in at least
one arena, the conflict between the individual and encroaching
civilization.
Men accustomed to struggling for survival against the elements and
Indians were bewildered by politicians, bankers and businessmen, and
unhorsed by fences, laws and alien taboos. Hart's good-bad man was
always an outsider, always one of the disinherited, and if he found it
necessary to shoot a sheriff or rob a bank along the way, his early
audiences found it easy to understand and forgive, especially when it
was Hart who, in the end, overcame the attacking Indians.
Audiences in the second decade of the twentieth century found it
pleasant to escape to a time when life, though hard, was relatively
simple. We still do; living in a world in which undeclared aggression,
war, hypocrisy, chicanery, anarchy and impending immolation are part of
our daily lives, we all want a code to live by.
CARL FOREMAN Virtue and a Fast Gun from The Observer
Supreme adj. 
protagonist n. 
outlaw n. 
framed adj. 
vicious adj. 
mythology n. 
vanished adj. 
absurdly adv. 
arena n. 
encroaching adj. 
Indian n. 
bewilder v. 
alien adj. 
taboo n. 
disinherit v. ...
undeclared adj. 
hypocrisy n. 
chicanery n. 
impending adj. 
immolation n. 
code n. 
.S...19141924
2020
** Lesson 22 Knowledge and progress
In what two areas have people made no 'progress' at all?
Why does the idea of progress loom so large in the modern world? Surely
progress of a particular kind is actually taking place around us and is
becoming more and more manifest. Although mankind has undergone no
general improvement in intelligence or morality, it has made
extraordinary progress in the accumulation of knowledge. Knowledge began
to increase as soon as the thoughts of one individual could be
communicated to another by means of speech. With the invention of
writing, a great advance was made, for knowledge could then be not only
communicated but also stored. Libraries made education possible, and
education in its turn added to libraries: the growth of knowledge
followed a kind of compound interest law, which was greatly enhanced by
the invention of printing. All this was comparatively slow until, with
the coming of science, the tempo was suddenly raised. Then knowledge
began to be accumulated according to a systematic plan. The trickle
became a stream; the stream has now become a torrent. Moreover, as soon
as new knowledge is acquired, it is now turned to practical account.
What is called 'modern civilization' is not the result of a balanced
development of all man's nature. but of accumulated knowledge applied to
practical life. The problem now facing humanity is: What is going to be
done with all this knowledge? As is so often pointed out, knowledge is a
two-edged weapon which can be used equally for good or evil. It is now
being used indifferently for both. Could any spectacle, for instance, be
more grimly whimsical than that of gunners ourselves very seriously what
will happen if this twofold use of knowledge, with its ever-increasing
power, continues.
G.N.M.TYRRELL The Personality of Man
loom v. 
manifest adj.
morality n. 
communicate v. 
compound adj. 
enhance v. 
tempo n. 
trickle n. 
torrent n. 
humanity n. 
indifferently adv. 
grimly adv. 
whimsical adj. 
shatter v. 
twofold adj. 
** Lesson 23 Bird flight
What are the two main types of bird flight described by the author?
No two sorts of birds practise quite the same sort of flight; the
varieties are infinite; but two classes may be roughly seen. Any shi
that crosses the Pacific is accompanied for many days by the smaller
albatross, Which may keep company with the vessel for an hour without
visible or more than occasional movement of wing. The currents of air
that the walls of the ship direct upwards, as well as in the line of its
course, are enough to give the great bird with its immense wings
sufficient sustenance and progress. The albatross is the king of the
gliders, the class of fliers which harness the air to their purpose, but
must yield to its opposition. In the contrary school, the duck is
supreme. It comes nearer to the engines with which man has 'conquered'
the air, as he boasts. Duck, and like them the pigeons, are endowed with
such-like muscles, that are a good part of the weight of the bird, and
these will ply the short wings with such irresistible power that they
can bore for long distances through an opposing gale before exhaustion
follows. Their humbler followers, such as partridges, have a like power
of strong propulsion, but soon tire. You may pick them up in utter
exhaustion, if wind over the sea has driven them to a long journey. The
swallow shares the virtues of both schools in highest measure. It tires
not, nor does it boast of its power; but belongs to the air, travelling
it may be six thousand miles to and from its northern nesting home,
feeding its flown young as it flies, and slipping through we no longer
take omens from their flight on this side and that; and even the most
superstitious villagers no longer take off their hats to the magpie and
wish it good-morning.
WILLIAM BEACH THOMAS A Countryman's Creed
albatross n. 
sustenance n. 
glider n. 
harness v. 
endow v. 
ply v. 
gale n. 
partridge n. 
like adj. 
propulsion n. 
utter adj. 
slip v. 
adverse adj. 
omen n. 
6000
** Lesson 24 Beatuy
What do glimpses of beauty, either in nature or art, often suggest to
the human mind?
A young man sees a sunset and, unable to understand or to express the
emotion that it rouses in him, concludes that it must be the gateway to
world that lies beyond. It is difficult for any of us in moments of
intense aesthetic experience to resist the suggestion that we are
catching a glimpse of a light that shines down to us from a different
realm of existence, different and, because the experience is intensely
moving, in some way higher. And, though the gleams blind and dazzle, yet
do they convey a hint of beauty and serenity greater than we have known
or imagined. Greater too than we can describe; for language, which was
invented to convey the meanings of this world, cannot readily be fitted
to the uses of another.
That all great has this power of suggesting a world beyond is
undeniable. In some moods, Nature shares it. There is no sky in June so
blue that it does not point forward to a bluer, no sunset so beautiful
that it does not waken the vision of a greater beauty, a vision which
passes before it is fully glimpsed, and in passing leaves and
indefinable longing and regret. But, if this world is not merely a bad
joke, life a vulgar flare amid the cool radiance of the stars, and
existence an empty laugh braying across the mysteries; if these
intimations of a something behind and beyond are not evil humour born of
indigestion, or whimsies sent by the devil to mock and madden us. if, in
a word, beauty means something, yet we must not seek to interpret the
meaning. If we glimpse the unutterable, it is unwise to try to utter it,
nor should we seek to invest with significance that which we cannot
grasp. Beauty in terms of our human meanings is meaningless.
C.E.M.JOAD Pieces of Mind
intense adj. 
aesthetic adj. 
realm n. 
serenity n. 
undeniable adj. 
indefinable adj. 
vulgar adj. 
radiance n. 
intimation n. 
unutterable adj. 
invest v. 
* Unit 3
** Lesson 25 Non-auditory effects of noise
What conclusion does the author draw about noise and health in this
piece?
May people in industry and the Services, who have practical experience
of noise, regard any investigation of this question as a waste of time;
they are not prepared even to admit the possibility that noise affects
people. On the other hand, those who dislike noise will sometimes use
most inadequate evidence to support their pleas for a quieter society.
This is a pity, because noise abatement really is a good cause, and it
is likely to be discredited if it gets to be associated with had
science.
One allegation often made is that noise produces mental illness. A
recent article in a weekly newspaper, for instance, was headed with a
striking illustration of a lady in a state of considerable distress,
with the caption 'She was yet another victim, reduced to a screaming
wreck'. On turning eagerly to the text, one learns that the lady was a
typist who found the sound of office typewriters worried her more and
more until eventually she had to go into a mental hospital. Now the snag
in this sort of anecdote is of course that one merely a symptom? Another
patient might equally well complain that her neighbours were combining
to slander her and persecute her, and yet one might be cautious about
believing this statement.
What is needed in case of noise is a study of large numbers of people
living under noisy conditions, to discover whether they are mentally ill
more often than other people are. Some time ago the United States Navy,
for instance, examined a very large number of men working on aircraft
carriers: the study was known as Project Anehin. It can be unpleasant to
live even several miles from an aerodrome; if you think what it must be
like to share the deck of a ship with several squadrons of jet aircraft,
you will realize that a modern navy is a good place to study noise. But
neither psychiatric interviews nor objective tests were able to show any
effects upon these American sailors. This result merely confirms earlier
American and British studies: if there is any effect of noise upon
mental health, it must be so small that present methods of psychiatric
diagnosis cannot find it. That does not prove that it does exist: but it
does mean that noise is less dangerous than, say, being brought up in an
orphanage -- which really is mental health hazard.
D.E.BROADBENT Non-auditory effects of noise from Science Survey
auditory adj. 
inadequate adj. 
plea n. 
abatement n. 
discredit v. 
allegation n. 
caption n. 
wreck n. 
snag n. 
anecdote n. 
slander v. 
persecute v. 
squadron n. 
psychiatric adj. 
diagnosis n. 
orphanage n. 
--  --
** Lesson 26 The past life of the earth
What is the main condition for the preservation of the remains of any
living creature?
It is animals and plants which lived in or near water whose remains are
most likely to be preserved, for one of the necessary conditions of
preservation is quick burial, and it is only in the seas and rivers, and
sometimes lakes, where mud and sit have been continuously deposited,
that bodies and the can be rapidly covered over and preserved.
But even in the most favourable circumstances only a small fraction of
the creatures that die are preserved in this way before decay sets in
or, even more likely, before scavengers eat them. After all, all living
creatures live by feeding on something else, whether it be plant or
animal, dead or alive, and it is only by chance that such a fate is
avoided. The remains of plants and animals that lived on land are much
more rarely preserved, for there is seldom anything to cover them over.
When you think of the innumerable birds that one sees flying bout, not
to mention the equally numerous small animals like field mice and voles
which you do not see, it is very rarely that one comes across a dead
body, except, of course, on the roads. They decompose and are quickly
destroyed by the weather or eaten by some other creature.
It is almost always due to some very special circumstances that traces
of land animals survive, as by falling into inaccessible caves, or into
an ice crevasse, like the Siberian mammoths, when the whole animal is
sometimes preserved, as in a refrigerator. This is what happened to the
famous Beresovka mammoth which was found preserved and in good
condition. In his mouth were the remains of fir trees -- the last meal
that he had before he fell into the crevasse and broke his back. The
mammoth has now just a suburb of Los Angeles. Apparently what happened
was that water collected on these tar pits, and the bigger animals like
the elephants ventured out on to the apparently firm surface to drink,
and were promptly bogged in the tar. And then, when they were dead, the
carnivores, like the sabre-toothed cats and the giant wolves, came out
to feed and suffered exactly the same fate. There are also endless
numbers of birds in the tar as well.
ERROL WHITE The past life of the earth from Discovery
preservation n. 
silt n. 
scavenger n. 
vole n. 
decompose v. 
inaccessible adj. 
crevasse n. 
Siberian adj.
palaeontological adj. 
St. Petersburg n. 
sabre-toothed adj. 
venture v. 
bogged adj. 
--
..
--
** Lesson 27 The 'Vasa'
What happened to the 'Vasa' almost immediately after she was launched?
From the seventeenth-century empire of Sweden, the story of a galleon
that sank at the start of her maiden voyage in 1628 must be one of the
strangest tales of the sea. For nearly three and a half centuries she
lay at the bottom of Stockholm harbour until her discovery in 1956. This
was the Vasa, royal flagship of the great imperial fleet.
King Gustavus Adolphus, 'The Northern Hurricane', then at the height of
his military success in the Thirty Years' War, had dictated her
measurements and armament. Triple gun-decks mounted sixty-four bronze
cannon. She was intended to play a leading role in the growing might of
Sweden.
As she was prepared of her maiden voyage on August 10, 1628, Stockholm
was in a ferment. From the Skeppsbron and surrounding islands the people
watched this thing of beauty begin to spread her sails and catch the
wind. They had laboured for three years to produce this floating work of
art; she was more richly carved and ornamented than any previous ship.
The high stern castle was a riot of carved gods, demons, knights, kings,
warriors, mermaids, cherubs; and zoomorphic animal shapes ablaze with
rea and gold and blue, symbols of courage, power, and cruelty, were
portrayed to stir the imaginations of the superstitious sailors of the
day.
Then the cannons of the anchored warships thundered a salute to which
the Vasa fired in reply. As the emerged from her drifting cloud of gun
smoke with the water churned to foam beneath her bow, her flags colour,
she presented a more majestic spectacle than Stockholmers had ever seen
before. All gun-ports were open and the muzzles peeped wickedly from
them.
As the wind freshened there came a sudden squall and the ship made a
strange movement, listing to port. The Ordnance Officer ordered all the
port cannon to be heaved to starboard to counteract the list, but the
steepening angle of the decks increased. Then the sound of rumbling
thunder reached the watchers on the shore, as cargo, ballast, ammunition
and 400 people went sliding and crashing down to the port side of the
steeply listing ship. The lower gun-ports were now below water and the
inrush sealed the ship's fate. In that first glorious hour, the mighty
Vasa, which was intended to rule the Baltic, sank with all flags
flying-in the harbour of her birth.
ROY SAUNGERS The Raising of the 'Vasa' from The Listener
galleon n. 
Stockholm n. 
flagship n. 
imperial adj. 
hurricane n. 
armament n. 
triple adj. 
mount v. 
bronze n. 
cannon n. 
162871956
.34
16288103
400
** Lesson 28 Patients and doctors
What are patients looking for when they visit the doctor?
This is a sceptical age, but although our faith in many of the things in
which our forefathers fervently believed has weakened, our confidence in
the curative properties of the bottle of medicine remains the same a
theirs. This modern faith in medicines is proved the fact that the
annual drug bill of the Health Services is mounting to astronomical
figures and shows no signs at present of ceasing to rise. The majority
of the patients attending the medical out-patients departments of our
hospitals feel that they have not received adequate treatment unless
they are able to carry home with them some tangible remedy in the shape
of a bottle of medicine, a box of pills, or a small jar of ointment, and
the doctor in charge of the department is only too ready to provide them
with these requirements. There is no quicker method of disposing of
patients then by giving them what they are asking for, and since most
medical men in the Health Services are overworked and have little time
for offering time-consuming and little-appreciated advice on such
subjects as diet, right living, and the need for abandoning bad habits
etc., the bottle, the box, and the jar are almost always granted them.
Nor is it only the ignorant and ill-educated person who was such faith
in the bottle of medicine. It is recounted of Thomas Carlyle that when
him in his pocket what remained of a bottle of medicine formerly
prescribed for an indisposition of Mrs. Carlyle's. Carlyle was entirely
ignorant of what the bottle in his pocket contained, of the nature of
the illness from which his friend was suffering, and of what had
previously been wrong with his wife, but a medicine that had worked so
well in one form of illness would surely be of equal benefit in another,
and comforted by the thought of the help he was bringing to his friend,
he hastened to Henry Taylor's house. History does not relate whether his
friend accepted his medical help, but in all probability he did. The
great advantage of taking medicine is that it makes no demands on the
taker beyond that of putting up for a moment with a disgusting taste,
and that is what all patients demand of their doctors -- to be cured at
no inconvenience to themselves.
sceptical adj. 
forefathers n. 
fervently adv. 
curative adj. 
astronomical adj. 
tangible adj.
remedy n. 
ointment n. 
prescribe v. 
indisposition n. 
inconvenience n. 
inconvenience n. 
...
-- 
** Lesson 29 The hovercraft
What is a hovercraft riding on when it is in motion?
Many strange new means of transport have been developed in our century,
the strangest of them being perhaps the hovercraft. In 1953, a former
electronics engineer in his fifties, Christopher Cockerell, who had
turned to boat-building on the Norfolk Broads, suggested an idea on
which he had been working for many years to the British Government and
industrial circles. It was the idea of supporting a craft on a 'pad', or
cushion, of low-pressure air, ringed with a curtain of higher pressure
air. Ever since, people have had difficulty in deciding whether the
craft should be ranged among ships, planes, or land vehicles -- for it
is something in between a boat and an aircraft. As a shipbuilder,
Cockerell was trying to find a solution to the problem of the wave
resistance which wastes a good deal of a surface ship's power and limits
its speed. His answer was to lift the vessel out of the water by a great
number of ring-shaped air jets on the bottom of the craft. It 'flies',
therefore, but it cannot fly higher -- its action depends on the
surface, water or ground, over which it rides.
The first tests on the Solent in 1959 caused a sensation. The hovercraft
travelled first over the water, then mounted the beach, climbed up the
dunes, and sat down on a road. Later it crossed the Channel, riding
smoothly over the waves, which presented no problem.
Since that time, various types of hovercraft have appeared and taken up
regular service. The hovercraft is particularly useful in large areas
with poor communications such as Africa or Australia; it can become a
'flying fruit-bowl', carrying bananas from the plantations to the ports;
giant hovercraft liners could span the Atlantic; and the railway of the
future may well be the 'hovertrain', riding on its air cushion over a
single rail, which it never touches, at speeds up to 300 m.p.h. -- the
possibilities appear unlimited.
EGON LARSEN The Pegasus Book of Inventors
hovercraft n. 
Norfolk Broads n. 
cushion n. 
ring v. 
Solent n. 
sensation n. 
dune n. 
plantation n. 
hovertrain n. 
195350.
1959
300
** Lesson 30 Exploring the sea-floor
How did people probably imagine the sea-floor before it was
investigated?
Our knowledge of the oceans a hundred years ago was confined to the
two-dimensional shape of the sea surface and the hazards of navigation
presented by the irregularities in depth of the shallow water close to
the land. The open sea was deep and mysterious, and anyone who gave more
than a passing thought to the bottom confines of the oceans probably
assumed that the sea bad was flat. Sir James Clark Ross had obtained a
sounding of over 2,400 fathoms in 1839, but it was not until of deep
soundings was obtained in the Atlantic and the first samples were
collected by dredging the bottom. Shortly after this the famous H. M. S.
Challenger expedition established the study of the sea-floor as a
subject worthy of the most qualified physicists and geologists. A burst
of activity associated with the laying of submarine cables soon
confirmed the challenger's observation that many parts of the ocean were
two to there miles deep, and the existence of underwater features of
considerable magnitude.
Today, enough soundings are available to enable a relief map of the
Atlantic to be drawn and we know something of the great variety of the
sea bed's topography. Since the sea covers the greater part of the
earth's surface, it is quite reasonable to regard the sea floor as the
basic form of the crust of the earth, with, superimposed upon, it the
continents, together with the islands and other features of the oceans.
The continents form rugged tablelands which stand nearly three miles
above the floor of the open ocean. From the shore line, out a distance
which may be anywhere from a few miles to a few hundred miles, runs the
gentle slope of the continental shelf, geologically part of the
continents. The real dividing line between continents and oceans occurs
at the foot a steeper slope.
This continental slope usually starts at a place somewhere near the
100-fatheom mark and in the course of a few hundred miles reaches the
true ocean floor at 2,500-3,500 fathoms. The slope averages about 1 in
30. but contains steep, probably vertical, cliffs, and gentle
sediment-covered terraces, and near its lower reaches there is a long
tailing-off which is almost certainly the result of material transported
out to deep water after being eroded from the continental masses.
T.F.GASKELL Exploring the Sea-floor from Science Survey
navigation n. 
sounding n. 
fathom n. 11.8
porcupine n. 
dredge v. 
expedition n. 
physicist n. 
magnitude n. 
topography n. 
crust n. 
rugged adj.
tableland n. 
sediment n. 
terrace n. 
erode v. 
1001839..24001869
100250035001/30
** Lesson 31 The sculptor speaks
What do you have to be able to do to appreciate sculpture?
Appreciation of sculpture depends upon the ability to respond to form in
there dimension. That is perhaps why sculpture has been described as the
most difficult of all arts; certainly it is more difficult than the arts
which involve appreciation of flat forms, shape in only two dimensions.
Many more people are 'form-blind' than colour-blind. The child learning
to see, first distinguishes only two-dimensional shape; it cannot judge
distances, depths. Later, for its personal safety and practical needs,
it has to develop (partly by means of touch) the ability to judge
roughly three-dimensonal distances. But having satisfied the
requirements of practical necessity, most people go no further. Though
they may attain considerable accuracy in the perception of flat from,
they do no make the further. Though they may attain considerable
accuracy in the perception of flat form, they do not make the further
intellectual and emotional effort needed to comprehend form in its full
spatial existence.
This is what the sculptor must do. He must strive continually to think
of, and use, form in its full spatial completeness. He gets the solid
shape, as it were, inside his head-he thinks of it, whatever its size,
as if he were holding it completely enclosed in the hollow of his hand.
He mentally visualizes a complex form from all round itself; he knows
while he looks at one side what the other side is like, he identifies
himself with its centre of gravity, its mass, its weight; he realizes
its volume, as the space that the shape displaces in the air.
And the sensitive observer of sculpture must also learn to feel shape
simply as shape, not as description or reminiscence. He must, for
example, perceive an egg as a simple single solid shape, quite apart
from its significance as food, or from the literary idea that it will
become a bird. And so with solids such as a shell, a nut, a plum, a
pear, a tadpole, a mushroom, a mountain peak, a kidney, a carrot, a
tree-trunk, a bird, a bud, a lark, a ladybird, a bulrush, a bone. From
these he can go on to appreciate more complex forms of combinations of
several forms.
HENRY MOORE The Sculptor Speaks from The Listener
colour-blind adj. 
perception n. 
comprehend v. 
spatial adj. 
visualize v. 
reminiscence n. 
tadpole n. 
mushroom n. 
carrot n. 
bud n. 
lark n. 
ladybird n. 
bulrush n. 
** Lesson 34 Adolescence
What do adolescents respect in parents?
Parents are often upset when their children praise the homes of their
friends and regard it as a slur on their own cooking, or cleaning, or
furniture, and often are foolish enough to let the adolescents see that
they are annoyed. They may even accuse them of disloyalty, or make some
spiteful remark about the friends' parents. Such loss of dignity and
descent into childish behaviour on the part to their parents about the
place or people they visit. Before very long the parents will be
complaining that the child is so secretive and never tells them
anything, but they seldom realize that they have brought this on
themselves.
Disillusionment with the parents, however good and adequate they may be
both as parents and as individuals, is to some degree inevitable. Most
children have such a high ideal of their parents, unless the parents
themselves have been unsatisfactory, that it can hardly hope to stand up
to a realistic evaluation. Parents would be greatly surprised and deeply
touched if they hope to stand up to a realistic evaluation. Parents
would be greatly surprised and deeply touched if they realized how much
belief their children usually have in their character and infallibility,
and how much this faith means to a child. If parents were prepared for
this adolescent reaction, and realized that it was a sign that the child
was growing up and developing valuable powers of observation and
independent judgment, they would not be so hurt, and therefore would not
drive the child into opposition by resenting and resisting it.
The adolescent, with his passion for sincerity, always respects a parent
who admits that he is wrong, or ignorant, or even that he has been
unfair or unjust. What the child cannot forgive is the parent's refusal
to admit these charges if the child knows them to be true.
Victorian parents believed that they kept their dignity by retreating
behind an unreasoning authoritarian attitude; in fact they did nothing
of the kind, but children were then too cowed to let them know how they
really felt. Today we tend to go to the other extreme, but on the whole
this is a healthier attitude both for the child and the parent. It is
always wiser and safer to face up to reality, however painful it may be
at the moment.
DOTID OFLUM Journey Through Adolescence
adolescence n.
slur n. 
adolescent n. 
disloyalty n. 12-18
spiteful adj. 
disillusionment n. 
evaluation n. 
infallibility n. 
resent v. 
sincerity n. 
victorian adj. 
retreat v. 
unreasoning adj. 
authoritarian adj. 
cow v. 
,
** Lesson 35 Space odyssey
When will it be possible for us to think seriously about colonising
Mars?
The Moon is likely to become the industrial hub of the Solar System,
supplying the rocket fuels fro its ships, easily obtainable from the
lunar rocks in the from of liquid oxygen. The reason lies in its
gravity. Because the Moon has only an eightieth of the Earth's mass, it
requires 97 per cent less energy to travel the quarter of a million
miles from the Moon to Earth-orbit than the 200 mile-journey from
Earth's surface into orbit!
This may sound fantastic, but it is easily calculated. To escape from
the Earth in a rocket, one must travel at seven miles per second. The
comparable speed from the Moon is only 1.5 miles per second. Because the
gravity on the Moon's surface is only a sixth of Earth's (remember how
easily the Apollo astronauts bounded along), it takes much less energy
to accelerate to that 1.5 miles per second than it does on Earth.
Moon-dwellers will be able to fly in space at only three per cent of the
cost of similar journeys by their terrestrial dwellers will be able to
fly in space at only three per cent of the cost of similar journeys by
their terrestrial cousins.
Arthur C. Clark once suggested a revolutionary idea passes through three
phases:
1 'It's impossible -- don't waste my time.'
2 'It's possible, but not worth doing.'
3 'I said it was a good idea all along.'
The idea of colonising Mars -- a world 160 times more distant time the
Moon -- will move decisively from the second phase to the third, when a
significant number of people are living permanently in space. Mars has
an extraordinary fascination for would-be voyagers. America, Russia and
Europe are filled with enthusiasts -- many of them serious and senior
scientists -- who dream of sending people to it. Their aim is
understandable. It is the one world in the Solar System that is most
like the Earth. It is a world of red sandy deserts (hence its name --
the Red Planet), cloudless skies, savage sandstorms, chasms wider than
the Grand Canyon and at least one mountain more than twice as tall as
Everest. It seems ideal for settlement.
7 DAYS, February 19, 1989
hub n. 
lunar adj. 
oxygen n. 
Apollo n. 
accelerate v. 
terrestrial adj. 
permanently adv. 
fascination n. 
senior adj. 
chasm n. 
canyon n. 
1/82520097%
71.51/6
--  --
1.53%
.C.3
1 
2 
3 
--
160 --
23
--
** Lesson 36 The cost of government
What is the most important factor, both in government or business, for
keeping running costs low?
If a nation is essentially disunited, it is left to the government to
hold it together. This increases the expense of government, and reduces
correspondingly the amount of economic resources that could be used for
developing the country. And it should not be forgotten how small those
resources are in a poor and backward country. Where the cost of
government is high, resources for development are correspondingly low.
This may be illustrated by comparing the position of a nation with that
of a private business enterprise. An enterprise has to incur certain
costs and expenses in order to stay in business. For our purposes, we
are concerned only with one kind of cost -- the cost of managing and
administering the business. Such administrative overheads in a business
are analogous to the cost of government in a nation. The administrative
overheads of a business are low to the extent that everyone working in
the business can be trusted to behave in a way that best promotes the
interests of the firm. If they can each be trusted to take such
responsibilities. and to exercise such initiative as falls within their
sphere, then administrative overheads will be low. It will be low
because it will be necessary to have only one man looking after each
job, then the business will require armies of administrators, checkers,
and foremen and administrative overheads will rise correspondingly. As
administrative overheads rise, so the earnings of the business after
meeting he expense of administration, will fall; and the business will
have less money to distribute as dividends or invest directly in its
future progress and development.
It is precisely the same with a nation. To the extent that the people
can be relied upon to behave in a loyal and responsible manner, the
government does not require armies of police and civil servants to keep
them in order. But if a nation is disunited, the government cannot be
sure that the actions of the people will be in the interests of the
nation; and it will have to watch, check, and control the people
accordingly. A disunited nation therefore has to incur unduly high costs
of government.
RAYMOND FROST The Backward Society
disunited adj. 
correspondingly adv. 
backward adj. 
incur v. 
administer v. 
adminstrative adj. 
analogous adj. 
overheads n. 
initiative n. 
checker n. 
foreman n. 
dividend n. 
unduly adv. 
--
* Unit 4
** Lesson 37 The process of ageing
What is one of the most unpleasant discoveries we make about ourselves
as we get older?
At the age of twelve years, the human body is at its most vigorous. It
has yet to reach its full size and strength, and its owner his or her
full intelligence; but at this age the likelihood of death is least.
Earlier, we were infants and young children, and consequently more
vulnerable; later, we shall undergo a progressive loss of our vigour and
resistance which, though imperceptible at first, will finally become so
steep that we can live no longer, however well we look after ourselves,
and however well society, and our doctors, look after us. This decline
in vigour with the passing of time is called ageing. It is one of the
most unpleasant discoveries which we all make that we must decline in
this way, that if we escape wars, accidents and disease we shall
eventually 'die of old age', and that this happens at a rate which
differs little from person to person, so that there are heavy odds in
favour of our dying between the ages of sixty-five and eighty. Some of
us will die sooner, a few will live longer -- on into a ninth or tenth
decade. But the chances are against it, and there is a virtual limit on
how long we can hope to remain alive, however lucky and robust we are.
Normal people tend to forget this process unless and until they are
reminded of it. We are so familiar with the fact that man ages, that
people have for years assumed that the process of losing vigour with
time, of becoming more likely to die the older we get, was something
self-evident, like the cooling of a hot kettle or the wearing-out of a
pair of shoes. They have also assumed that all animals, and probably
other organisms such as trees, or even the universe itself, must in the
nature of things 'wear out'. Most animals we commonly observe do in fact
age as we do, if given the chance to live long enough; and mechanical
systems like a wound watch, or the sun, do in fact run out of energy in
accordance with the second law of thermodynamics (whether the whole
universe does so is a moot point at present). But these are not
analogous to what happens when man ages. A run-down watch is still a
watch and can be rewound. An old watch, by contrast, becomes so worn and
unreliable that it eventually is not worth mending. But a watch could
never repair itself -- it does not consist of living parts, only of
metal, which wears away by friction. We could, at one time, repair
ourselves --well enough, at least, to overcome all but the most
instantly fatal illnesses and accidents. Between twelve and eighty years
we gradually lose this power; an illness which at twelve would knock us
over, at eighty can knock us out, and another 700 for the survivors to
be reduced by half again.
ALEX COMFORT The process of ageing
likelihood n. 
infant n. 
vulnerable adj. 
imperceptible adj. 
steep adj. 
ageing n. 
odds n. 
virtual adj. 
robust adj. 
organism n. 
thermodynamics n. 
moot adj. 
run-down adj. 
friction n. 
126580
--
1280128012700700
** Lesson 38 Water and the traveller
What does this text describe?
Contamination of water supplies is usually due to poor sanitation close
to water sources, sewage disposal into the sources themselves, leakage
of sewage into distribution systems or contamination with industrial or
farm waste. Even if a piped water supply is safe at its source, it is
not always safe by the time it reaches the tap. Intermittent tap-water
supplies should be regarded as particularly suspect.
Travellers on short trips to areas with water supplies of uncertain
quality should avoid drinking tap-water, or untreated water from any
other source. It is best to hot drinks, bottled or canned drinks of
well-known brand names -- international standards of water treatment are
usually followed at bottling plants. Carbonated drinks are acidic, and
slightly safer. Make sure that all bottles are opened in your presence,
and that their rims are clean and dry.
Boiling is always a good way of treating water. Some hotels supply
boiled water on request and this can be used for drinking, or for
brushing teeth. Portable boiling elements that can boil small quantities
of water are useful when the right voltage of electricity is available.
Refuse politely any cold drink from an unknown source.
Ice is only as safe as the water from which it is made, and should not
be put in drinks unless it is known to be safe. Drink can be cooled by
placing them on ice tather than adding ice to them.
Alcohol may be a medical disinfectant, but should not be relied upon to
sterilize water. Ethanol is more effective at a concentration of 50-70
per cent; below 20 per cent, its bactericidal action is negligible.
Spirits labelled 95 proof contain only about 47 per cent alcohol. Beware
of methylated alcohol, which is very poisonous, and should never be
added to drinking water.
If no other safe supply can be obtained, tap water that is too hot to
touch can be left to cool and is generally safe to drink. Those planning
a trip to remote areas, or intending to live in countries where drinking
water is not readily available, should know about the various possible
methods for making water safe.
RICHARD DAWOOD Travellers' Health
contamination n. 
sanitation n. 
sewage n. 
leakage n. 
intermittent adj. 
carbonated adj. 
acidic adj. 
alcohol n. 
disinfectant n. 
sterilize v. 
ethanol n. 
bactericidal adj. 
negligible adj. 
methylated adj. 
--
50%70%20%9547%
** Lesson 39 What every writer wants
How do professional writers ignore what they were taught at school about
writing?
I have known very few writers, but those I have known, and whom I
respect, confess at once that they have little idea where they the are
going when they first set pen to paper. They have a character, perhaps
two; they are in that condition of eager discomfort which passes for
inspiration; all admit radical changes of destination once the journey
has begun; one, to my certain knowledge, spent nine months on a novel
about Kashmir, then reset the whole thing in the Scottish Highlands. I
never heard of anyone making a 'skeleton', as we were taught at school.
In the breaking and remaking, in the timing, interweaving, beginning
afresh, the writer comes to discern things in his material which were
not consciously in his mind when he began. This organic process, often
leading to moments of extraordinary self-discovery, is of an
indescribable fascination. A blurred image appears; he adds a
brushstroke and another, and it is gone; but something was there, and he
will not rest till he has captured it. Sometimes the yeast within a
writer outlives a book he has written. I have heard of writers who read
nothing but their own books; like adolescents they stand before the
mirror, and still cannot fathom the exact outline of the vision before
them. For the same reason, writers talk interminably about their own
books, winkling out hidden meanings, super-imposing new ones, begging
response from those around them. Of course a writer doing this is
misunderstood: he might as well try to explain a crime or a love affair.
He is also, incidentally, an unforgivable bore.
This temptation to cover the distance between himself and the reader, to
study his image in the sight of those who do not know him, can be his
undoing: he has begun to write to please.
A young English writer made the pertinent observation a year or two back
that the talent goes into the first draft, and the art into the drafts
that follow. For this reason also the writer, like any other artist, has
no resting place, no crowd or movement in which he may take comfort, no
judgment from outside which can replace the judgment from within. A
writer makes order out of the anarchy of his heart; he submits himself
to a more ruthless discipline than any critic dreamed of, and when he
flirts with fame, he is taking time off from living with himself, from
the search for what his world contains at its inmost point.
JOHN LE CARRE What every writer wants from Harper's
confess v. 
inspiration n. 
Kashmir n. 
interweave v. 
afresh adv. 
discern v. 
indescribable adj. 
blur v. ...
yeast n. 
fathom v. 
interminably adv. 
winkle v. 
incidentally adv. 
pertinent adj. 
flirt v. 
inmost adj. 
9
** Lesson 40 Waves
What false impression does an ocean were convey to the observer?
Waves are the children of the struggle between ocean and atmosphere, the
ongoing signatures of infinity. Rays from the sun excite and energize
the atmosphere of the earth, awakening it to flow, to movement, to
rhythm, to life. The wind then speaks the message of the sun to the sea
and the sea transmits it on through waves -- an ancient, exquisite,
powerful message.
These ocean waves are among the earth's most complicated natural
phenomena. The basic features include a crest (the highest point of the
wave), a trough (the lowest point), a height (the vertical distance from
the trough to the crest), a wave length (the horizontal distance between
two wave crests), and a period (which is the time it takes a wave crest
to travel one wave length).
Although an ocean wave gives the impression of a wall of water moving in
your direction, in actuality waves move through the water leaving the
water about where it was. If the water was moving with the wave, the
ocean and everything on it would be racing in to the shore with
obviously catastrophic results.
An ocean wave passing through deep water causes a particle on the
surface to move in a roughly circular orbit, drawing the particle first
towards the advancing wave, then up into the wave, then forward with it
and then -- as the wave leaves the particles behind -- back to its
starting point again.
From both maturity to death, a wave is subject to the same laws as any
other 'living' thing. For a time it assumes a miraculous individuality
that, in the end, is reabsorbed into the great ocean of life.
The undulating waves of the open sea are generated by three natural
causes: wind, earth movements or tremors, and the gravitational pull of
the moon and the sun. Once waves have been generated, gravity is the
force that drives them in a continual attempt to restore the ocean
surface to a flat plain.
from World Magazine (BBC Enterprises)
signature n. 
infinity n. 
ray n. 
energize v. ...
rhythm n. 
transmit v. 
exquisite adj. 
phenomena n. 
crest n. 
trough n. 
vertical adj. 
horizontal adj. 
actuality n. 
catastrophic adj. 
particle n. 
maturity n. 
undulate v. 
tremor n. 
gravitational adj. 
-- 
--  -- 
3
** Lesson 41 Training elephants
At what point does the training of a captive wild elephant begin?
Two main techniques have been used for training elephants, which we may
respectively the tough and the gentle. The former method simply consists
of setting an elephant to work and beating him until he does what is
expected of him. Apart from moral considerations this is a stupid method
of training, for it produces a resentful animal who at a later stage may
well turn man-killer. The gentle method requires more patience in the
early stages, but produces a cheerful, good-tempered elephant who will
give many years of loyal service.
The first essential in elephant training is to assign to the animal a
single mahout who will be entirely responsible for the job. Elephants
like to have one master just as dogs do, and are capable of a
considerable degree of personal affection. There are even stories of
half-trained elephant calves who have refused to feed and pined to death
when by some unavoidable circumstance they have been deprived of their
own trainer. Such extreme cases must probably be taken with a grain of
salt, but they do underline the general principle that the relationship
between elephant and mahout is the key to successful training.
The most economical age to capture an elephant for training is between
fifteen and twenty years, for it is then almost ready to undertake heavy
work and can begin to earn its keep straight away. But animals of this
age do not easily become subservient to man, and a very time man, and a
very firm hand must be employed in the early stages. The captive
elephant, still roped to a tree, plunges and screams every time a man
approaches, and for several days will probably refuse all food through
anger and fear. Sometimes a tame elephant is tethered nearby to give the
wild one confidence, and in most cases the captive gradually quietens
down and begins to accept its food. The next stage is to get the
elephant to the training establishment, a ticklish business which is
achieved with the aid of two tame elephants roped to the captive on
either side.
When several elephants are being trained at one time, it is customary
for the new arrival to be placed between the stalls of two captives
whose training is already well advanced. It is then left completely
undisturbed with plenty of food and water so that it can absorb the
atmosphere of its new home and see that nothing particularly alarming is
happening to its companions. When it is eating normally, its own
training begins. The trainer stands in front of the elephant holding a
long stick with a sharp metal point. Two assistants, mounted on tame
elephants, control the captive from either side, while others rub their
hands over his skin to the accompaniment of a monotonous and soothing
chant. This is supposed to induce pleasurable sensations in the
elephant, and its effects are reinforced by the use of endearing
epithets. The elephant is not son', or 'ho! my father', or 'my mother',
according to the age and sex of the captive. The elephant is not
immediately susceptible to such blandishments, however, and usually
lashes fiercely with its trunk in all directions. These movements are
controlled by the trainer with the metal-pointed stick, and the trunk
eventually becomes so sore that the elephant curls it up and seldom
afterwards uses it for offensive purposes.
RICHARD CARRINGTON Elephants
technique n. 
tough adj. 
resentful adj. 
assign v. 
mahout n. 
calf n. 
pine v. 
underline v. 
keep n. 
subservient adj. 
plunge v. 
tame adj. 
tether v. 
ticklish adj. 
alarming adj. 
accompaniment n. 
soothe v. 
chant n. 
reinforce v. 
endearing adj.
epithet n. 
susceptible adj. 
blandishment n. 
lash v. 
curl v. 
1520
** Lesson 42 Recording an earthquake
What does a pen have to do to record on paper the vibrations generated
by an earthquake?
An earthquake comes like a thief in the night, without warning. It was
necessary, therefore, to invent instruments that neither slumbered nor
slept. Some devices were quite simple. One, for instance, consisted of
rods of various lengths and thicknesses with would stand up end like
ninepins. When a shock came, it shook the rigid table upon which these
stood. If it were gentle, only the more unstable rods fell. If it were
severe, they all fell. Thus the rods, by falling, and by the direction
in which they fell, recorded for the severe, they all fell. Thus the
rods, by falling, and by the direction in which they fell, recorded for
the slumbering scientist the strength of a shock that was too weak to
waken him, and the direction from which it came.
But instruments far more deliecate than that were needed if any really
serious advance was to be made. The ideal to be aimed at was to devise
an instrument that could record with a pen on paper, the movements of
the ground or of the table as the quake passed by. While I write my pen
moves, but the paper keeps still. With practice, no doubt, I could in
time learn to write by holding the pen still while the paper moved. That
sounds a silly suggestion, but that was precisely the idea adopted in
some of the early instruments (seismometers) for recording earthquake
waves. But when table, penholder and paper are all moving, how is it
possible to write legibly? The key to a solution of that problem lay in
an everyday observation. Why does a person standing in a bus or train
tend to fall when a sudden start is made? It is because his feet move on
, but his head stays still. A simple experiment will help us a little
further. Tie a heavy weight at the end of a long piece of string. With
the hand to and fro and around but not up and string so that the weight
nearly touches the ground. Now move the hand to and fro and around but
not up and down. It will be found that the weight a piece of string.
With the hand held high in the air, hold the string so that the weight
nearly touches the ground. Now move the hand to and fro and around but
not up and down. It will be found that ten weight moves but slightly or
not at all. Imagine an earthquake shock shaking the floor, the paper,
you and your hand. In the midst of all this movement, the weight and the
pen would be still. But as the paper moved from side to side under the
pen point, its movement would be recorded in ink upon its surface. It
was upon this principle that the first instruments were made, but while
the drum was being shaken, the line that the pen was drawing wriggled
from side to side. The apparatus thus described, however, records only
the horizontal component of the wave movement, which is, in fact, much
more complicated. If we could actually see the path described by a
particle, such as a sand grain in the rock, it would be more like that
of a bluebottle path described by a particle, such as a sand grain in
the rock, it would be more like that of a bluebottle buzzing round the
room; it would be up and down, to and fro and from side to side.
Instruments have been devised and can be so placed that all three
elements can be recorded in different graphs.
When the instrument is situated at more than 700 miles from the
earthquake centre, the graphic record shows three waves arriving one
after at short intervals. The first records the arrival of longitudinal
vibrations. The second marks the arrival of transverse vibrations which
travel more slowly and arrive several minutes after the first. These two
have travelled through the earth. It was from the study of these that so
much was learnt about the interior of the earth. The third, or main. The
third, or main wave, is the slowest and has travelled round the earth
through the surface rocks.
H.H,SWINNERTON The Earth beneath Us
earthquake n. 
slumber v. 
ninepin n. 
rigid adj. 
delicate adj. 
seismometer n. 
penholder n. 
legibly adv. 
drum n. 
wriggle v. 
bluebottle n. 
graph n. 
graphic adj. 
longitudinal adj. 
transverse adj. 
3
7003
** Lesson 43 Are there strangers in space?
What does the 'uniquely rational way' for us to communicate with other
intelligent beings in space depend on?
We must conclude from the work of those who have studied the origin of
life, that given a planet only approximately like our own, life is
almost certain to start. Of all the planets in our solar system, we ware
now pretty certain the Earth is the only one on which life can survive.
Mars is too dry and poor in oxygen, Venus far too hot, and so is
Mercury, and the outer planets have temperatures near absolute zero and
hydrogen-dominated atmospheres. But other suns, start as the astronomers
call them, are bound to have planets like our own, and as is the number
of stars in the universe is so vast, this possibility becomes virtual
certainty. There are one hundred thousand million starts in our own
Milky Way alone, and then there are exist is now estimated at about 300
million million.
Although perhaps only 1 per cent of the life that has started somewhere
will develop into highly complex and intelligent patterns, so vast is
the number of planets, that intelligent life is bound to be a natural
part of the universe.
If then we are so certain that other intelligent life exists in the
universe, why have we had no visitors from outer space yet? First of
all, they may have come to this planet of ours thousands or millions of
years ago, and found our then prevailing primitive state completely
uninteresting to their own advanced knowledge. Professor Ronald
Bracewell, a leading American radio astronomer, argued in Nature that
such a superior civilization, on a visit to our own solar system, may
have left an automatic messenger behind to await the possible awakening
of an advanced civilization. Such a messenger, receiving our radio and
television signals, might well re-transmit them back to its home-planet,
although what impression any other civilization would thus get from us
is best left unsaid.
But here we come up against the most difficult of all obstacles to
contact with people on other planets -- the astronomical distances which
separate us. As a reasonable guess, they might, on an average, be 100
light years away. (A light year is the distance which light travels at
186,000 miles per second in one year, namely 6 million million miles.)
Radio waves also travel at the speed of light, and assuming such an
automatic messenger picked up our first broadcasts of the 1920's, the
message to its home planet is barely halfway there. Similarly, our own
present primitive chemical rockets, though good enough to orbit men,
have no chance of transporting us to the nearest other star, four light
years away, let alone distances of tens or hundreds of light years.
Fortunately, there is a 'uniquely rational way' for us to communicate
with other intelligent beings, as Walter Sullivan has put it in his
excellent book, We Are not Alone. This depends on the precise radio
frequency of the 21-cm wavelength, or 1420 megacycles per second. It is
the natural frequency of emission of the hydrogen atoms in space and was
discovered by us in 1951; it must be known to any kind of radio
astronomer in the universe.
Once the existence of this wave-length had been discovered, it was not
long before its use as the uniquely recognizable broadcasting frequency
for interstellar communication was suggested. Without something of this
kind, searching for intelligences on other planets would be like trying
to meet a friend in London without a pre-arranged rendezvous and
absurdly wandering the streets in the hope of a chance encounter.
ANTHONY MICHAELIS Are There Strangers in Space? from The Weekend
Telegraph
Mercury n. 
hydrogen n. 
prevailing adj. 
radio astronomer
uniquely adv. 
rational adj. 
radio frequency 
cm n. 
megacycle n. 
emission n. 
intersteller adj.
rendezvous n. 
10003030X1000
1%
.
100118600064
.2114201951
** Lesson 44 Patterns of culture
What influences us from the moment of birth?
Custom has not commonly been regarded as a subject of great moment. The
inner workings of our won brains we feel to be uniquely worthy of
investigation, but custom, we have a way of thinking, is behaviour at
its most commonplace. As a matter of fact, it is the other way around.
Traditional custom, taken the world over, is a mass of detailed
behaviour more astonishing than what any one person can ever evolve in
individual actions, no matter how aberrant. Yet that is a rather trivial
aspect of the matter. The fact of first-rate importance is the
predominant role that custom plays in experience and in belief, and the
very great varieties it may manifest.
No man ever looks at the world with pristine eyes. He sees it edited by
a definite set of customs and institutions and ways of thinking. Even in
his philosophical probing he cannot go behind these stereotypes; his
very concepts of the true and the false will still have reference to his
particular traditional customs. John Dewey has said in all seriousness
that the part played by custom in shaping the behaviour of the
individual, as against any way in which he can affect traditional
custom, is as the proportion of the total vocabulary of his mother
tongue against those words of his own baby talk that are taken up into
the vernacular of his family. When one seriously studies the social
orders that have had the opportunity to develop autonomously, the figure
becomes no more than an exact and matter-of-fact observation. The life
history handed down in his community. From the moment of his birth, the
customs into which he is born shape his experience and behaviour. By the
time he can talk, he is the little creature of his culture, and by the
time he is grown and able to take part in its activities, its habits are
his habits, its beliefs his beliefs, its impossibilities his
impossibilities. Every child that is born into his group will share them
with him, and no child born into one on the opposite side of the globe
can ever achieve the thousandth part. There is no social problem it is
more incumbent upon us to understand than this of the role of custom.
Until we are intelligent as to its laws and varieties, the main
complicating facts of human life must remain unintelligible.
The study of custom can be profitable only after certain preliminary
propositions have been accepted, and some of these propositions have
been violently opposed. In the first place, any scientific study
requires that there be no preferential weighting of one or another of
the items in the series it selects for its consideration. In all the
less controversial fields, like the study of cacti or termites or the
mature of nebulae, the necessary method of study is to group the
relevant material and to take note of all possible variant forms and
conditions. In this way, we have learned all that we know of the laws of
astronomy, or of the habits of the social insects, let us say. It is
only in the relevant material and to take note of all possible variant
forms and conditions. In this way, we have learned all that we know of
the laws of astronomy, or of the habits of the social insects, let us
say. It is only in the study of man himself that the major social
sciences have substituted the study of one local variation, that of
Western civilization.
Anthropology was by definition impossible, as long as these distinctions
between ourselves and the primitive, ourselves and the barbarian,
ourselves and the pagan, held sway over people's minds. It was necessary
first to arrive at that degree of sophistication where we no longer set
our own belief against our neighbour's superstition. It was necessary to
recognize that these institutions which are based on the same premises,
let us say the supernatural, must be considered together, our own among
the rest.
RUTH BENEDICT Patterns of Culture
commonplace adj. 
aberrant adj. 
trivial adj. 
predominant adj. 
manifest v. 
pristine adj. 
stereotype n. 
vernacular n. 
accommodation n. 
incumbent adj. 
preliminary adj. 
proposition n. 
preferrential adj. 
controversial adj. 
cactus n. 
termite n. 
nebula adj. 
variant n. 
barbarian n. 
pagan n. 
sophistication n. 
premise n. 
supernatural adj. 
.
** Lesson 45 Of men and galaxies
What is the most influential factor in any human society?
In man's early days. competition with other creatures must have been
critical. But this phase of our development is now finished. Indeed, we
lack practice and experience nowadays in dealing with primitive
conditions. I am sure that, without modern weapons, I would make a very
poor show of disputing the ownership of a cave with a bear, and in this
I do not think that I stand alone. The last creature to compete with man
was the mosquito. But even the mosquito has been subdued by attention to
drainage and by chemical sprays.
Competition between our selves, person against person, community against
community, still persists, however; and it is as fierce as it ever was.
But the competition of man against man is not the simple process
envisioned in biology. It is not a simple competition for a fixed amount
of food determined by the physical environment, because the environment
that determines our evolution is no longer essentially physical. Our
environment is chiefly conditoned by the things we believe. Morocco and
California are bits of the Earth in very similar latitudes, both on the
west coasts of continents with similar climates, and probably with
rather similar natural resources. Yet their present development is
wholly different, not so much because of different people wish to
emphasize. The most important factor in our environment is the state of
our own minds.
It is well known that where the white man has invaded a primitive
culture, the most destructive effects have come not from physical
weapons but from ideas. Ideas are dangerous. The Holy Office knew this
full well when it caused heretics to be burned in days gone by. Indeed,
the concept of free speech only exists in our modern society because
when you are inside a community, you are conditioned by the conventions
of the community to such a degree that it is very difficult to conceive
of anything really destructive. It is only someone looking on from
outside that can inject the dangerous thoughts. I do not doubt that it
would be possible to inject ideas into the modern world that would
utterly destroy us. I would like to give you an example, but fortunately
I cannot do so. Perhaps it will suffice to mention the unclear bomb. Of
making the effect on a reasonably advanced technological society, one
that still does not possess the bomb, of making it aware of the
possibility, of supplying sufficient details to enable the thing to be
constructed. Twenty or thirty pages of information handed to any of the
major world powers around the year 1925 would have been sufficient to
change the course of world history. It is a strange thought, but I
believe a correct one, that twenty or thirty pages of ideas and
information would be capable of turning the present-day world upside
down, or even destroying it. I have often tried to conceive of what
those pages might contain, but of course outside the particular patterns
that our brains are conditioned to, or, to be more accurate, we can
think only a very little way outside, and then only if we are very
original.
FRED HOYLE Of Men and Galaxies
dispute v. 
mosquito n. 
subdue v. 
drainage n. 
envision n. 
Morocco n. 
latitude n. 
heretic n. 
conceive v. 
suffice v. 
nuclear adj. 
original adj.
1952
** Lesson 46 Hobbies
Who, according to the author, are 'Fortune's favoured children'?
a gifted American psychologist has said, 'Worry is a spasm of the
emotion; the mind catches hold of something and will not let it go.' It
is useless to argue with the mind in this condition. The stronger the
will, the more futile the task. One can only gently insinuate something
else into its convulsive grasp. And if this something else is rightly
chosen, if it really attended by the illumination of another field of
interest, gradually, and often quite swiftly, the old undue grip relaxes
and the process of recuperation and repair begins.
The cultivation of a hobby and new forms of interest is therefore a
policy of the first importance to a public man. But this is not a
business that can be undertaken in a day or swiftly improvised by a mere
command of the will. The growth of alternative mental interests is a
long process. The seeds must by carefully chosen; they must fall on good
ground; they must be sedulously tended, if the vivifying fruits are to
be at hand when needed.
To be really happy and really safe, one ought to have at least two or
three hobbies, and they must all be real. It is no use starting late in
life to say: 'I will take an interest in this or that.' Such an attempt
only aggravates the strain of mental effort. A man may acquire great
knowledge of topics unconnected with his daily work, and yet get hardly
any benefit or relief. It is no use doing what you like; you have got to
like what you do. Broadly speaking, human beings may be divided into
three classes: those who are toiled to death, those who are worried to
hard week's sweat and effort, the chance of playing a game of football
or baseball or Saturday afternoon. It is no use inviting the politician
or the professional or business man, who has beer working or worrying
about serious things for six days, to work or worry about trifling
things at the weekend.
As for the unfortunate people who can command everything they want, who
can gratify every caprice and lay their hands on almost every object of
desire -- for them a new pleasure, a new excitement if only an
additional satiation. In vain they rush frantically round from place to
place, trying to escape from avenging boredom by mere clatter and
motion. For them discipline in one form or another is the most hopeful
path.
It may also be said that rational, industrious, useful human being are
divided into two classes: first, one. Of these the former are the
majority. They have their compensations. The long hours in the office or
the factory bring with them as their reward, not only the means of
sustenance, but a keen appetite for pleasure even in its simplest and
most modest forms. But Fortune's of sustenance, but a keen appetite for
pleasure even in its simplest and modest forms. But Fortune's favoured
children belong to the second class. Their life is a natural harmony.
For them the working hours are never long enough. Each day is a holiday,
and ordinary holidays, when they come, are grudged as enforced as
enforced interruptions in an absorbing vocation. Yet to both classes,
the need of an alternative outlook, of a change of atmosphere, of a
diversion of effort, is essential. Indeed, it may well be that those
work is their pleasure are those who and most need the means of
banishing it at intervals from their minds.
WINSTON CHURCHLL Painting as a Pastime
gifted adj. 
psychologist n. 
spasm n. 
futile adj. 
insinuate v. 
convulsive adj. 
illumination n. 
undue adj. 
grip n. 
recuperation n. 
improvise v. 
sedulously adv. 
vivify v. 
aggravate v. 
trifling adj. 
gratify v. 
caprice n. 
satiation n. 
frantically adv. 
avenge v. ...
boredom n. 
clatter n. 
sustenance n. 
appetite n. 
grudge v. 
absorbing adj. 
banish v. 
36
** Lesson 47 The great escape
First listen and then answer the following quesion.
What is one of the features of modern camping where nationality is
concerned?
Economy is one powerful motive for camping, since after the initial
outlay upon equipment, or through hiring it, the total expense can be
far less than the cost of hotels. But, contrary to a popular assumption,
it is far from being the only one, or even the greatest. The man who
manoeuvres carelessly into his twenty pounds' worth of space at one of
Europe's myriad permanent sites may find himself bumping a Bentley. More
likely, Ford Escort will be hub to hub with Renault or Mercedes, but
rarely with bicycles made for two.
That the equipment of modern camping becomes yearly more sophisticated
is an entertaining paradox for the cynic, a brighter promise for the
hopeful traveler who has sworn to get away from it all. It also
provides-and some student sociologist might care to base his thesis upon
the phenomenon -- an escape of another kind. The modern traveller is
often a man who dislikes the Splendide and the Bellavista, not because
he cannot afford, or shuns their material comforts. but because he is
afford of them. Affluent he may be, but he is by no means sure what to
tip the doorman or the chambermaid. Master in his own house, he has
little idea of when to say boo to a maitre d'hotel.
From all such fears camping releases him. Granted, a snobbery of camping
itself, based upon equipment and techniques, already exists; but it is
of a kind that, if he meets it, he can readily understand and deal with.
There is no superior 'they' in the shape of managements and hotel
hierarchies to darken his holiday days.
To such motives, yet another must be added. The contemporary phenomenon
of car worship is to be explained not least by the sense of independence
and freedom that ownership entails. To this pleasure camping gives an
exquisite refinement.
From one's own front door to home or foreign hills or sands and back
again, everything is to hand. Not only are the means of arriving at the
holiday paradise entirely within one's own command and keeping, but the
means of escape from holiday hel (if the beach proves too crowded, the
local weather too inclement) are there, outside -- or, as likely, part
of -- the tent.
Idealists have objected to the package tour, that the traveller abroad
thereby denies himself the opportunity of getting to know the people of
the country visited. Insularity and self-containment, it is argued, go
hand in hand. The opinion does not survive experience of a popular
Continental camping place. Holiday hotels tend to cater for one
nationality of visitors especially, sometimes exclusively. Camping
sites, by contrast, are highly cosmopolitan. Granted, a preponderance of
Germans is a characteristic that seems common to most Mediterranean
sites; but as yet there is no overwhelmingly specialized patronage.
Notices forbidding the open-air drying of clothes, or the use of water
points for car washing, or those inviting 'our camping friends' to a
dance or a boat trip are printed not only in French or Italian or
Spanish, but also in English, German and Dutch. At meal times the odour
of sauerkraut vies with that of garlic. The Frenchman's breakfast coffee
competes with the Englishman's bacon and eggs.
Whether the remarkable growth of organized camping means the eventual
death of the more independent kind is hard to say. Municipalities
naturally want to secure the campers' site fees and other custom. Police
are wary of itinerants who cannot be traced to a recognized camp
boundary or to four walls. But most probably it will all depend upon
campers themselves: how many heath fires they cause; how much litter
they leave; in short, whether or not they wholly alienate landowners and
those who live in the countryside. Only good scouting is likely to
preserve the freedoms so dear to the heart of the eternal Boy Scout.
NIGEL BUXTON The Great Escape from The Weekend Telegraph
assumption n. 
manoeuvre v. 
myriad adj. 
paradox n. 
cynic n. 
sociologist n. 
shun v. 
affluent adj. 
chambermaid n. 
boob. 
maitre d'hotel n. []
snobbery n. 
hierarchy n. 
entail v. 
inclement adj. 
package tour 
insularity n. 
cater v. 
exclusively adv. 
cosmopolitan adj. 
preponderance n. 
overwhelmingly adv. 
patronage n. 
sauerkraut n. 
vie v. 
municipality n. 
itinerant n. 
heath v. 
alienate v. 
eternal adj. 
20.
** Lesson 48 Planning a share portfolio
How does the older investor differ in his approach to investment from
the younger investor?
There is no shortage of tipsters around offering 'get-rich-quick'
opportunities. But if you are a serious private investor, leave the Las
Vegas mentality to those with money to fritter. The serious investor
needs a proper 'portfolio' -- a well-planned selection of investments,
with a definite structure and a clear aim. But exactly how does a
newcomer to the stock market go about achieving that?
Well, if you go to five reputable stock brokers and ask them what you
should do with your money, you're likely to get five different answers,
-- even if you give all the relevant information about your age age,
family, finances and what you want from your investments. Moral? There
is no one 'right' way to structure a portfolio. However, there are
undoubtedly some wrong ways, and you can be sure that none of our five
advisers would have suggested sinking all (or perhaps any) of your money
into Periwigs*.
So what should you do? We'll assume that you have sorted out the basics
-- like mortgages, pensions, insurance and access to sufficient cash
reserves. You should then establish your own individual aims. These are
partly a matter of personal circumstances, partly a matter of
psychology.
For instance, if you are older you have less time to recover from any
major losses, and you may well wish to boost your pension income. So
preserving your capital and generating extra income are your main
priorities. In this case, you'd probably construct a portfolio with some
shares (but not high risk ones), along with gilts, cash deposits, and
perhaps convertibles or the income shares of split capital investment
trusts.
If you are younger, and in a solid financial position, you may decide to
take an aggressive approach -- but only if you're blessed with a
sanguine disposition and won't suffer sleepless nights over share
prices. If portfolio, alongside your more pedestrian in vestments. Once
you have decided on your investment aims, you can then decide where to
put your money. The golden rule here is spread your risk -- if you put
all of your money into Periwigs International, you're setting yourself
up as a hostage to fortune.
*'Periwigs' is the name of a fictitious company.
INVESTOR'S CHRONICLE, March 23 1990
portfolio n. 
tipster n. 
Las Vegas n. 
fritter v. 
reputable n. 
broker n. 
finance n. 
mortgage n. 
pension n. 
priority n. 
gilt n. 
convertible n. 
sanguine adj. 
heady adj. 
alongside prep. ............
pedestrian adj. 
-- ,
555
--
