* New Concept English 3
* Unit 1
** Lesson 1 A Puma at large
Where must the puma have come from?
Pumas are large, cat-like animals which are found in America. When
reports came into London Zoo that a wild puma had been spotted
forty-five miles south of London, they were not taken seriously.
However, as the evidence began to accumulate, experts from the Zoo felt
obliged to investigate, for the descriptions given by people who claimed
to have seen the puma were extraordinarily similar.
The hunt for the puma began in a small village where a woman picking
blackberries saw 'a large cat' only five yards away from her. It
immediately ran away when she saw it, and experts confirmed that a puma
will not attack a human being unless it is cornered. The search proved
difficult, for the puma was often observed at one place in the morning
and at another place twenty miles away in the evening. Wherever it went,
it left behind it a trail of dead deer and small animals like rabbits.
Paw prints were seen in a number of places and puma fur was found
clinging to bushes. Several people complained of "cat-like noises' at
night and a businessman on a fishing trip saw the puma up a tree. The
experts were now fully convinced that the animal was a puma, but where
had it come from? As no pumas had been reported missing from any zoo in
the country, this one must have been in the possession of a private
collector and somehow managed to escape. The hunt went on for several
weeks, but the puma was not caught. It is disturbing to think that a
dangerous wild animal is still at large in the quiet countryside.
puma n. 
spot v. 
evidence n. 
accumulate v. 
oblige v. ......
hunt n. 
blackberry n. 
human being 
corner v. 
trail n. 
print n. 
cling v. 
convince v. ......
somehow adv. 
disturb v. 
45
520
** Lesson 2 Thirteen equals one
Was the vicar pleased that the clock was striking? Why?
Our vicar is always raising money for one cause or another, but he has
never managed to get enough money to have the church clock repaired. The
big clock which used to strike the hours day and night was damaged many
years ago and has been silent ever since.
One night, however, our vicar work up with a start: the clock was
striking the hours! Looking at his watch, he saw that it was one
o'clock, but the bell struck thirteen times before it stopped. Armed
with a torch, the vicar went up into the clock tower to see what was
going on. In the torchlight, he caught sight of a figure whom he
immediately recognized as Bill Wilkins, our local grocer.
'Whatever are you doing up here Bill?' asked the vicar in surprise.
'I'm trying to repair the bell,' answered Bill. 'I've been coming up
here night after night for weeks now. You see, I was hoping to give you
a surprise.'
'You certainly did give me a surprise!' said the vicar. 'You've probably
woken up everyone in the village as well. Still, I'm glad the bell is
working again.'
That's the trouble, vicar,' answered Bill. 'It's working all right, but
I'm afraid that at one o'clock it will strike thirteen times and there's
nothing I can do about it."
We'll get used to that, Bill,' said the vicar. "Thirteen is not as good
as one, but it's better than nothing. Now let's go downstairs and have a
cup of tea.'
equal v. 
vicar n. 
raise v. 
torchlight n. 
113.
113
1311
** Lesson 3 An unknown goddess
How did the archaeologists know that the statue was a goddess?
Some time ago, and interesting discovery was made by archaeologists on
the Aegean island of Kea. An American team explored a temple which
stands in an ancient city on the promontory of Ayia Irini. The city at
one time must have been prosperous, for it enjoyed a high level of
civilization. Houses -- often three storeys high -- were built of stone.
They had large rooms with beautifully decorated walls. The city was
equipped with a drainage system, for a great many clay pipes were found
beneath the narrow streets.
The temple which the archaeologists explored was used as a place of
worship from the fifteenth century B.C. until Roman times. In the most
sacred room of temple, clay fragments of fifteen statues were found.
Each of these represented a goddess and had, at one time, been painted.
The body of one statue was found among remains dating from the fifteenth
century B.C. It's missing head happened to be among remains of the fifth
century B.C. This head must have been found in Classical times and
carefully preserved. It was very old and precious even then. When the
archaeologists reconstructed the fragments, they were amazed to find
that the goddess turned out to be a very modern-looking woman. She stood
three feet high and her hands rested on her hips. She was wearing a
full-length skirt which swept the ground. Despite her great age, she was
very graceful indeed, but, so far, the archaeologists have been unable
to discover her identity.
goddess(tile) n. 
archaeologist n. 
Aegean adj. 
explore v. 
promontory n. 
prosperous adj. 
civilization n. 
storey n. 
drainage n. 
worship n. 
sacred adj. 
fragment n. 
remains n. 
classical adj. 
reconstruct v. 
rest v. 
hip n. 
full-length adj. 
graceful adj. 
identity n. 
.3
15151553
** Lesson 4 The double life of Alfred Bloggs
.
Why did Alf want a white-collar job?
These days, people who do manual work often receive far more money than
people who work in offices. People who work in offices are frequently
referred to as "white-collar workers' for the simple reason that they
usually wear a collar and tie to go to work. Such is human nature, that
a great many people are often willing to sacrifice higher pay for the
privilege of becoming white-collar workers. This can give rise to
curious situations, as it did in the case of Alfred Bloggs who worked as
a dustman for the Ellesmere Corporation.
When he got married, Alf was too embarrassed to say anything to his wife
about his job. He simply told her that he worked for the Corporation.
Every morning, he left home dressed in a smart black suit. He then
changed into overalls and spent the next eight hours as a dustman.
Before returning home at night. He took a shower and changed back into
his suit. Alf did this for over two years and his fellow dustmen kept
his secret Alf's wife has never discovered that she married a dustman
and she never will, for Alf has just found another job. He will soon be
working in an office. He will be earning only half as much as he used
to, but he feels that his rise in status is well worth the loss of
money. From now on, he will wear a suit all day and others will call him
'Mr. Bloggs', not 'Alf'.
manual adj. 
collar n. 
sacrifice v. 
privilege n. 
dustman n. 
corporation n. 
overalls n. 
shower n. 
secret n. 
status n. 
.
8
** Lesson 5 The facts
What was the consequence of the editor's insistence on facts and
statistics?
Editors of newspapers and magazines often go to extremes to provide
their reader with unimportant facts and statistics. Last year a
journalist had been instructed by a well-known magazine to write an
article on the president's palace in a new African republic. When the
article arrived, the editor read the first sentence and then refuse to
publish it. The article began: 'Hundreds of steps lead to the high wall
which surrounds the president's palace'. The editor at once sent the
journalist a fax instructing him find out the exact number of steps and
the height of the wall.
The journalist immediately set out to obtain these important facts, but
the took a long time to send them Meanwhile, the editor was getting
impatient, for the magazine would soon go to press. He sent the
journalist two more faxes, but received no reply. He sent yet another
fax informing the journalist that if he did not reply soon he would be
fired. When the journalist again failed to reply, the editor reluctantly
published the article as it had originally been written. A week later,
the editor at last received a fax from the journalist. Not only had the
poor man been arrested, but he had been sent to prison as well. However,
he had at last been allowed to send a fax in which he informed the
editor that the he had been arrested while counting the 1,084 steps
leading to the fifteen-foot wall which surrounded the president's
palace.
editor n. 
extreme n. 
statistics n. 
journalist n. 
president n. 
palace n. 
publish v. 
fax n. 
impatient adj. 
fire v. 
originally adv. 
151084
** Lesson 6 Smash-and-grab
How did Mr. Taylor try to stop the thieves?
The expensive shops in a famous near Piccadilly were just "opening. At
this time of the morning, the arcade was almost empty. Mr. Taylor, the
owner of a jewellery shop was admiring a new display. Two of his
assistants had been working busily since eight o'clock and had only just
finished. Diamond necklaces and rings had been beautifully arranged on a
background of black velvet. After gazing at the display for several
minutes, Mr. Taylor went back into his shop.
The silence was suddenly broken when a large car, with its headlights on
and its home blaring, roared down the arcade. It came to a stop outside
the jeweller's. One man stayed at the wheel while two others with black
stocking over their faces jumped out and smashed the window of the shop
with iron bars. While this was going on, Mr. Taylor was upstairs. He and
his staff began throwing furniture out of the window. Chairs and tables
went flying into the arcade. One of the thieves was struck by a heavy
statue, but he was too busy helping himself to diamonds to notice any
pain. The raid was all over in three minutes, for the men scrambled back
into the car and it moved off at a fantastic speed. Just as it was
leaving, Mr. Taylor rushed out and ran after it throwing ashtrays and
vases, but it was impossible to stop the thieves. They had got away with
thousands of pounds worth of diamonds.
smash-and-grab n. 
arcade n. 
Piccadilly n. 
jewllery n. 
necklace n. 
ring n. 
background n. 
velvet n. 
headlight n. 
blare v. 
staff n. 
raid n. 
scramble n. 
scramble v. 
fantastic adj. 
ashtray n. 
8
3
** Lesson 7 Mutilated ladies
Why did Jane cook John's wallet?
Has it ever happened to you? Have you ever put your trousers in the
washing machine and then remembered there was a large bank note in your
back pocket? When you rescued your trousers, did note in your back
pocket? When you rescued your trousers, did you find the note was whiter
than white? People who live in Britain needn't despair when they made
mistakes like this (and a lot of people do)! Fortunately for them, the
Bank of England has a team called Mutilated Ladies which deals with
claims from people who fed their money to a machine or to their dog.
Dogs, it seems, love to chew up money!
A recent case concerns Jane Butlin whose fianc, John, runs a successful
furniture business. John had very good day and put his wallet containing
$3,000 into the microwave oven for safekeeping. Then he and Jane went
horse-riding. When they got home, Jane cooked their dinner in the
microwave oven and without realizing it, cooked her fianc's wallet as
well. Imagine their dismay when they found a beautifully-cooked wallet
and notes turned to ash! John went to see his bank manager who sent the
remains of wallet and the money to the special department of the Bank of
England in Newcastle: the Mutilate Ladies! They examined the remain and
John got all his money back. 'So long as there's something to identify,
we will give people their money back,' said a spokeswoman for the Bank.
'Last year, we paid $1.5m on 21,000 claims. Damaged bank notes. The
Queen's head appears on English bank notes, and 'lady' refers to this.
mutilate v. 
chew v. 
microwave n. 
oven n. 
safekeeping n. 
Newcastle n. 
identify v. 
spokeswoman n. 
.3,000
------21000
150
** Lesson 8 A famous monastery
What are the St. Bernard dogs used for?
The Great St. Bernard Pass connects Switzerland to Italy. At 2,473
metres, it is the highest mountain pass in Europe. The famous monastery
of St. Bernard, witch was founded in eleventh century, lies about a mile
away. For hundreds of years, St. Bernard dogs have saved the lives of
travellers crossing the dangerous Pass. These friendly dogs, which were
first brought from Asia, were used as watchdogs even in Roman times. Now
that a tunnel ahs been built through the mountains, the Pass is less
dangerous, but each year, the dogs are still sent out into the snow
whenever a traveller is in difficulty. Despite the new tunnel, there are
still a few people who rashly attempt to cross the Pass on foot.
During the summer months, the monastery is very busy, for it is visited
by thousands of people who cross the Pass in cars. As there are so many
people about, the dogs have to be kept in a special enclosure. In
winter, however, life at the monastery is quite different. The
temperature drops to -- 30 o and very few people attempt to cross the
Pass. The monks prefer winter to summer of they have more privacy. The
dogs have greater freedom, too, for they are allowed to wander outside
their enclosure. The only regular visitors to the monastery in winter
are parties of skiers who go there at Christmas and Easter. These young
people, who love the peace of mountains, always receive a warm welcome
at St. Bernard's monastery.
monastery n. 
St. Bernard 
pass n. 
watchdog n. 
rashly adj. 
enclosure n. 
monk n. 
privacy n. 
skier n. 
Easter n. 
2,473O111
30
** Lesson 9 Flying cats
How do cats try to protect themselves when falling from great heights?
Cats never fail to fascinate human beings. They can be friendly and
affectionate towards humans, but they lead mysterious lives of their own
as well. They never become submissive like dogs and horses. As a result,
humans have learned to respect feline independence. Most cats remain
suspicious of humans all their lives. One of the things that fascinates
us most about cats is the popular belief that they have nine lives.
Apparently, there is a good deal of truth in this idea. A cat's ability
to survive falls is based on fact.
Recently the New York Animal Medical Center made a study of 132 cats
over a period of five months. All these cats had one experience in
common: they had fallen off high buildings, yet only eight of them died
from shock or injuries. Of course, New York is the ideal place for such
an interesting study, because there is no shortage of tall buildings.
There are plenty of high-rise windowsills to fall from! One cat,
Sabrina, fell 32 storeys, yet only suffered from a broken tooth. 'Cats
behave like well-trained paratroopers.' a doctor said. It seems that the
further cats fall, the less they are likely to injure themselves. In a
long drop, they reach speeds of 60 miles an hour and more. At high
speeds, falling cats have time to relax. They stretch out their legs
like flying squirrels. This increases their air-resistance and reduces
the shock of impact when they hit the ground.
fascinate v. 
affectionate adj. 
mysterious adj. 
submissive adj. 
feline adj. 
independence n. 
high-rise adj. 
windowsill n. 
paratrooper n. 
squirrel n. 
air-resistance n. 
impact n. 
------
1325832
60
** Lesson 10 The loss of the Titanic
What would have happened if only two of the sixteen water-tight
compartments had been flooded?
The great ship, Titanic, sailed for New York from Southampton on April
10th, 1912. She was carrying 1,316 passengers and crew of 891. Even by
modern standards, the 46,000 ton Titanic was a colossal ship. At the
time, however, she was not only the largest ship that had ever been
built, but was regarded as unsinkable, for she had sixteen watertight
compartments. Even if two of these were flooded, she would still be able
to float. The tragic sinking of this great liner will always be
remembered, for she went down on her first voyage with heavy loss of
life.
Four days after setting out, while the Titanic was sailing across the
icy water of the North Atlantic, huge iceberg was suddenly spotted by a
lookout. After the alarm had been given, the great ship turned sharply
to avoid a direct collision. The Titanic turned just in time, narrowly
missing the immense walk of ice which rose over 100 feet out of the
water beside her. Suddenly, there was a slight trembling sound from
below, and the captain went down to see what had happened. The noise had
been so faint that no one though that the ship had been damaged. Below,
the captain realized to his horror that the Titanic was sinking rapidly,
for five of her sixteen watertight compartments had already been
flooded! The order to abandon ship was given and hundreds of people
plunged into the icy water. As there were not enough lifeboats for
everybody, 1,500 lives were lost.
Southampton n. 
colossal adj. 
watertight adj. 
compartment n. 
flood v. 
float v. 
tragic adj. 
liner n. 
voyage n. 
iceberg n. 
lookout n. 
collision n. 
narrowly adv. 
miss v. 
slight adj. 
tremble v. 
faint adj. 
horror n. 
abandon v. 
plunge v. 
lifeboat n. 
19124101,31689145,000
16
41001651,500
** Lesson 11 Not guilty
What was the Customs Officer looking for?
Customs Officers are quite tolerant these days, but they can still stop
you when you are going through the Green Channel and have nothing to
declare. Even really honest people are often made to feel guilty. The
hardened professional smuggler, on the other hand, is never troubled by
such feelings, even if he has five hundred gold watches hidden in his
suitcase. When I returned form abroad recently, a particularly officious
young Customs Officer clearly regarded me as a smuggler.
'Have you anything to declare?' he asked, looking me in the eye.
'No', I answered confidently.
'Would you mind unlocking this suitcase please?'
'Not at all,' I answered.
The Officer went through the case with great care. All the thing I had
packed so carefully were soon in a dreadful mess. I felt sure I would
never be able to close the case again. Suddenly, I saw the Officer's
face light up. He had spotted a tiny bottle at the bottom of my case and
he pounced on it with delight.
'Perfume, eh?' he asked sarcastically. 'You should have declared that.
Perfume is not exempt from import duty.'
'But it isn't perfume,' I said. 'It's hair gel.' Then I added with a
smile, 'It's a strange mixture I make myself.'
As I expected, he did not believe me.
'Try it!' I said encouragingly.
The officer unscrewed the cap and put the bottle to his nostrils. He was
greeted by an unpleasant smell which convinced him that I was telling
the truth. A few minutes later, I was able to hurry away with precious
chalk marks on my baggage.
guilty adj. 
tolerant adj. 
declare v. 
hardened adj. 
professional adj. 
smuggler n. 
officious adj. 
confidently adv. 
dreadful adj. 
pounce v. 
perfume n. 
sarcastically adv. 
exempt adj. 
duty n. 
gel n. 
mixture n. 
unscrew v. 
nostril n. 
chalk n. 
baggage n. 
500
** Lesson 12 Life on a desert island
What was exceptional about the two men's stay on the desert island?
Most of us have formed an unrealistic picture of life on a desert
island. We sometimes imagine a desert island to be a sort of paradise
where the sun always shines. Life there is simple and good. Ripe fruit
falls from the trees and you never have to work. The other side of the
picture is quite the opposite. Life on a desert island is wretched. You
either starve to death or live like Robinson Crusoe, Waiting for a boat
which never comes. Perhaps there is an element of truth in both these
pictures, but few us have had the opportunity to find out.
Two men who recently spent five days on a coral island wished they had
stayed there longer. They were taking a badly damaged boat from the
Virgin Islands to Miami to have it repaired. During the journey, their
boat began to sink. They quickly loaded a small rubber dinghy with food,
matches, and cans of beer and rowed for a few miles across the Caribbean
until they arrived at a tiny coral island. There were hardly any trees
on the island and there was no water, but this did not prove to be a
problem. The men collected rainwater in the rubber dinghy. As they had
brought a spear gun with them, they had plenty to eat. They caught
lobster and fish every dayand, as one of them put it 'ate like kings'.
When a passing tanker rescued them five days later, both men were
genuinely sorry that they had to leave.
desert island
unrealistic adj. 
paradise n. 
wretched adj. 
starve v. 
element n. 
opportunity n. 
coral n. 
Miami n. 
dinghy n. 
Caribbean n. 
spear gun 
lobster n. 
tanker n. 
genuinely adv. 
55
** Lesson 13 "It's only me'
What did the man expect to find under the stairs?
After her husband had gone to work. Mrs. Richards sent her children to
school and went upstairs to her bedroom. She was too excited to do any
housework that morning, for in the evening she would be going to a
fancy-dress part with her husband. She intended to dress up as a ghost
and as she had made her costume the night before, she was impatient to
try it on. Though the costume consisted only of a sheet, it was very
effective. After putting it on, Mrs. Richards went downstairs. She
wanted to find out whether it would be comfortable to wear.
Just as Mrs. Richards was entering the dinning room, there was a knock
on the front door. She knew that it must be the baker. She had told him
to come straight in if ever she failed to open the door and to leave the
bread on the kitchen table. Not wanting to frighten the poor man, Mrs.
Richards quickly hid in the small storeroom under the stairs. She heard
the front door open and heavy footsteps in the hall. Suddenly the door
of the storeroom was opened and a man entered. Mrs. Richards realized
that it must be the man from the Electricity Board who had come to read
the metre. She tried to explain the situation, saying 'It's only me',
but it was too late. The man let out cry and jumped back several paces.
When Mrs. Richards walked towards him, he fled, slamming the door behind
him.
costume n. 
consist v. ......
sheet n. 
effective adj. 
metre n. 
pace n. 
lee (fled, fled) v. 
slam v. 
** Lesson 14 A noble gangster
How did Haywood make in times of peace?
There was a tine when the owners of shops and businesses in Chicago that
to pay large sums of money to gangsters in return for 'protection.' If
the money was not paid promptly, the gangsters would quickly put a man
out of business by destroying his shop. Obtaining 'protection money' is
not a modern crime. As long ago as the fourteenth century, an
Englishman, Sir John Hawkwood, made the remarkable discovery that people
would rather pay large sums of money than have their life work destroyed
by gangsters.
Six hundred years ago, Sir Johan Hawkwood arrived in Italy with a band
of soldiers and settled near Florence. He soon made a name for himself
and came to be known to the Italians as Giovanni Acuto. Whenever the
Italian city-states were at war with each other, Hawkwood used to hire
his soldiers to princes who were willing to pay the high price he
demanded. In times of peace, when business was bad, Hawkwood and his men
would march into a city-state and, after burning down a few farms, would
offer to go away protection money was paid to them. Hawkwood made large
sums of money in this way. In spite of this, the Italians regarded him
as a sort of hero. When he died at the age of eighty, the Florentines
gave him a state funeral and had a pictured with as dedicated to the
memory of 'the most valiant soldier and most notable leader, Signor
Giovanni Haukodue.'
gangster n. ,
Chicago n. ()
protection n. 
promptly adv. 
destroy v. ;
remarkable adj. 
hand n. ,
Florence n. ()
city-state n. ()
hire v. ,
prince n. ,
Florentine n. 
funeral n. 
dedicate v. ,
memory n. 
valiant adj. 
,"",,."".14,.:",.
600,.,,...,,,,,,,.,80,,".."
** Lesson 15 Fifty pence worth of trouble
Did George get anything for his fifty pence? What?
Children always appreciate small gifts of money. Mum or dad, of course,
provide a regular supply of pocket money, but uncles and ants are always
a source of extra income. With some children, small sums go a long way.
If fifty pence pieces are not exchanged for sweets, they rattle for
months inside money boxes. Only very thrifty children manage to fill up
a money box. For most of them, fifty pence is a small price to pay for a
nice big bar of chocolate.
My nephew, George, has a money box but it is always empty. Very few of
the fifty pence pieces and pound coins I have given him have found their
way there. I gave him fifty pence yesterday and advised him to save it.
Instead he bought himself fifty pence worth of trouble. On his way to
the sweet shop, he dropped his fifty pence and it bounced along the
pavement and then disappeared down a drain. George took off his jacket,
rolled up his sleeves and pushed is right arm through the drain cover.
He could not find his fifty pence piece anywhere, and what is more, he
could no get his arm out. A crowd of people gathered round him and a
lady rubbed his arm with soap and butter, but George was firmly stuck.
The fire brigade was called and two fire fighter freed George using a
special type of grease. George was not too upset by his experience
because the lady who owns the sweet shop heard about his troubles and
rewarded him with large box of chocolates.
appreciate v. 
thrifty adj. 
nephew n. 
bounce v. 
pavement n. 
stick (stuck, stuck) v. 
brigade n. 
grease n. 
5050
5050505050
* Unit 2
** Lesson 16 Mary had a little lamb
Was Dimitri right to apologize to his neighbour? Why not?
Mary and her husband Dimitri lived in the tiny village of Perachora in
southern Greece. One of Mary's prize possessions was a little white lamb
which her husband had given her. She kept it tied to a tree in a field
during the day and went to fetch it every evening. One evening, however,
the lamb was missing. The rope had been cut, so it was obvious that the
lamb had been stolen.
When Dimitri came in from the fields, his wife told him what had
happened. Dimitri at once set out to find the thief. He knew it would
not prove difficult in such a small village. After telling several of
his friends about the theft, Dimitri found out that his neighbour,
Aleko, had suddenly acquired a new lamb. Dimitri immediately went to
Aleko's house and angrily accused him of stealing the lamb. He told him
he had better return it or he would call the police. Aleko denied taking
it and led Dimitri into his backyard. It was true that he had just
bought a lamb, he explained, but his lamb was black. Ashamed of having
acted so rashly, Dimitri apologized to Aleko for having accused him.
While they were talking it began to rain and Dimitri stayed in Aleko's
house until the rain stopped. When he went outside half an hour later,
he was astonished to find the little black lamb was almost white. Its
wool, which had been dyed black, had been washed clean by the rain!
prize adj. 
tie v. 
theft n. 
accuse v. 
deny v. 
ashamed adj. 
apologize v. 
dye v. 
** Lesson 17 The longest suspension
bridge in the world
How is the bridge supported?
Verrazano, an Italian about whom little is known, sailed into New York
Harbour in 1524 and named it Angouleme. He described it as 'a very
agreeable situation located within two small hills in the midst of which
flowed a great river.' Though Verrazano is by no means considered to be
a great explorer, his name will probably remain immortal, for on
November 21st, 1964, the longest suspension bridge in the world was
named after him.
The Verrazano Bridge, which was designed by Othmar Ammann, joins
Brooklyn to Staten Island. It has a span of 4,260 feet. The bridge is so
long that the shape of the earth had to be taken into account by its
designer. Two great towers support four huge cables. The towers are
built on immense underwater platforms make of steel and concrete. The
platforms extend to a depth of over 100 feet under the sea. These alone
took sixteen months to build. Above the surface of the water, the towers
rise to a height of nearly 700 feet. They support the cables from which
the bridge has been suspended. Each of the four cables contains 26,108
lengths of wire. It has been estimated that if the bridge were packed
with cars, it would still only be carrying a third of its total
capacity. However, size and strength are not the only important things
about this bridge. Despite its immensity, it is both simple and elegant,
fulfilling its designer's dream to create 'an enormous object drawn as
faintly as possible'.
suspension n. 
agreeable adj. 
situation n. 
locate v. 
immortal adj. 
Brooklyn n. 
Staten n. 
span n. 
cable n. 
concrete n. 
suspend v. 
length n. 
estimate v. 
capacity n. 
immensity n. 
elegant adj. 
faintly adv. 
152419641121
.4,2604100167004261081/3
** Lesson 18 Electric currents in modern art
How might some of the exhibits have been dangerous?
Modern sculpture rarely surprises us any more. The idea that modern art
can only be seen in museums is mistaken. Even people who take no
interest in art cannot have failed to notice examples of modern
sculpture on display in public places. Strange forms stand in gardens,
and outside buildings and shops. We have got quite used to them. Some
so-called 'modern' pieces have been on display for nearly eighty years.
In spite of this, some people -- including myself -- were surprise by a
recent exhibition of modern sculpture. The first thing I saw when I
entered the art gallery was a notice which said: 'Do not touch the
exhibits. Some of them are dangerous!' The objects on display were
pieces of moving sculpture. Oddly shaped forms that are suspended form
the ceiling and move in response to a gust of wind are quite familiar to
everybody. These objects, however, were different. Lined up against the
wall, there were long thin wires attached to metal spheres. The spheres
had been magnetized and attracted or repelled each other all the time.
In the centre of the hall, there were a number of tall structures which
contained coloured lights. These lights flickered continuously like
traffic lights which have gone mad. Sparks were emitted from small black
boxes and red lamps flashed on and off angrily. It was rather like an
exhibition of prehistoric electronic equipment. These peculiar forms not
only seemed designed to shock people emotionally, but to give them
electric shocks as well!
current n. 
sculpture n. 
mistaken adj. 
gallery n. 
exhibit n. 
oddly adv. 
attach v. 
sphere n. 
magnetize v. 
repel v. 
flicker v. 
emit v. 
flash v. 
prehistoric adj. 
electronic adj. 
peculiar adj. 
shock v. 
emotionally adv. 
80
** Lesson 19 A very dear cat
Why was Rastus 'very dear' in more ways than one?
Kidnappers are rarely interested in animals, but they recently took
considerable interest in Mrs. Eleanor Ramsay's cat. Mrs. Eleanor Ramsay,
a very wealthy old lady, has shared a flat with her cat, Rastus, for a
great many years. Rastus leads an orderly life. He usually takes a short
walk in the evenings and is always home by seven o'clock. One evening,
however, he failed to arrive. Mrs. Ramsay got very worried. She looked
everywhere for him but could not find him.
There days after Rastus' disappearance, Mrs. Ramsay received an
anonymous letter. The writer stated that Rastus was in safe hands and
would be returned immediately if Mrs. Ramsay paid a ransom of $1,000.
Mrs. Ramsay was instructed to place the money in a cardboard box and to
leave it outside her door. At first she decided to go to the police, but
fearing that she would never see Rastus again -- the letter had made
that quite clear -- she changed her mind. She withdrew $1000 from her
bank and followed the kidnapper's instructions. The next morning, the
box had disappeared but Mrs. Ramsay was sure that the kidnapper would
keep his word. Sure enough, Rastus arrived punctually at seven o'clock
that evening. He looked very well though he was rather thirsty, for he
drank half a bottle of milk. The police were astounded when Mrs. Ramsay
told them what she had done. She explained that Rastus was very dear to
her. Considering the amount she paid, he was dear in more ways than one!
dear adj. 
kidnapper n. 
considerable adj. 
wealthy adj. 
orderly adj. 
disappearance n. 
anonymous adj. 
ransom n. 
cardboard n. 
withdraw(withdrew, withdrawn) v. 
punctually adv. 
astound v. 
..7
31,000
------------1,000
7
** Lesson 20 Pioneer pilots
What was the name of the first plane to fly across the English Channel?
In 1908 Lord Northcliffe offered a prize of $1,000 to the first man who
would fly across the English Channel. Over a year passed before the
first attempt was made. On July 19th, 1909, in the early morning, Hubert
Latham took off from the French coast in his plane the 'Antoinette IV.'
He had travelled only seven miles across the Channel when his engine
failed and he was forced to land on sea. The 'Antoinette' floated on the
water until Latham was picked up by a ship.
Two days alter, Louis Bleriot arrived near Calais with a plane called
'No. XI'. Bleriot had been making planes since 1905 and this was his
lattes model. A week before, he had completed a successful overland
flight during which he covered twenty-six miles. Latham, however, did
not give up easily. He, too, arrived near Calais on the same day with a
new 'Antoinette'. It looked as if there would be an exciting race across
the Channel. Both planes were going to take off on July 25th, but Latham
failed to get up early enough, After making a short test flight at 4,15
a.m., Bleriot set off half an hour later. His great flight lasted
thirty-seven minutes. When he landed near Dover, the first person to
greet him was a local policeman. Latham made another attempt a week
later and got within half a mile of Dover, but he was unlucky again. His
engine failed and he landed on the sea for the second time.
pioneer n. 
lord n. 
Calais n. 
overland adj. 
19081,0001909719.47
.111905112672541537
** Lesson 21 Daniel Mendoza
.
How many unsuccessful attempts did Mendoza make before becoming Champion
of all England?
Boxing matches were very popular in England two hundred years ago. In
those days, boxers fought with bare fists for prize money. Because of
this, they were known as 'prizefighters'. However, boxing was very
crude, for these were no rules and a prizefighter could be seriously
injured or even killed during a match.
One of the most colourful figures in boxing history was Daniel Mendoza,
who was born in 1764. The use of gloves was not introduced until 1860,
when the Marquis of Queensberry drew up the first set of rules. Though
he was technically a prizefighter, Mendoza did much to change crude
prizefighting into a sport, for he brought science to the game. In this
day, Mendoza enjoyed tremendous popularity. He was adored by rich and
poor alike.
Mendoza rose to fame swiftly after a boxing match when he was only
fourteen years old. This attracted the attention of Richard Humphries
who was then the most eminent boxer in England. He offered to train
Mendoza and his young pupil was quick to learn. In fact, Mendoza soon
became so successful that Humphries turned against him. The two men
quarrelled bitterly and it was clear that the argument could only be
settled by a fight. A match was held at Stilton, where both men fought
for an hour. The public bet a great deal of money on Mendoza, but he was
defeated. Mendoza met Humphries in the ring on a later occasion and he
lost for a second time. It was not until his third match in 1790 that he
finally beat Humphries and became Champion of England. Meanwhile, he
founded a highly successful Academy and even Lord Byron became one of
his pupils. He earned enormous sums of money and was paid as much as
$100 for a single appear one of his pupils. He earned enormous sums of
money and was paid as much as $100 for a single appearance. Despite
this, he was so extravagant that he was always in debt. After he was
defeated by a boxer called Gentleman Jackson, he was quickly forgotten.
He was sent to prison for failing to pay his debts and died in poverty
in 1836.
Boxing n. 
boxer n. 
bare adj. 
prizefighter n. 
crude adj. 
marquis n. 
technically adv. 
science n. 
popularity n. 
adore v. 
alike adv. 
fame n. 
eminent adj. 
bitterly adv. 
bet v. 
academy n. 
extravagant adj. 
poverty n. 
.17641860
14.179031001836
** Lesson 22 By heart
Which actor read the letter in the end, the aristocrat or the gaoler?
Some plays are so successful that they run for years on end, In many
ways, this is unfortunate for the poor actors who are required to go on
repeating the same lines night after night. One would expect them to
know their parts by heart and never have cause to falter. Yet this is
not always the case.
A famous actor in a highly successful play was once cast in the role of
an aristocrat who had been imprisoned in the Bastille for twenty years.
In the last act, a gaoler would always come on to the stage with a
letter which he would hand to the prisoner. Even though the noble was
expected to read the letter at each performance, he always insisted that
it should be written out in full.
One night, the gaoler decided to play a joke on his colleague to find
out if, after so many performances, he had managed to learn the contents
of the letter by heart. The curtain went up on the final act of the play
and revealed the aristocrat sitting alone behind bars in his dark cell.
Just then, the gaoler appeared with the precious letter in his bands. He
entered the cell and presented the letter to the aristocrat. But the
copy he gave him had not been written out in full as usual. It was
simply a blank sheet of paper. The gaoler looked on eagerly, anxious to
see if his fellow actor had at last learnt his lines. The noble stared
at the blank sheet of paper for a few seconds. Then, squinting his eyes,
he said: 'The light is dim. Read the letter to me'. And he promptly
handed the sheet of paper to the gaoler. Finding that he could not
remember a word of the letter either, the gaoler replied: 'The light is
indeed dim, sire, I must get my glasses.' With this, he hurried off the
stage. Much to the aristocrat's amusement, the gaoler returned a few
moments later with a pair of glasses and the usual copy of the letter
with he proceeded to read to the prisoner.
run (ran, run) v. 
lines n. 
part n. 
falter v. 
cast (cast, cast) v. ......
role n. 
aristocrat n. 
imprison v. 
Bastille n. 
gaoler n. 
colleague n. 
curtain n. 
reveal v. 
cell n. 
blank adj. 
squint v. 
dim adj. 
sire n. 
proceed v. 
20
** Lesson 23 One man's meat is
another man's poison
What was it about snails that made the writer collect them for his
friend on that in particular?
People become quite illogical when they try to decide what can be eaten
and what cannot be eaten. If you lived in the Mediterranean, for
instance, you would consider octopus a great delicacy. You would not be
able to understand why some people find it repulsive. On the other hand,
your stomach would turn at the idea of frying potatoes in animal fat --
the normally accepted practice in many northern countries. The sad truth
is that most of us have been brought up to eat certain foods and we
stick to them all our lives.
No creature has received more praise and abuse than the common garden
snail. Cooked in wine, snails are a great luxury in various parts of the
world. There are countless people who, ever since their early years,
have learned to associate snails with food. My friend, Robert, lives in
a country where snails are despised. As his flat is in a large town, he
has no garden of his own. For years he has been asking me to collect
snails from my garden and take them to him. The idea never appealed to
me very much, but one day, after heavy shower, I happened to be walking
in my garden when I noticed a huge number of snails taking a stroll on
some of my prize plants. Acting on a sudden impulse, I collected several
dozen, put them in a paper bag, and took them to Robert. Robert was
delighted to see me and equally pleased with my little gift. I left the
bag in the hall and Robert and I went into the living room where we
talked for a couple of hours. I had forgotten all about the snails when
Robert suddenly said that I must stay to dinner. Snails would, of
course, be the main dish. I did not fancy the idea and I reluctantly
followed Robert out of the room. To our dismay, we saw that there were
snails everywhere: they had escaped from the paper bag and had taken
complete possession of the hall! I have never been able to look at a
snail since then.
poison (title) n. 
illogical adj. 
octopus n. 
delicacy n. 
repulsive adj. 
stomach n. 
turn v. 
fry v. 
fat n. 
abuse n. 
snail n. 
luxury n. 
associate v. 
despise v. 
appeal v. 
shower n. 
stroll n. 
impulse n. 
dozen n. 12
fancy v. 
** Lesson 24 A skeleton in the cupboard
Who was Sebastian?
We often read in novels how a seemingly respectable person or family has
some terrible secret which has been concealed from strangers for years.
The English language possesses a vivid saying to describe this sort of
situation. The terrible secret is called 'a skeleton in the cupboard'.
At some dramatic moment in the story, the terrible secret becomes known
and a reputation is ruined. The reader's hair stands on end when he
reads in the final pages of the novel that the heroine a dear old lady
who had always been so kind to everybody, had, in her youth, poisoned
every one of her five husbands.
It is all very well for such things to occur in fiction. To varying
degrees, we all have secrets which we do not want even our closest
friends to learn, but few of us have skeletons in the cupboard. The only
person I know who has a skeleton in the cupboard is George Carlton, and
he is very pound of the fact. George studied medicine in his youth.
Instead of becoming a doctor, however, he became a successful writer of
detective stories. I once spend an uncomfortable weekend which I shall
never forget at his house. George showed me to the guestroom which, he
said, was rarely used. He told me to unpack my things and then come down
to dinner. After I had stacked my shirts and underclothes in two empty
drawers, I decided to hang one of the tow suits I had brought with me in
the cupboard. I opened the cupboard door and then stood in front of two
suits I had brought with me in the cupboard. I opened the cupboard door
and then stood in front of it suits I had brought with me in the
cupboard. I opened the cupboard door and then stood in front of it
petrified. A skeleton was dangling before my eyes. The sudden movement
of the door made it sway slightly and it gave me the impression that it
was about to leap out at me. Dropping my suit, I dashed downstairs to
tell George. This was worse than "a terrible secret'; this was a read
skeleton! But George was unsympathetic. 'Oh, that,' he said with a smile
as if he were talking about an old friend. 'That's Sebastian. You forget
that I was a medical student once upon a time.'
skeleton n. 
seemingly adv. 
respectable adj. 
conceal v. 
vivid adj. 
dramatic adj. 
ruin v. 
heroine n. 
fiction n. 
varying adj. 
medicine n. 
guestroom n. 
unpack vt. 
stack v. 
underclothes n. 
drawer n. 
petrify v. 
dangle v. 
sway v. 
unsympathetic adj. 
medical adj. 
5
.
** Lesson 25 The Cutty Sark
What piece of bad luck prevented the Cutty Sark from winning the race?
One of the most famous sailing ships of the nineteenth century, the
Cutty Sark, can still be seen at Greewich. She stands on dry land and is
visited by thousands of people each year. She serves as an impressive
reminder of the great ships of past. Before they were replaced by
steamships, sailing vessels like the Cutty Sark were used to carry tea
from China and wool from Australia. The Cutty Sark was one the fastest
sailing ships that has ever been built. The only other ship to match her
was the Thermopylae. Both these ships set out from Shanghai on June
18th, 1872 on an exciting race to England. This race, which went on for
exactly four exactly four months, was the last of its kind. It marked
the end of the great tradition of ships with sails and the beginning of
a new era.
The first of the two ships to reach Java after the race had begun was
the Thermopylae, but on the Indian Ocean, the Cutty Sark took lead. It
seemed certain that she would be the first ship home, but during the
race she had a lot of bad luck. In August, she was struck by a very
heavy storm during which her rudder was torn away. The Cutty Sark rolled
from side to side and it became impossible to steer her. A temporary
rudder was made on board from spare planks and it was fitted with great
difficulty. This greatly reduced the speed of the ship, for there was a
danger that if she traveled too quickly, this rudder would be torn away
as well. Because of this, the Cutty Sark lost her lead. After crossing
the Equator, the captain called in at a port to have a new rudder
fitted, but by now the Thermopylae was over five hundred miles ahead.
Though the new rudder was fitted at tremendous speed, it was impossible
for the Cutty Sark to win. She arrived in England a week after the
Thermopylae. Even this was remarkable, considering that she had had so
many delays. These is no doubt that if she had not lost her rudder she
would have won the race easily.
impressive adj. 
steamship n. 
vessel n. 
era n. 
Java n. 
rudder n. 
roll v. 
steer v. 
temporary adj. 
plank n. 
fit v. 
Equator n. 
delay n. 
1918726184
85001
** Lesson 26 Wanted: a large biscuit tin
Listen who the prize for biggest biscuit?
No one can avoid being influenced by advertisements. Much as we may
pride ourselves on our good taste, we are no longer free to choose the
things we want, for advertising exerts a subtle influence on us. In
their efforts to persuade us to buy this or that product, advertisers
have made a close study of human nature and have classified all our
little weaknesses.
Advertisers discovered years ago that all of us love to get something
for nothing. An advertisement which begins with the magic word FREE can
rarely go wrong. These days, advertisers not only offer free samples,
but free cars, free houses, and free trips round the world as well. They
devise hundreds of competitions which will enable us to win huge sums of
money. Radio and television have made it possible for advertisers to
capture the attention of millions of people in this way.
During a radio programme, a company of biscuit manufacturers once asked
listeners to bake biscuits and send them to their factory. They offered
to pay $10 a pound for the biggest biscuit baked by a listener. The
response to this competition was tremendous. Before long, biscuits of
all shapes and sizes began arriving at the factory. One lady brought in
a biscuit on a wheelbarrow. It weighed nearly 500 pounds. A little
later, a man came along with a biscuit which occupied the whole boot of
his car. All the biscuits that were sent were carefully weighed. The
largest was 713 pounds. It seemed certain that this would win the prize.
But just before the competition closed, a lorry arrived at the factory
with a truly colossal biscuit which weighed 2,400 pounds. It had been
baked by a college student who had used over 1,000 pounds of flour, 800
pounds of sugar, 200 pounds of fat, and 400 pounds of various other
ingredients. It was so heavy that a crane had to be used to remove it
from the lorry. The manufacturers had to pay more money than they had
anticipated, or they bought the biscuit from the student for $24,000.
influence v. 
pride v. 
taste n. 
exert v. 
subtle adj. 
advertiser n. 
classify v. 
magic adj. 
sample n. 
devise v. 
capture v. 
manufacturer n. 
wheelbarrow n. 
boot n. 
ingredient n. 
crane n. 
anticipate v. 
105007132,4001,00080020040024,000
** Lesson 27 Nothing to sell and nothing to buy
What is the most important thing for a tramp?
It has been said that everyone lives by selling something. In the light
of this statement, teachers live by selling knowledge, philosophers by
selling wisdom and priests by selling spiritual comfort. Though it may
be possible to measure the value of material good in terms of money, it
is extremely difficult to estimate the true value of the services which
people perform for us. There are times when we would willingly give
everything we possess to save our lives, yet we might grudge paying a
surgeon a high fee for offering us precisely this service. The
conditions of society are such that skills have to be paid for in the
same way that goods are paid for at a shop. Everyone has something to
sell.
Tramps seem to be the only exception to this general rule. Beggars
almost sell themselves as human being to arouse the pity of passers-by.
But real tramps are not beggars. They have nothing to sell and require
nothing from others. In seeking independence, they do not sacrifice
their human dignity. A tramp may ask you for money, but he will never
ask you to feel sorry for him. He has deliberately chosen to lead the
life he leads and is fully aware of the consequences. He may never be
sure where the next meal is coming from, but his is free from the
thousands of anxieties which afflict other people. His few material
possessions make it possible for him to move from place to place with
ease. By having to sleep in the open, he gets far closer to the world of
nature than most of us ever do. He may hunt, beg, or stead occasionally
to keep himself alive; he may even, in times of real need, do a little
work; but he will never sacrifice his freedom. We often speak of my
even, in times of real need, do a little work; but he will never
sacrifice his freedom. We often speak of tramps with contempt and put
them in the same class as beggars, but how many of us can honestly say
that we have not felt a little envious of their simple way of life and
their freedom from care?
philosopher n. 
wisdom n. 
priest n. 
spiritual adj. 
grudge v. 
surgeon n. 
passer-by n.  passers-by)
dignity n. 
deliberately adv. 
consequence n. 
afflict v. 
ease n. 
nature n. 
contempt n. 
envious adj. 
** Lesson 28 Five pound too dear
Why was even five pounds 'too dear'?
Small boats loaded with wares sped to the great liner as she was
entering the harbour. Before she had anchored, the men from the boats
had climbed on board and the decks were son covered with colourful rugs
from Persia, silks from India, copper coffee pots, and beautiful
handmade silverware. It was difficult not to be tempted. Many of the
tourists on board had begun bargaining with the tradesmen, but I decide
not to buy anything until I had disembarked.
I had no sooner got off the ship than I was assailed by a man who wanted
to sell me a diamond ring. I had no intention of buying one, but I could
not conceal the fact that I was impressed by the size of the diamonds.
Some of them were as big as marbles. The man went to great lengths to
prove that the diamonds were real. As we were walking past a shop, he
held a diamond firmly against the window and made a deep impression in
the glass. It took me over half an hour to get rid of him.
The next man to approach me was selling expensive pens and watches. I
examined one of the pens closely. It certainly looked genuine. At the
base of the gold cap, the words 'made in the U.S.A' had been nearly
inscribed. The man said that the pen was worth $50, but as a special
favour, he would let me have it for $30. I shook my head and held up
five fingers indicating that I was willing to pay $5. Gesticulating
wildly, the man acted as if he found my offer outrageous, but he
eventually reduced the price to $10. Shrugging my shoulders, I began to
walk away when, a moment later, he ran after me and thrust the pen into
my hands. Though he kept throwing up his arms in despair, he readily
accepted the $5 I have him. I felt especially pleased with my wonderful
bargain -- until I got back to the ship. No matter how hard I tried, it
was impossible to fill this beautiful pen with ink and to this day it
has never written a single world!
wares n. 
anchor v. 
deck n. 
silverware n. 
tempt v. 
bargain v. 
disembark v. 
assail v. 
marble n. 
inscribe v. 
favour n. 
gesticulate v. 
outrageous adj. 
thrust v. 
503055105
** Lesson 29 Funny or not?
What is the basis of 'sick' humour?
Whether we find a joke funny or not largely depends on were we have been
brought up. The sense of humour is mysteriously bound up with national
characteristics. A Frenchman, for instance, might find it hard to laugh
at a Russian joke. In the same way, a Russian might fail to see anything
amusing in a joke witch would make an Englishman laugh to tears.
Most funny stories are based on comic situations. In spite of national
differences, certain funny situations have a universal appeal. No matter
where you live, you would find it difficult not to laugh at, say,
Charlie Chaplin's early films. However, a new type of humour, which
stems largely from the U.S., has recently come into fashion. It is
called 'sick humour'. Comedians base their jokes on tragic situation
like violent death or serious accidents. Many people find this sort of
joke distasteful The following example of 'sick humour' will enable you
to judge for yourself.
A man who had broken his right leg was taken to hospital a few weeks
before Christmas. From the moment he arrived there, he kept on pestering
his doctor to tell him when he would be able to go home. He dreaded
having to spend Christmas in hospital. Though the doctors did his best,
the patient's recovery was slow. On Christmas Day, the man still had his
right leg in plaster. He spent a miserable day in bed thinking of all
the fun he was missing. The following day, however, the doctor consoled
him by telling him that his chances of being able to leave hospital in
time for New Year celebrations were good. The good. The man took heart
and, sure enough, on New Years' Eve he was able to hobble along to a
party. To compensate for his unpleasant experiences in hospital, the man
drank a little more than was good for him. In the process, he enjoyed
himself thoroughly and kept telling everybody how much he hated
hospitals. He was still mumbling something about hospitals at the end of
the party when he slipped on a piece of ice and broke his left leg.
largely adv. 
comic adj. 
universal adj. 
comedian n. 
distasteful adj. 
pester v. 
dread v. 
recovery n. 
plaster n. 
console v. 
hobble v. 
compensate v. 
mumble v. 
.
** Lesson 30 The death of a ghost
Why did the two brothers keep the secret?
For years, villagers believed that Endley Farm was hunted. The farm was
owned by two brothers, Joe and Bob Cox. They employed a few farmhands,
but no one was willing to work there long. Every time a worker gave up
his job, he told the same story. Farm labourers said that they always
woke up to find that work had been done overnight. Hay had been cut and
cowsheds had been cleaned. A farm worker, who stayed up all night
claimed to have seen a figure cutting corn in the moonlight. In time, it
became an accepted fact the Cox brothers employed a conscientious ghost
that did most of their work for them.
No one suspected that there might be someone else on the farm who had
never been seen. This was indeed the case. A short time ago, villagers
were astonished to learn that the ghost of Endley had died. Everyone
went to the funeral, for the 'ghost' was none other than Eric Cox, a
third brother who was supposed to have died as a young man. After the
funeral, Joe and Bob revealed a secret which they had kept for over
fifty years.
Eric had been the eldest son of the family, very much older than his two
brothers. He had been obliged to join the army during the Second World
War. As he hated army life, he decided to desert his regiment. When he
learnt that he would be sent abroad, he returned to the farm and his
father hid him until the end of the war. Fearing the authorities, Eric
remained in hiding after the war as well. His father told everybody that
Eric had been killed in action. The only other people who knew the
secret were Joe and Bob. They did not even tell their wives. When their
father died, they thought it their duty to keep Eric in hiding. All
these years, Eric had lived as a recluse. He used to sleep during the
day and work at night, quite unaware of the fact that he had become the
ghost of Endley. When he died, however, his brothers found it impossible
to keep the secret any longer.
labourer n. 
overnight adv. 
hay n. 
corn n. 
moonlight n. 
conscientious adj. 
suspect v. 
desert v. 
regiment n. 
action n. 
recluse n. 
..
.50
* Unit 3
** Lesson 31 A lovable eccentric
Why did the shop assistant refuse to serve Dickie?
True eccentrics never deliberately set out to draw attention to
themselves. They disregard social conventions without being conscious
that they are doing anything extraordinary. This invariably wins them
the love and respect of others, for they add colour to the dull routine
of everyday life.
Up to the time of his death, Richard Colson was one of the most notable
figures in our town. He was a shrewd and wealthy businessman, but most
people in the town hardly knew anything about this side of his life. He
was known to us all as Dickie and his eccentricity had become legendary
long before he died.
Dickie disliked snobs intensely. Though he owned a large car, he hardly
ever used it, preferring always to go on foot. Even when it was raining
heavily, he refused to carry an umbrella. One day, he walked into an
expensive shop after having been caught in a particularly heavy shower.
He wanted to buy a $300 watch for his wife, but he was in such a
bedraggled condition than an assistant refused to serve him. Dickie left
the shop without a word and returned carrying a large cloth bag. As it
was extremely heavy, he dumped it on the counter. The assistant asked
him to leave, but Dickie paid no attention to him and requested to see
the manager. Recognizing who the customer was, the manager was most
apologetic and reprimanded the assistant severely. When Dickie was given
the watch, the presented the assistant with the cloth bag. It contained
$300 in pennies. He insisted on the assistant's counting the money
before he left -- 30,000 pennies in all! On another occasion, he invited
a number of important critics to see his private collection of modern
paintings. This exhibition received a great deal of attention in the
press, for though the pictures were supposed to be the work of famous
artists, they had in fact been painted by Dickie. It took him four years
to stage this elaborate joke simply to prove that critics do not always
know what they are talking about.
lovable adj. 
eccentric n. 
disregard v. 
convention n. 
conscious adj. 
invariably adv. 
routine n. 
shrewd adj. 
eccentricity n. 
legendary adj. 
snob n. 
intensely adv. 
bedraggled adj. 
dump v. ......
apologetic adj. 
reprimand v. 
stage v. 
elaborate adj. 
.
30030030,000
4
** Lesson 32 A lost ship
Did the crew of the Elkor find what they were looking for? Why?
The salvage operation had been a complete failure. The small ship,
Elkor, which had been searching the Barents Sea for weeks, was on its
way home. A radio message from the mainland had been received by the
ship's captain instructing him to give up the search. The captain knew
that another attempt would be made later, for the sunken ship he was
trying to find had been carrying a precious cargo of gold bullion.
Despite the message, the captain of the Elkor decided to try once more.
The sea bed was scoured with powerful nets and there was tremendous
excitement on board went a chest was raised from the bottom. Though the
crew were at first under the impression that the lost ship had been
found, the contents of the chest proved them wrong. What they had in
fact found was a ship which had been sunk many years before.
The chest contained the personal belongings of a seaman, Alan Fielding.
There were books, clothing and photographs, together with letters which
the seaman had once received from his wife. The captain of the Elkor
ordered his men to salvage as much as possible from the wreck. Nothing
of value was found, but the numerous items which were brought to the
surface proved to be of great interest. From a heavy gun that was
raised, the captain realized that the ship must have been a cruiser. In
another chest, which contained the belongings of a ship's officer, there
was an unfinished letter which had been written on March 14th, 1943. The
captain learnt from the letter that the name of the lost ship was the
Karen. The most valuable find of all was the ship's log book, parts of
which it was still possible to read. From this the captain was able to
piece together all the information that had come to light. The Karen had
been sailing in a convoy to Russia when she was torpedoed by an enemy
submarine. This was later confirmed by naval official at the Ministry of
Defiance after the Elkor had returned home. All the items that were
found were sent to the War Museum.
salvage v. 
Barents n. 
sunken adj. 
cargo n. 
bullion n. 
scour v. 
chest n. 
contents n. 
belongings n. 
item n. 
cruiser n. 
find n. 
piece v. 
convoy n. 
torpedo v. 
submarine n. 
naval adj. 
ministry n. 
.1943314
** Lesson 33 A day t remember
What incident began the series of traffic accidents?
We have all experienced days when everything goes wrong. A day may begin
well enough, but suddenly everything seems to get out of control. What
invariably happens is that a great number of things choose to go wrong
at precisely the same moment. It is as if a single unimportant event set
up a chain of reactions. Let us suppose that you are preparing a meal
and keeping an eye on the baby at the same time. The telephone rings and
this marks the prelude to an unforeseen series of catastrophes. While
you are on the phone, the baby pulls the tablecloth off the table,
smashing half your best crockery and cutting himself in the process. You
hang up hurriedly and attend to baby, crockery, etc. Meanwhile, the meal
gets burnt. As if this were not enough to reduce you to tears, your
husband arrives, unexpectedly bringing three guests to dinner.
Things can go wrong on a big scale, as a number of people recently
discovered in Parramatta, a suburb of Sydney. During the rush hour one
evening two cars collided and both drivers began to argue. The woman
immediately behind the two cars happened to be a learner. She suddenly
got into a panic and stopped her car. This made the driver following her
brake hard. His wife was sitting beside him holding a large cake. As she
was thrown forward, the cake went right through the windscreen and
landed on the road. Seeing a cake flying through the air, a lorry driver
who was drawing up alongside the car, pulled up all of a sudden. The
lorry was loaded with empty beer bottles and hundreds of them slid off
the back of the vehicle and on to the road. This led to yet another
angry argument. Meanwhile, the traffic piled up behind. It took the
police nearly an hour to get the traffic on the move again. In the
meantime, the lorry driver had to sweep up hundreds of broken bottles.
Only two stray dogs benefited from all this confusion, for they greedily
devoured what was left of the cake. It was just one of those days!
prelude n. 
unforeseen adj. 
series n. 
catastrophe n. 
crockery n. 
suburb n. 
collide v. 
learner n. 
panic n. 
windscreen n. 
alongside prep.............
slide (slid,slid) v. 
stray adj. 
confusion n. 
greedily adv. 
devour v. 
3
** Lesson 34 A happy discovery
What was the 'happy discovery'?
Antique shops exert a peculiar fascination on a great many people. The
more expensive kind of antique shop where rare objects are beautifully
displayed in glass cases to keep them free from dust is usually a
forbidding place. But no one has to muster up courage to enter a less
pretentious antique shop. There is always hope that in its labyrinth of
musty, dark, disordered rooms a real rarity will be found amongst the
piles of assorted junk that little the floors.
No one discovers a rarity by chance. A truly dedicated bargain hunter
must have patience, and above all, the ability to recognize the worth of
something when he sees it. To do this, he must be at least as
knowledgeable as the dealer. Like a scientist bent on making a
discovery, he must cherish the hope that one day he will be amply
rewarded.
My old friend, Frank Halliday, is just such a person. He has often
described to me how he picked up a masterpiece for a mere $50. One
Saturday morning, Frank visited an antique shop in my neighbourhood. As
he had never been there before, he found a great deal to interest him.
The morning passed rapidly and Frank was about to leave when he noticed
a large packing case lying on the floor. The morning passed rapidly and
Frank just come in, but that he could not be bothered to open it. Frank
begged him to do so and the dealer reluctantly prised it open. The
contents were disappointing. Apart from an interesting-looking carved
dagger, the box was full of crockery, much of it broken. Frank gently
lifted the crockery out of the box an suddenly noticed a miniature
painting at the bottom of the packing case. As its composition and line
reminded him of an Italian painting he knew well, he decided to buy it.
Glancing at it briefly, the dealer told him that it was worth $50. Frank
could hardly conceal his excitement, for he knew that he had made a real
discovery. The tiny painting proved to be an unknown masterpiece by
Correggio and was worth hundreds of thousands of pounds.
antique n. 
fascination n. 
forbidding adj. 
muster v. 
pretentious adj. 
labyrinth n. 
musty adj. 
rarity n. 
assorted adj. 
junk n. 
litter v. 
dedicated adj. 
bargain hunter 
dealer v. 
cherish v. 
amply adv. 
masterpiece n. 
mere adj. 
prise v. 
carve v. 
dagger n. 
miniature adj. 
composition n. 
.5050
** Lesson 35 Justice was done
The word 'justice' is given two different meanings in the text. What is
the distinction between them?
The word justice is usually associated with courts of law. We might say
that justice has been done when a man's innocence or guilt has been
proved beyond doubt. Justice is part of the complex machinery of the
law. Those who seek it undertake an arduous journey and can never be
sure that they will find it. Judges, however wise or eminent, are human
and can make mistakes.
There are rare instances when justice almost ceases to be an abstract
concept. Reward or punishment are meted out quite independent of human
interference. At such times, justice acts like a living force. When we
use a phrase like 'it serves him right', we are, in part, admitting that
a certain set of circumstances has enabled justice to act of its own
accord.
When a thief was caught on the premises of large jewellery store on
morning, the shop assistants must have found it impossible to resist the
temptation to say 'it serves him right.' The shop was an old converted
house with many large, disused fireplaces and tall, narrow chimneys.
Towards midday, a girl heard a muffed cry coming from behind on of the
walls. As the cry was repeated several times, she ran to tell the
manager who promptly rang up the fire brigade. The cry had certainly
come form one of the chimneys, but as there were so many of them, the
fire fighters could not be certain which one it was. They located the
right chimney by tapping at the walls and listening for the man's cries.
After chipping through a wall which was eighteen inches thick, they
found that a man had been trapped in the chimney. As it was extremely
narrow, the man was unable to move, but the fire fighters were
eventually able to free him by cutting a huge hole in the wall. The
sorry-looking, blackened figure that emerged, admitted at once that he
had tried to break into the shop during the night but had got stuck in
the chimney. He had been there for nearly ten hours. Justice had been
done even before the man was handed over to the police.
justice n. 
court n. 
law n. 
innocence n. 
undertake v. 
arduous adj. 
abstract adj. 
concept n. 
mete out
interference n. 
accord n. 
premises n. 
convert v. 
disused adj. 
fireplace n. 
muffle v. 
chip v. 
blacken v. 
emerge v. 
1810
** Lesson 36 A chance in a million
What was the chance in a million?
We are less credulous than we used to be. In the nineteenth century, a
novelist would bring his story to a conclusion by presenting his readers
with a series of coincidences -- most of them wildly improbable. Readers
happily accepted the fact that an obscure maidservant was really the
hero's mother. A long-lost brother, who was presumed dead, was really
alive all the time and wickedly plotting to bring about the hero's
downfall. And so on. Modern readers would find such naive solution
totally unacceptable. Yet, in real life, circumstances do sometimes
conspire to bring about coincidences which anyone but a nineteenth
century novelist would find incredible.
When I was a boy, my grandfather told me how a German taxi driver, Franz
Bussman, found a brother who was thought to have been killed twenty
years before. While on a walking tour with his wife, he stooped to talk
to a workman. After they had gone on, Mrs. Bussman commented on the
workman's close resemblance to her husband and even suggested that he
might be his brother. Franz poured scorn on the idea, pointing out that
his brother had been killed in action during the war. Though Mrs.
Busssman fully acquainted with this story, she thought that there was a
chance in a million that she might be right. A few days later, she sent
a boy to the workman to ask him if his name was Hans Bussman. Needless
to say, the man's name was Hans Bussman and he really was Franz's
long-lost brother. When the brothers were reunited, Hans explained how
it was that he was still alive. After having been wounded towards the
end of the war, he had been sent to hospital and was separated from his
unit. The hospital had been bombed and Hans had made his way back into
Western Germany on foot. Meanwhile, his unit was lost and all records of
him had been destroyed. Hans returned to his family home, but the house
had been bombed and no one in the neighbourhood knew what had become of
the inhabitants. Assuming that his family had been killed during an air
raid, Hans settled down in a village fifty miles away where he had
remained ever since.
credulous adj. 
improbable adj. 
obscure adj. 
maidservant n. 
presume v. 
wickedly adv. 
plot v. 
downfall n. 
naive adj. 
unacceptable adj. 
conspire v. 
incredible adj. 
scorn n. 
acquaint v. 
reunite v. 
assume v. 
19------19
20..50
** Lesson 37 The Westhaven Express
What was the mistake the author made?
We have learnt to expect that trains will be punctual. After years of
conditioning, most of us have developed an unshakable faith in railway
timetables. Ships may be delayed by storms; flights may be cancelled
because of bad weather, but trains must be on time. Only an
exceptionally heavy snowfall might temporarily dislocate railway
services. It is all too easy to blame the railway authorities when
something does go wrong. The truth is that when mistakes occur, they are
more likely to be ours than theirs.
After consulting my railway timetable, I noted with satisfaction that
there was an express train to Westhaven. It went direct from my local
station and the journey lasted mere hour and seventeen minutes. When I
boarded the train, I could not help noticing that a great many local
people got on as well. At the time, this did not strike me as odd. I
reflected that there must be a great many local people besides myself
who wished to take advantage of this excellent service. Neither was I
surprise when the train stopped at Widley, a tiny station a few miles
along the line. Even a mighty express train can be held up by signals.
But when the train dawdled at station after station, I began to wonder,
It suddenly dawned on me that this express was not roaring down the line
at ninety miles an hour, but barely chugging along at thirty. One hour
and seventeen minutes passed and we had not even covered half the
distance. I asked a passenger if this was the Westhaven Express, but he
had not even heard of it. I determined to lodge a complaint as soon as
we arrived. Two hours later, I was talking angrily to the station master
at Westhaven. When he denied the train's existence, I borrowed his copy
of the timetable. There was a note of triumph in my voice when I told
him that it was there in black and white. Glancing at it briefly, he
told me to look again. A tiny asterisk conducted me to a footnote at the
bottom of the page. It said: 'This service has been suspended.'
express n.  adj. 
punctual adj. 
condition v. 
unshakable adj. 
faith n. 
cancel v. 
exceptionally adv. 
dislocate v. 
blame v. 
consult v. 
direct adv. 
odd adj. 
reflect v. 
advantage n. 
mighty adj. 
dawdle v. 
chug v. 
lodge v. 
complaint n. 
triumph n. 
asterisk n. *
conduct v. 
1179030117
** Lesson 38 The first calender
What is the importance of the dots, lines, and symbols engraved on some,
bones and ivory?
Future historians will be in a unique position when they come to record
the history of our own times. They will hardly know which facts to
select from the great mass of evidence that steadily accumulates. What
is more, they will not have to rely solely on the written word. Films,
videos, CDs and CD-ROMS are just some of the bewildering amount of
information they will have. They will be able, as it were, to see and
hear us in action. But the historian attempting to reconstruct the
distant past is always faced with a difficult task. He has to deduce
what he can from the few scanty clues available. Even seemingly
insignificant remains can shed interesting light on the history of early
man.
Up to now, historians have assumed that calendars came into being with
the advent of agriculture, for then man was faced with a real need to
understand something about the seasons. Recent scientific evidence seems
to indicate that this assumption is incorrect.
Historians have long been puzzled by dots, lines and symbols which have
been engraved on walls, bones, and the ivory tusks of mammoths. The
nomads who made these markings lived by hunting and fishing during the
last Ice Age which began about 35,000 B.C. and ended about 10,000 B.C.
By correlating markings made in various parts of the world, historians
have been able to read this difficult code. They have found that it is
connected with the passage of days and the phases of the moon. It is, in
fact, a primitive type of calendar. It has long been known that the
hunting scenes depicted on walls were not simply a form of artistic
expression. They had a definite meaning, for they were as near as early
man could get to writing. It is possible that there is a definite
relation between these paintings and the markings that sometimes
accompany them. It seems that man was making a real effort to understand
the seasons 20,000 years earlier than has been supposed.
calendar n. 
historian n. 
unique adj. 
steadily adv. 
solely adv. 
video n. 
bewilder v. 
deduce v. 
scanty adj. 
clue n. 
insignificant adj. 
shed v. 
advent n. 
agriculture n. 
assumption n. 
dot n. 
symbol n. 
engrave v. 
ivory n. 
mammoth n. 
tusk n. 
nomad n. 
correlate v. 
phase n. 
primitive adj. 
depict v. 
350001000020,000
** Lesson 39 Nothing to worry about
What was the difference between Bruce's behaviour and that of other
people?
The rough across the plain soon became so bad that we tried to get Bruce
to drive back to the village we had come from. Even though the road was
littered with boulders and pitted with holes, Bruce was not in the least
perturbed. Glancing at his map, he informed us that the next village was
a mere twenty miles away. It was not that Bruce always underestimated
difficulties. He simply had no sense of danger at all. No matter what
the conditions were, he believed that a car should be driven as fast as
it could possibly go.
As we bumped over eh dusty track, we swerved to avoid large boulders.
The wheels scooped up stones which hammered ominously under the car. We
felt sure that sooner or later a stone would rip a hole in our petrol
tank or damage the engine. Because of this, we kept looking back,
wondering if we were leaving a trail of oil and petrol behind us.
What a relief it was when the boulders suddenly disappeared, giving way
to a stretch of plain where the only obstacles were clumps of bushes.
But there was worse to come. Just ahead of us there was a huge fissure.
In response to renewed pleadings, Bruce stopped. Though we all got out
to examine the fissure, he remained in the car. We informed him that the
fissure extended for fifty years and was tow feet wide and four feet
deep. Even this had no effect. Bruce went into a low gear and drove at a
terrifying speed, keeping the front wheels astride the crack as he
followed its zigzag course. Before we had time to worry about what might
happen, we were back on the plain again. Bruce consulted the map once
more and told us that the village was now only fifteen miles away. Our
next obstacle was a shallow pool of water about half a mile across.
Bruce charged at it, but in the middle, the car came to a grinding half.
A yellow light on the dashboard flashed angrily and Bruce cheerfully
announced that there was no oil in the engine!
rough adj. 
boulder n. 
pit v. 
perturb v. 
underestimate v. 
swerve v. 
scoop v. 
hammer v. 
ominously adv. 
rip v. 
petrol n. 
stretch n. 
obstacle n. 
clump n. 
fissure n. 
renew v. 
pleading n. 
gear n. 
astride prep.
crack n. 
zigzag n. 
shallow adj. 
grind (ground, ground) v. 
halt n. 
dashboard n. 
20
502415
** Lesson 40 Who's who
How did the policeman discover that the whole thing was a joke?
It has never been explained why university students seem to enjoy
practical jokes more than else. Students specialize in a particular type
of practical joke: the hoax. Inviting the fire brigade to put out a
nonexistent fire is a crude form of deception which no self-respecting
student would ever indulge in. Students often create amusing situations
which are funny to everyone except the victims.
When a student recently saw two workmen using a pneumatic drill outside
his university, he immediately telephoned the police and informed them
that two students dressed up as workmen were tearing up the road with a
pneumatic drill. As soon as he had hung up, he went over to the workmen
and told them that if a policeman ordered them to go away, they were not
take him seriously. He added that a student had dressed up as a
policeman and was playing all sorts of silly jokes on people. Both the
police and the workmen were grateful to the student for this piece of
advance information.
The student did in an archway nearby where he could watch and hear
everything that went on. Sure enough, a policeman arrived on the scene
and politely asked the workmen to go away. When he received a very rude
reply from one of the workmen. He threatened to remove them by force.
The workmen told him to do as he pleased and the policeman telephoned
for help. Shortly afterwards, four more policemen arrived and
remonstrated with the workmen. As the men refused to stop working, the
police attempted to seize the pneumatic drill. The workmen struggled
fiercely and one of them lost his temper. He threatened to call the
police. At this, the police pointed out ironically that this would
hardly be necessary as the men were already under arrest. Pretending to
speak seriously, one of the workmen asked if he might make a telephone
call before being taken to the station. Permission was granted and a
policeman accompanied him to a pay phone. Only when he saw that the man
was actually telephoning the police did he realize that they had all
been the victims of a hoax.
hoax n. 
deception n. 
self-respecting adj. 
indulge v. 
pneumatic adj. 
drill n. 
silly adj. 
advance adj. 
archway n. 
remonstrate v. 
ironically adv. 
permission n. 
grant v. 
------
4
** Lesson 41 Illusions of Pastoral peace
What particular anxiety spoils the country dweller's visit to the
theatre?
The quiet life of the country ahs never appealed to me. City born and
city bred. I have always regarded the country as something you look at
through a train window, or something you occasional visit during the
weekend. Most of my friends live in the city, yet they always go into
raptures at the mere mention of the country. Though they extol the
virtues of the peaceful life, only one of hem has ever gone to live in
the country and he was back in town within six months. Even he still
lives under the illusion that country life is somehow superior to town
life. He is forever talking about the friendly people, the clean
atmosphere, the closeness to nature and the gentle pace of living.
Nothing can be compared, he maintains, with the first cockcrow, the
twittering of birds at dawn, the sight of the rising sun glinting on the
trees and pastures. This idyllic pastoral scene is only part of the
picture. My friend fails to mention the long and friendless winter
evenings in front of the TV -- virtually the only form of entertainment.
He says nothing about the poor selection of goods in the shops, or about
those unfortunate people who have to travel from the country to the city
every day to get to work. Why people are prepared to tolerate a
four-hour journey each day for the dubious privilege of living in the
country is beyond me. They could be saved so much misery and expense if
they chose to live in the city where they rightly belong.
If you can do without the few pastoral pleasures of the country, you
will find the city can provide you with the best that life can offer.
You never have to travel miles to see your friends. They invariably lie
nearby and are always available for an informal chat or an evening's
entertainment. Some of my acquaintances in the country come up to town
once or twice a year to visit the theatre as a special treat. For them
this is a major operation which involves considerable planning. As the
play draws to its close, they wonder whether they will ever catch that
last train home. The cit dweller never experiences anxieties of this
sort. The latest exhibitions, films, or plays are only a short bus ride
away. Shopping, too, is always a pleasure. The latest exhibitions,
films, or plays are only a short bus ride away. Shopping, too, is always
a pleasure. There is so much variety that you never have to make do with
second best. Country people run wild when they go shopping in the city
and stagger home loaded with as many of the exotic items as they can
carry. Nor is the city without its moments of beauty. There is something
comforting about the warm glow shed by advertisements on cold wet winter
nights. Few things could be more impressive than the peace that descends
on deserted city streets at weekends when the thousands that travel to
work every day are tucked away in their homes in the country. It has
always been a mystery to me who city dwellers, who appreciate all these
things, obstinately pretend that they would prefer to live in the
country.
illusion n. 
pastoral adj. 
breed (bred, bred) v. 
rapture n. 
extol v. 
superior adj. 
cockcrow n. 
twitter v. 
glint v. 
pasture n. 
idyllic adj. 
virtually adv. 
dubious adj. 
privilege n. 
misery n. 
acquaintance n. 
treat n. 
dweller n. 
stagger v. 
exotic adj. 
glow n. 
descend v. 
descend v. 
obstinately adv. 
6------4
** Lesson 42 Modern cavemen
With what does the writer compare the Gouffre Berger?
Cave exploration, or pot-holing, as it has come to be known, is a
relatively new sport. Perhaps it is the desire for solitude or the
chance of making an unexpected discovery that lures people down to the
depths of the earth. It is impossible to give a satisfactory explanation
for a pot-holer's motives. For him, caves have the same peculiar
fascination which high mountains have for the climber. They arouse
instincts which can only be dimly understood.
Exploring really deep caves is not a task for the Sunday afternoon
rambler. Such undertakings require the precise planning and foresight of
military operations. It can take as long as eight days to rig up rope
ladders and to establish supply bases before a descent can be made into
a very deep cave. Precautions of this sort are necessary, for it is
impossible to foretell the exact nature of the difficulties which will
confront the pot-holer. The deepest known cave in the world is the
Gouffre Berger near Grenoble. It extends to a depth of 3,723 feet. This
immense chasm has been formed by an underground stream which has
tunneled a course through a flaw in the rocks. The entrance to the cave
is on a plateau in the Dauphine Alps. As it is only six feet across, it
is barely noticeable. The cave might never have been discovered has not
the entrance been spotted by the distinguished French pot-holer, Berger.
Since its discovery, it has become a sort of potholers' Everest. Though
a number of descents have been made, much of it still remains to be
explored.
A team of pot-holers recently went down the Gouffre Berger. After
entering the narrow gap on the plateau, they climbed down the steep
sides of the cave until they came to narrow corridor. They had to edge
their way along this, sometimes wading across shallow streams, or
swimming across deep pools. Suddenly they came to a waterfall which
dropped into an underground lake at the bottom of the cave. They plunged
into the lake, and after loading their gear on an inflatable rubber
dinghy, let the current carry them to the other side. To protect
themselves from the icy water, they had to wear special rubber suits. At
the far end of the lake, they came to huge piles of rubble which had
been washed up by the water. In this part of the cave, they could hear
an insistent booming sound which they found was caused by a small
waterspout shooting down into a pool from the roof of the cave.
Squeezing through a cleft in the rocks, the pot-holers arrived at an
enormous cavern, the size of a huge concert hall. After switching on
powerful arc lights, they saw great stalagmites -- some of them over
forty feet high -- rising up like tree-trunks to meet the stalactites
suspended from the roof. Round about, piles of limestone glistened in
all the colours of the rainbow. In the eerie silence of the cavern, the
only sound that could be heard was made by water which dripped
continuously from the high dome above them.
caveman n. 
pot-holing n. 
solitude n. 
lure v. 
pot-holer n. 
undertaking n. 
foresight n. 
foretell v. 
Grenoble n. 
chasm n. 
flaw n. 
distinguished adj. 
Everest n. 
wade v. 
waterfall n. 
gear n. 
inflatable adj. 
rubble n. 
insistent adj. 
boom v. 
waterspout n. 
cleft n. 
cavern n. 
stalagmite n. 
stalactite n. 
limestone n. 
glisten v. 
cerie adj. 
dome n. 
------------
8.3,7236
.40
** Lesson 43 Fully insured
Who owned the pie and why?
Insurance companies are normally willing to insure anything. Insuring
public or private property is a standard practice in most countries in
the world. If, however, you were holding an open air garden party or a
fete it would be equally possible to insure yourself in the event of bad
weather. Needless to say, the bigger the risk an insurance company
takes, the higher the premium you will have to pay. It is not uncommon
to hear that a shipping company has made a claim for cost of salvaging a
sunken ship. But the claim made by a local authority to recover the cost
of salvaging a sunken pie dish must surely be unique.
Admittedly it was an unusual pie dish, for it was eighteen feet long and
six feet wide. It had been purchased by a local authority so that an
enormous pie could be baked for an annual fair. The pie committee
decided that the best way to transport the dish would be by canal, so
they insured it for the trip. Shortly after it was launched, the pie
committee went to a local inn to celebrate. At the same time, a number
of teenagers climbed on to the dish and held a little party of their
own. Dancing proved to be more than the dish could bear, for during the
party it capsized and sank in seven feet of water.
The pie committee telephoned a local garage owner who arrived in a
recovery truck to salvage the pie dish. Shivering in their wet clothes,
the teenagers looked on while three men dived repeatedly into the water
to locate the dish. They had little difficulty in finding it, but
hauling it out of the water proved to be a serious problem. The sides of
the dish were so smooth that it was almost impossible to attach hawsers
and chains to the rim without damaging it. Eventually chains were fixed
to one end of the dish and a powerful winch was put into operation. The
dish rose to the surface and was gently drawn towards the canal bank.
For one agonizing moment, the dish was perched precariously on the bank
of the canal, but it suddenly overbalanced and slid back into the water.
The men were now obliged to try once more. This time they fixed heavy
metal clamps to both sides of the dish so that they could fasten the
chains. The dish now had to be lifted vertically because one edge was
resting against the side of the canal. The winch was again put into
operation and one of the men started up the truck. Several minutes
later, the dish was again put into operation and one of the water. Water
streamed in torrents over its sides with such force that it set up a
huge wave in the canal. There was danger that the wave would rebound off
the other side of the bank and send the dish plunging into the water
again. By working at tremendous speed, the men managed to get the dish
on to dry land before the wave returned.
admittedly adv. 
purchase v. 
annual adj. 
teenager n. 1319
capsize v. 
shiver v. 
dive v. 
haul v. 
hawser n. 
rim n. 
winch n. 
agonizing adj. 
perch v. 
precariously adv. 
overbalance v. 
clamp n. 
vertically adv. 
torrent n. 
rebound v. 
1867
3
** Lesson 44 Speed and comfort
Which type of transport does the writer prefer, do you think?
People travelling long distances frequently have to decide whether they
would prefer to go by land, sea, or air. Hardly anyone can positively
enjoy sitting in a train for more than a few hours. Train compartments
soon get cramped and stuffy. It is almost impossible to take your mind
off the journey. Reading is only a partial solution, for the monotonous
rhythm of the wheels clicking on the rails soon lulls you to sleep.
During the day, sleep comes in snatches. At night, when you really wish
to go to sleep, you rarely manage to do so. If you are lucky enough to
get a sleeper, you spend half the night staring at the small blue light
in the ceiling, or fumbling to find you ticket for inspection.
Inevitably you arrive at your destination almost exhausted. Long car
journeys are even less pleasant, for it is quite impossible even to
read. On motorways you can, at least, travel fairly safely at high
speeds, but more often than not, the greater part of the journey is
spent on roads with few service stations and too much traffic. By
comparison, ferry trips or cruises offer a great variety of civilized
comforts. You can stretch your legs on the spacious decks, play games,
meet interesting people and enjoy good food -- always assuming, of
course, that the sea is calm. If it is not, and you are likely to get
seasick, no form of transport could be worse. Even if you travel in
ideal weather, sea journeys take a long time. Relatively few people are
prepared to sacrifice holiday time for the pleasure of travlling by sea.
Aeroplanes have the reputation of being dangerous and even hardened
travellers are intimidated by them. They also have the disadvantage of
being an expensive form of transport. But nothing can match them for
speed and comfort. Travelling at a height of 30,000 feet, far above the
clouds, and at over 500 miles an hour is an exhilarating experience. You
do not have to devise ways of taking your mind off the journey, for an
aeroplane gets you to your destination rapidly. For a few hours, you
settle back in a deep armchair to enjoy the flight. The real escapist
can watch a film and sip champagne on some services. But even when such
refinements are not available, there is plenty to keep you occupied. An
aeroplane offers you an unusual and breathtaking view of the world. You
soar effortlessly over high mountains and deep valleys. You really see
the shape of the land. If the landscape is hidden from view, you can
enjoy the extraordinary sight of unbroken cloud plains that stretch out
for miles before you, while the sun shines brilliantly in a clear sky.
The journey is so smooth that there is nothing to prevent you from
reading or sleeping. However you decide to spend your time, one thing is
certain: you will arrive at your destination fresh and uncrumpled. You
will not have to spend the next few days recovering from a long and
arduous journey.
positively adv. 
compartment n. 
cramped adj. 
stuffy adj. 
monotonous adj. 
rhythm n. 
click v. 
lull v. 
snatch n. 
sleeper n. 
fumble v. 
inspection n. 
inevitably adv. 
destination n. 
exhaust v. 
motorway n. 
ferry n. 
cruise n. 
civilize v. 
spacious adj. 
seasick adj. 
intimidate v. 
disadvantage n. 
exhilarating adj. 
escapist n. 
sip v. 
champagne n. 
refinement n. 
breathtaking adj.
soar v. 
effortlessly adv. 
landscape n. 
fresh adj. 
uncrumpled adj. 
------
30000
500
** Lesson 45 The power of the press
Does the writer think the parents where lucky or unlucky to gain
prosperity in this way? Why?
In democratic countries any efforts to restrict the freedom of the press
are rightly condemned. However, this freedom can easily be abused.
Stories about people often attract far more public attention than
political events. Though we may enjoy reading about the lives of others,
it is extremely doubtful whether we would equally enjoy reading about
ourselves. Acting on the contention that facts are sacred, reporters can
cause untold suffering to individuals by publishing details about their
private lives. Newspapers exert such tremendous influence that they can
not only bring about major changes to the lives of ordinary people but
can even overthrow a government.
The story of a poor family that acquired fame and fortune overnight,
dramatically illustrates the power of the press. The family lived in
Aberdeen, a small town of 23,000 inhabitants in South Dakota. As the
parents had five children, life was a perpetual struggle against
poverty. They were expecting their sixth child and were faced with even
more pressing economic problems. If they had only had one more child,
the fact would have passed unnoticed. They would have continued to
struggle against economic odds and would have lived in obscurity. But
they suddenly became the parents of quintuplets, an aeroplane arrived in
Aberdeen bringing sixty reporters and photographers.
The rise to fame was swift. Television cameras and newspapers carried
the news to everyone in the country. Newspapers and magazines offered
the family huge sums for the exclusive rights to publish stories and
photographs. Gifts poured in not only from unknown people, but room baby
food and soap manufacturers who wished to advertise their products. The
old farmhouse the family lived in was to be replaced by new $500,000
home. Reporters kept pressing for interviews so lawyers had to be
employed to act as spokesmen for the family at press conferences. While
the five babies were babies were still quietly sleeping in oxygen tents
in hospital nursery, their parents were paying the price for fame. It
would never again be possible for them to lead normal lives. They had
become the victims of commercialization, for their names had acquired a
market value. Instead of being five new family members, these children
had immediately become a commodity.
democratic adj. 
restrict v. 
abuse v. 
contention n. 
untold adj. 
South Dakota
perpetual adj. 
quintuplet n. 
obscurity n. 
radically adv. 
exclusive adj. 
nursery n. 
commercialization n. 
commodity n. 
23000
5614160
505
** Lesson 46 Do it yourself
Did the writer repair his lawn mower in the end? Why/Why not?
So great is our passion for doing things for ourselves, that we are
becoming increasingly less dependent on specialized labour. No one can
plead ignorance of a subject any longer, for these are countless
do-it-yourself publications. Armed with the right tools and materials,
newlyweds gaily embark on the task of decorating their own homes. Men,
particularly, spend hours of their leisure time installing their own
fireplaces, laying out their own gardens; building garages and making
furniture. Some really keen enthusiasts go so far as to build their own
computers. Shops cater for the do-it-yourself craze not only by running
special advisory services for novices, but by offering consumers bits
and pieces which they can assemble at home. Such things provide an
excellent outlet for pent up creative energy, but unfortunately not all
of us are born handymen.
Some wives tend to believe that their husbands are infinitely
resourceful and can fix anything. Even men who can hardly drive a nail
in straight are supposed to be born electricians, carpenters, plumbers
and mechanics. When lights fuse, furniture gets rickety, pipes get
clogged, or vacuum cleaners fail to operate, some woman assume that
their husbands will somehow put things right. The worst thing about the
do-it-yourself game is that sometimes even men live under the delusion
that they can do anything, even when they have repeatedly been proved
wrong. It is a question of pride as much as anything else.
Last spring my wife suggested that I call in a man to look at our lawn
mower. It had broken down the previous summer, and though I promised to
repair it, I had never got round to it. I would not hear of the
suggestion and said that I would fix it myself. One Saturday afternoon,
I hauled the machine into the garden and had a close look at it. As far
as I could see, it needed only a minor adjustment: a turn of a screw
here, a little tightening up there, a drop of oil and it would be as
good as new. Inevitably the repair job was not quite so simple. The
mower firmly refused to mow, so I decided to dismantle it. The garden
was soon littered with chunks of metal which had once made up a lawn
mower. But I was extremely pleased with myself. I had traced the cause
of the trouble. One of links in the chain that drives the wheels had
snapped. After buying a new chain I was faced with the insurmountable
task of putting the confusing jigsaw puzzle together again. I was not
surprised to find that the machine still refused to work after I had
reassembled it, for the simple reason that I was left with several
curiously shaped bits of metal which did not seem to fit anywhere. I
gave up in despair. The weeks passed and the grass grew. When my wife
nagged me to do something about it, I told her that either I would have
to buy a new mower or let the grass grow. Needless to say our house is
now surrounded by a jungle. Buried somewhere in deep grass there is a
rusting lawn mower which I have promised to repair one day.
plead v. 
ignorance n. 
publication n. 
newlyweds n. 
gaily adv. 
leisure n. 
keen adj. 
advisory adj. 
novice n. 
consumer n. 
assemble v. 
outlet n. 
creative adj. 
handyman n. 
resourceful adj. 
fuse v. 
rickety adj. 
clog v. 
delusion n. 
lawn mower
adjustment n. 
screw n. 
dismantle v. 
chunk n. 
snap v. 
insurmountable adj. 
jigsaw n. 
nag v. 
rust v. 
** Lesson 47 Too high a price?
What does the writer describe as an 'amusing old-fashioned source of
noise'?
Pollution is the price we pay for an overpopulated, over industrialized
planet. When you come to think about it, there are only four ways you
can deal with rubbish: dump it, burn it, turn it into something you can
use again, attempt to produce less of it. We keep trying all four
methods, but he sheer volume of rubbish we produce worldwide threatens
to overwhelm us.
Rubbish, however, is only part of the problem of polluting our planet.
The need to produce ever-increasing quantities of cheap food leads to a
different kind of pollution. Industrialized farming methods produce
cheap meat products: beef, pork and chicken. The use of pesticides and
fertilizers produces cheap grain and vegetables. The price we pay for
cheap food may be already too high: Mad Cow Disease (BSE) in cattle,
salmonella in chicken and eggs, and wisteria in dairy products. And if
you think you'll abandon meat and become a vegetarian, you have the
choice of very expensive organically-grown vegetables or a steady diet
of pesticides every time you think you're eating fresh salads and
vegetables, or just having an innocent glass of water!
However, there is an even more insidious kind of pollution that
particularly affects urban areas and invades our daily lives, and that
is noise. Burglar alarms going off at any time of the day or night serve
only to annoy passers-by and actually assist burglars to burgle. Car
alarms constantly scream at us in the street and are a source of
profound irritation. A recent survey of the effects of noise revealed
(surprisingly?) that dogs barking incessantly in the night rated the
highest form of noise pollution on a scale ranging from 1 to 7. The
survey revealed a large number of sources of noise that we really
dislike. Lawn mowers whining on a summer's day, late-night parties in
apartment blocks, noisy neighbors, vehicles of al kinds, especially
large container trucks thundering through quiet village, planes and
helicopters flying overhead, large radios carried round in public places
and played at maximum volume. New technology has also made its own
contribution to noise. A lot of people object to mobile phones,
especially when they are used in public places like restaurants or on
public transport. Loud conversations on mobile phones invade our
thoughts or interrupt the pleasure of meeting friends for a quiet chat.
The noise pollution survey revealed a rather spurring and possibly
amusing old fashioned source of noise. It turned out to be snoring! Men
were found to be the worst offenders. It was revealed that 20% of men in
their mid-thirties snore. This figure rises to a staggering 60% of men
in their sixties. Against these figures, it was found that only 5% of
women snore regularly, while the rest are constantly woken or kept awake
by their trumpeting partners. Whatever the source of noise, one thing is
certain: silence, it seems, has become a golden memory.
pollution n. 
overpopulated adj. 
over-industrialized adj. 
sheer adj. 
worldwide adv. 
overwhelm v. 
pollute v. 
pesticide n. 
fertilizer n. 
salmonella n. 
listeria n. 
vegetarian n. 
organically-grown adj. 
insidious adj. 
urban adj. 
burglar n. 
burgle v. 
scream v. 
profound adj. 
irritation n. 
incessantly adv. 
whine v. 
helicopter n. 
maximum adj. 
technology n. 
contribution n. 
mobile adj. 
snore v. 
offender v. 
staggering adj. 
trumpet v. 
partner n. 
44
------
1720%356060%5%
** Lesson 48 The silent village
Why was the village silent?
In this much-travelled world, there are still thousands of places which
are inaccessible to tourists. We always assume that villagers in remote
places are friendly and hospitable. But people who are cut off not only
from foreign tourists, but even from their own countrymen can be hostile
to travellers. Visits to really remote villages are seldom enjoyable --
as my wife and I discovered during a tour through the Balkans.
We had spent several days in a small town and visited a number of old
churches in the vicinity. These attracted many visitors, for they were
not only of great architectural interest, but contained a large number
of beautifully preserved frescoes as well. On the day before our
departure, several bus loads of tourists descended on the town. This was
more than we could bear, so we decided to spend our last day exploring
the countryside. Taking a path which led out of the town, we crossed a
few fields until we came to a dense wood. We expected the path to end
abruptly, but we found that it traced its way through the trees. We
tramped through the wood for over two hours until we arrived at a deep
stream. We could see that the path continued on the other side, but we
had no idea how we could get across the stream. Suddenly my wife spotted
a boat moored to the bank. In it there was a boatman fast asleep. We
gently woke him up and asked him to ferry us to the other side. Though
he was reluctant to do so at first, we eventually persuaded him to take
us.
The path led to a tiny village perched on the steep sides of a mountain.
The place consisted of a straggling unmade road which was lined on
either side by small houses. Even under a clear blue sky, the village
looked forbidding, as all the houses were built of grey mud bricks. The
village seemed deserted, the only sign of life being an ugly-looking
black goat on a short length of rope tied to a tree in a field nearby.
Sitting down on a dilapidated wooden fence near the field, we opened a
couple of tins of sardines and had a picnic lunch. All at once, I
noticed that my wife seemed to be filled with alarm. Looking up I saw
that we were surrounded by children in rags who were looking at us
silently as we ate. We offered them food and spoke to them kindly, but
they remained motionless. I concluded that they were simply shy of
strangers. When we later walked down the main street of the villager, we
were followed by a silent procession of children. The village which had
seemed deserted, immediately came to life. Faces appeared at windows.
Men in shirt sleeves stood outside their houses and glared at us. Old
women in black shawls peered at us from doorways. The most frightening
thing of all was that not a sound could be heard. There was no doubt
that we were unwelcome visitors. We needed no further warning. Turning
back down the main street, we quickened our pace and made our way
rapidly towards the stream where we hoped the boatman was waiting.
inaccessible adj. ,
hospitable adj. 
hostile adj. ,
vicinity n. ,
architectural adj. 
fresco n. 
abruptly adv. ,
tramp v. 
moor v. 
ferry v. 
straggle v. 
sardine n. 
rag n. 
procession adj. 
shawl n. 
peer v. 
quicken v. 
* Unit 4
** Lesson 49 The ideal servant
It is a good thing my aunt Harriet died years ago. If she were alive
today she would not be able to air her views on her favourite topic of
conversation: domestic servants. Aunt Harriet lived in that leisurely
age when servants were employed to do housework. She had a huge,
rambling country house called 'The Gables'. She was sentimentally
attached to this house, for even though it was far too big for her
needs, she persisted in living there long after her husband's death.
Before she grew old, Aunt Harriet used to entertain lavishly. I often
visited The Gables when I was boy. No matter how many guests were
present, the great house was always immaculate. The parquet floors shone
like mirrors; highly polished silver was displayed in gleaming glass
cabinets; even my uncle's huge collection of books was kept miraculously
free from dust. Aunt Harriet presided over an invisible army of servants
that continuously scrubbed, cleaned, and polished. She always referred
to them as 'the shifting population', for they came and went with such
frequency that I never even got a chance to learn their names. Though my
aunt pursued what was, in those days, an enlightened policy, in that she
never allowed her domestic staff to work more than eight hours a day,
she was extremely difficult to please. While she always criticized the
fickleness of human nature, she carried on an unrelenting search for the
ideal servant to the end of her days, even after she had been sadly
disillusioned by Bessie.
Bessie worked for Aunt Harriet for three years. During that time she so
gained my aunt's confidence that she was put in charge of the domestic
staff. Aunt Harriet could not find words to praise Bessie's
industriousness and efficiency. In addition to all her other
qualifications, Bessie was an expert cook. She acted the role of the
perfect servant for three years before Aunt Harriet discovered her
'little weakness'. After being absent from the Gables for a week, my
aunt unexpectedly returned one afternoon with a party of guests and
instructed Bessie to prepare dinner. No only was the meal well below the
usual standard, but Bessie seemed unable to walk steadily. She bumped
into the furniture and kept mumbling about the guests. When she came in
with the last course -- a huge pudding -- she tripped on the carpet and
the pudding went flying through the air, narrowly missed my aunt, and
crashed on the dining table with considerable force. Though this caused
great mirth among the guests, Aunt Harriet was horrified. She
reluctantly came to the conclusion that Bessie was drunk. The guests
had, of course, realized this from the moment Bessie opened the door for
them and, long before the final catastrophe, had had a difficult time
trying to conceal their amusement. The poor girl was dismissed
instantly. After her departure, Aunt Harriet discovered that there were
piles of empty wine bottles of all shapes and sizes neatly stacked in
what had once been Bessie's wardrobe. They had mysteriously found their
way there from the wine cellar!
rambling adj. 
sentimentally adv. 
immaculate adj. 
lavishly adv. 
parquet n. 
gleam v. 
preside v. 
invisible adj. 
scrub v. 
enlightened adj. 
fickleness n. 
unrelenting adj. 
disillusion v. 
qualification n. 
mirth n. 
stack v. 
cellar n. 
8
33------------
** Lesson 50 New Year resolutions
What marked the end of the writer's New Year resolutions?
The New Year is a time for resolutions. Mentally, at least, most of us
could compile formidable lists of 'dos' and 'don'ts'. The same old
favorites recur year in year out with monotonous regularity. We resolve
to get up earlier each morning, eat less, find more time to play with
the children, do a thousand and one jobs about the house, be nice to
people we don't' like, drive carefully, and take the dog for a walk
every day. Past experience has taught us that certain accomplishments
are beyond attainment. If we remain inveterate smokers, it is only
because we have so often experienced the frustration that results from
failure. Most of us fail in our efforts at self-improvement because our
schemes are too ambitious and we never have time to carry them out. We
also make the fundamental error of announcing our resolutions to
everybody so that we look even more foolish when we slip back into our
bad old ways. Aware of these pitfalls, this year I attempted to keep my
resolutions to myself. I limited myself to two modest ambitions: to do
physical exercise every morning and to read more of an evening. An
all-night party on New Year's Eve provided me with a good excuse for not
carrying out either of these new resolutions on the first day of the
year, but on the second, I applied myself assiduously to the task.
The daily exercises lasted only eleven minutes and I proposed to do them
early in the morning before anyone had got up. The self-discipline
required to drag myself out of bed eleven minutes earlier than usual was
considerable. Nevertheless, I managed to creep down into the living room
for two days before anyone found me out. After jumping about on the
carpet and twisting the human frame into uncomfortable positions, I sat
down at the breakfast table in an exhausted condition. It was this that
betrayed me. The next morning the whole family trooped in to watch the
performance. That was really unsettling, but I fended off the taunts and
jibes of the family good-humouredly and soon everybody got used to the
idea. However, my enthusiasm waned. The time I spent at exercises
gradually diminished. Little by little the eleven minutes fell to zero.
By January 10th, I was back to where I had started from. I argued that
if I spent less time exhausting myself at exercises in the morning, I
would keep my mind fresh for reading when I got home formwork Resisting
the hypnotizing effect of television, I sat in my room for a few
evenings with my eyes glued to book. One night, however, feeling cold
and lonely, I went downstairs and sat in front of the television
pretending to read. That proved to be my undoing, for I soon got back to
my old bad habit of dozing off in front of the screen. I still haven't
given up my resolution to do more reading. In fact, I have just bought a
book entitled How to Read a Thousand Words a Minute. Perhaps it will
solve my problem, but I just haven't had time to read it!
resolution n. 
mentally adv. 
compile v. 
formidable adj. 
recur v. 
regularity n. 
accomplishment n. 
attainment n. 
inveterate adj. 
self-improvement n. 
scheme n. 
ambitious adj. 
pitfall n. 
modest adj. 
assiduously adv. 
self-discipline n. 
frame n. 
betray v. 
troop v. 
unsettle v. 
taunt n. 
jibe n. 
good-humouredly adv. 
wane v. 
hypnotize v. 
undoing n. 
screen n. 
111111110
** Lesson 51 Predicting the future
What was the 'future' electronic development that Leon Bagrit wasn't
able to foresee?
Predicting the future is notoriously difficult. Who could have imagined,
in the mid 1970s, for example, that by the end of the 20th century,
computers would be as common in people's homes as TV sets? In the 1970s,
computers were common enough, but only in big business, government
departments, and large organizations. These were the so-called mainframe
machines. Mainframe computers were very large indeed, often occupying
whole air-conditioned rooms, employing full-time technicians and run on
specially-written software. Though these large machines still exist,
many of their functions have been taken over by small powerful personal
computers, commonly known as PCs.
In 1975, a primitive machine called the Altair, was launched in the USA.
It can properly be described as the first 'home computer' and it pointed
the way to the future. This was followed, at the end of the 1970s, by a
machine called an Apple. In the early 1980s, the computer giant, IBM
produced the world's first Personal Computer. This ran on an 'operating
system' called DOS, produced by a then small company named Microsoft.
The IBM Personal Computer was widely copied. From those humble
beginnings, we have seen the development of the user-friendly home
computers and multimedia machines which are in common use today.
Considering how recent these developments are, it is even more
remarkable that as long ago as the 1960s, an Englishman, Leon Bagrit,
was able to predict some of the uses of computers which we know today.
Bagrit dismissed the idea that computers would learn to 'think' for
themselves and would 'rule the world', which people liked to believe in
those days. Bagrit foresaw a time when computers would be small enough
to hold in the hand, when they would be capable of providing information
about traffic jams and suggesting alternative routes, when they would be
used in hospitals to help doctors to diagnose illnesses, when they would
relieve office workers and accountants of dull, repetitive clerical
work. All these computer uses have become commonplace. Of course, Leon
Bagrit could not possibly have foreseen the development of the Internet,
the worldwide system that enables us to communicate instantly with
anyone in any part of the world by using computers linked to telephone
networks. Nor could he have foreseen how we could use the Internet to
obtain information on every known subject, so we can read it on a screen
in our homes and even print it as well if we want to. Computers have
become smaller and smaller, more and more powerful and cheaper and
cheaper. This is what makes Leon Bagrit's predictions particularly
remarkable. If he, or someone like him, were alive today, he might be
able to tell us what to expect in the next fifty years.
notoriously adv. 
full-time adj. 
technician n. 
user-friendly adj. 
mainframe n. 
alternative adj. 
diagnose v. 
relieve v. 
accountant n. 
repetitive adj. 
clerical adj. 
20702070------PC------
19757080IBMDOSIBM
.60.------------.50
** Lesson 52 Mud is mud
Why did Harry decide to give up his little game?
My cousin, Harry, keeps a large curiously-shaped bottle on permanent
display in his study. Despite the fact that the bottle is tinted a
delicate shade of green, an observant visitor would soon notice that it
is filled with what looks like a thick, grayish substance. If you were
to ask Harry what was in the bottle, he would tell you that it contained
perfumed mud. If you expressed doubt or surprise, he would immediately
invite you to smell it and then to rub some into your skin. This brief
experiment would dispel any further doubts you might have. The bottle
really does contain perfumed mud. How Harry came into the possession of
this outlandish stuff makes an interesting story which he is fond of
relating. Furthermore, the acquisition of this bottle cured him of a bad
habit he had been developing for years.
Harry used to consider it a great joke to go into expensive cosmetic
shops and make outrageous requests for goods that do not exist. He would
invent fanciful names on the spot. On entering a shop, he would ask for
a new perfume called 'Scented Shadow' or for 'insoluble bath cubes'. If
a shop assistant told him she had not heard of it, he would pretend to
be considerably put out. He loved to be told that one of his imaginary
products was temporarily out of stock and he would faithfully promise to
call again at some future date, but of course he never did. How Harry
managed to keep a straight face during these performances is quite
beyond me.
Harry does not need to be prompted to explain how he bought his precious
bottle of mud. One day, he went to an exclusive shop in London and asked
for 'Myrolite', the shop assistant looked puzzled and Harry repeated the
word, slowly stressing each syllable. When the woman shook her head in
bewilderment, Harry went on to explain that 'myrolite' was a hard,
amber-like substance which could be used to remove freckles. This
explanation evidently conveyed something to the woman who searched shelf
after shelf. She produced all sorts of weird concoctions, but none of
them met with Harry's requirements. When Harry put on his act of being
mildly annoyed, the assistant promised to order some for him.
Intoxicated by his success, Harry then asked for perfumed mud. He
expected the assistant to look at him in blank astonishment. However, it
was his turn to be surprised, for the woman's eyes immediately lit up
and she fetched several bottles which she placed on the counter for
Harry to inspect. For once, Harry had to admit defeat. He picked up what
seemed to be the smallest bottle and discreetly asked the price. He was
glad to get away with a mere twenty pounds and he beat a hasty retreat,
clutching the precious bottle under his arm. From then on, Harry decided
that this little game he had invented might prove to be expensive. The
curious bottle, which now adorns the bookcase in his study, was his
first and last purchase of rare cosmetics.
permanent adj. 
tint v. ......
delicate adj. 
shade n. 
observant adj. 
dispel v. 
outlandish adj. 
acquisition n. 
cosmetic n. 
outrageous adj. 
fanciful adj. 
insoluble adj. 
prompt v. 
exclusive adj. 
syllable n. 
bewilderment n. 
freckle n. 
evidently adv. 
weird adj. 
concoction n. 
intoxicate v. 
blank adj. 
discreetly adv. 
clutch v. 
adorn v. 
20
** Lesson 53 In the public interest
What could not be reported in the official flees?
The Scandinavian countries are much admired all over the world for their
enlightened social policies. Sweden has evolved an excellent system for
protecting the individual citizen from highhanded or incompetent public
officers. The system has worked so well, that it has been adopted in
other countries too.
The Swedes were the first to recognize that public official like civil
servants, police officers, health inspectors or tax-collectors can make
mistakes or act over-zealously in the belief that they are serving the
public. As long ago as 1809, the Swedish Parliament introduced a scheme
to safeguard the interest of the individual. A parliamentary committee
representing all political parties appoints a person who is suitably
qualified to investigate private grievances against the State. The
official title of the person is 'Justiteombudsman', but the Swedes
commonly refer to him as the 'J.O.' or 'Ombudsman'. The Ombudsman is not
subject to political pressure. He investigates complaints large and
small that come to him from all levels of society. As complaints must be
made in writing, the Ombudsman receives an average of 1,200 letters a
year. He has eight lawyer assistants to help him and examines every
single letter in detail. There is nothing secretive about the
Ombudsman's work for his correspondence is open to public inspection. If
a citizen's complaint is justified, the Ombudsman will act on his
behalf. The action he takes varies according to the nature of the
complaint. He may gently reprimand an official or even suggest to
parliament that a law the altered. The following case is a typical
example of the Ombudsman's work.
A foreigner living in a Swedish village wrote to the Ombudsman
complaining that he had been ill-treated by the police, simply because
he was a foreigner. The Ombudsman immediately wrote to the Chief of
Police in the district asking him to send a record of the case. There
was nothing in the record to show that the foreigner's complaint was
justified and the Chief of Police strongly denied the accusation. It was
impossible for the Ombudsman to take action, but when he received a
similar complaint from another foreigner in the same village, he
immediately sent one of his layers to investigate the matter. The lawyer
ascertained that a policeman had indeed dealt roughly with foreigners on
several occasions. The fact that the policeman was prejudiced against
foreigners could not be recorded in the official files. It was only
possible for the Ombudsman to find this out by sending one of his
representatives to check the facts. The policeman in question was
severely reprimanded and was informed that if any further complaints
were lodged against him, he would prosecuted. The Ombudsman's prompt
action at once put an end to an unpleasant practice which might have
gone unnoticed.
evolve v. 
high-handed adj. 
incompetent adj. 
over-zealously adv. 
safeguard v. 
parliamentary adj. 
qalified adj. 
grievance n. 
Justiteombudsman n. 
ombudsman n. 
secretive adj. 
correspondence n. 
alter v. 
accusation n. 
ascertain v. 
prejudiced adj. 
prompt adj. 
1809J.O.1,2008
** Lesson 54 Instinct or cleverness?
Was the writer successful in protecting his peach tree? Why not?
We have been brought up to fear insects. We regard them as unnecessary
creatures that do more harm than good. We continually wage war on them,
for they contaminate our food, carry diseases, or devour our crops. They
sting or bite without provocation; they fly uninvited into our rooms on
summer nights, or beat ageist our lighted windows. We live in dread not
only of unpleasant insects like spiders or wasps, but of quite harmless
one like moths. Reading about them increases our understanding without
dispelling our fears. Knowing that the industrious ant lives in a highly
organized society does nothing to prevent us from being filled with
revulsion when we find hordes of them crawling over a carefully prepared
picnic lunch. No matter how much we like honey, or how much we have read
about the uncanny sense of direction which bees possess, we have a
horror of being stung. Most of our fears are unreasonable, but they are
impossible to erase. At the same time, however, insects are strangely
fascinating. We enjoy reading about them, especially when we find that,
like the praying mantis, they lead perfectly horrible lives. We enjoy
staring at them, entranced as they go about their business, unaware (we
hope) of our presence. Who has not stood in awe at the sight of a spider
pouncing on a fly, or a column of ants triumphantly bearing home an
enormous dead beetle?
Last summer I spent days in the garden watching thousands of ants
crawling up the trunk of my prize peach tree. The tree has grown against
a warm wall on a sheltered side of the house. I am especially proud of
it, not only because it has survived several severe winters, but because
it occasionally produces luscious peaches. During the summer, I noticed
tat the leaves of the tree were beginning to wither. Clusters of tin
insects called aphids were to be found on the underside of the leaves.
They were visited by a large colony of ants which obtained a sort of
honey from them. I immediately embarked on an experiment which, even
though if failed to get rid of the ants, kept me fascinated for
twenty-four hours. I bound the base of the tree with sticky tape, making
it impossible for the ants to reach the aphids. The tape was so stick
that they did not dare to cross it. For a long time. I watched them
scurrying around the base of the tree in bewilderment. I even went out
at midnight with a torch and noted with satisfaction (and surprise) that
the ants were still swarming around the sticky tape without being able
to do anything about it. I got up early next morning hoping to find that
the ants had given up in despair. Instead, I saw that they had
discovered a new route. They were climbing up the wall of the house and
then on to the leaves of the tree. I realized sadly that I had been
completely defeated by their ingenuity. The ants had been quick to find
an answer to my thoroughly unscientific methods!
insect n. 
wage v. 
contaminate v. 
provocation n. 
spider n. 
wasp n. 
moth n. 
ant n. 
revulsion n. 
horde n. 
uncanny adj. 
erase v. 
praying mantis 
entranced adj. 
beetle n. 
sheltered adj. 
luscious adj. 
cluster n. 
aphid n. 
underside n. 
colony n. 
sticky adj. 
scurry v. 
swarm v. 
ingenuity n. 
24
** Lesson 55 From the earth: Greetings
Which life forms are most likely to develop on a distant planet?
Recent developments in astronomy have made it possible to detect planets
in our won Milky Way and in other galaxies. This is a major achievement
because, in relative terms, planets are very small and old not emit
light. Finding planets is proving hard enough, but finding life on them
will prove infinitely more difficult. The first question to answer is
whether a planet can actually support life. In our won solar system, for
example, Venus is far too hot and Mars is far too cold to support life.
Only the Earth provides ideal conditions, and even here it has taken
more than four billion years for plant and animal life to evolve.
Whether a planet can support life depends on the size and brightness of
its star, that is its 'sun'. Imagine a star up t twenty times larger,
brighter, brighter and hotter than our own sun. A planet would have to
be a very long way from it to be capable of supporting life.
Alternatively, if the star were small, the life-supporting planet would
have to have a close orbit round it and also provide the perfect
conditions for life forms to develop. But how would we find such a
planet? At present, there is no telescope in existence that is capable
of detecting the presence of life. The development of such a telescope
will be one of the great astronomical projects of the twenty-first
century.
It is impossible to look for life on another planet using earth-based
telescopes. Our own warm atmosphere and the heat generated by the
telescope would make it impossible to detect objects as small as
planets. Even a telescope in orbit round the earth, like the very
successful Hubble telescope, would not be suitable because of the dust
particles iron solar system. A telescope would have to be as far away as
the planet Jupiter to look for life in outer space, because the dust
becomes thinner the further we travel towards the outer edges of our own
solar system. Once we detected a planet, we would have to find a way of
blotting out the light from its star, so that we would be able to 'see'
the planet properly and analyze its atmosphere. In the first instance,
we would be looking for plant life, rather than 'little green men'. The
life forms most likely to develop on a planet would be bacteria. It is
bacteria that have generated the oxygen we breathe on earth. For most of
the earth's history they have been the only form of life on our planet.
As Earth-dwellers, we always cherish the hope that we will be visited by
little green men and that we will be able to communicate with them. But
this hope is always in the realms of science fiction. If we were able to
discover lowly forms of life like bacteria on another planet, it would
completely change our view of ourselves. As Daniel Goldin of NASA
observed, 'Finding life elsewhere would change everything. No human
endeavor or thought would be unchanged by it."
astronomy n. 
relative adj. 
infinitely adv. 
solar adj. 
Venus n. 
Mars n. 
orbit n. 
astronomical adj. 
generate v. 
particle n. 
Jupiter n. 
blot v. 
analyse v. 
bacteria n. 
oxygen n. 
realm n. 
endeavour v. 
40
------------2021
------------.
** Lesson 56 Our neighbour, the river
Why had the neighbours left their farm?
The river which forms the eastern boundary of our farm has always played
an important part in our lives. Without it we could not make a living.
There is only enough spring water to supply the needs of the houses, so
we have to pump from the river for farm use. We tell river all our
secrets. We know instinctively, just as beekeepers with their bees, that
misfortune might overtake us if the important events of our lives were
not related to it.
We have special river birthday parties in the summer. Sometimes were go
upstream to a favourite backwater, sometimes we have our party at the
boathouse, which a predecessor of ours at the farm built in the meadow
hard by the deepest pool for swimming and diving. In a heat wave we
choose a midnight birthday party and that is the most exciting of all.
We welcome the seasons by the riverside, crowning the youngest girl with
flowers in the spring, holding a summer festival on Midsummer Eve,
giving thanks for the harvest in the autumn, and throwing a holy wreath
into the current in the winter.
After a long period of rain the river may overflow its banks. This is a
rare occurrence as our climate seldom guest to extremes. We are lucky in
that only the lower fields, which make up a very small proportion of our
farm, are effected by flooding, but other farms are less favorably
sited, and flooding can sometimes spell disaster for their owners.
One had winter we watched the river creep up the lower meadows. All the
cattle had been moved into stalls and we stood to lose little. We were,
however, worried about our nearest neighbors, whose farm was low lying
and who were newcomers to the district. As the floods had put the
telephone out of order, we could not find out how they were managing.
From an attic window we could get a sweeping view of the river where
their land joined ours, and at the most critical juncture we took turns
in watching that point. The first sign of disaster was a dead sheep
floating down. Next came a horse, swimming bravely, but we were afraid
that the strength of the current would prevent its landing anywhere
before it became exhausted. Suddenly a raft appeared, looking rather
like Noah's ark, carrying the whole family, a few hens, the dogs, cat,
and bird in a cage. We realized that they must have become unduly
frightened by the rising flood, for their house, which had sound
foundations, would have stood stoutly even if it had been almost
submerged. The men of our family waded down through our flooded meadows
with boathooks, in the hope of being able to grapple a corner of the
raft and pull it out of the current towards our bank. We still think it
a miracle that they we able to do so.
boundary n. 
pump v. 
overtake v. 
backwater n. 
predecessor n. 
meadow n. 
crown v. ......
holly n. 
wreath n. 
occurrence n. 
proportion n. 
site v. 
spell v. 
stall n. 
attic n. 
sweeping adj. 
critical adj. 
juncture n. 
raft n. 
unduly adv. 
foundations n. 
stoutly adv. 
submerge v. 
grapple v. 
** Lesson 57 Back in the old country
Did the narrator find is mother's grave?
I stopped to let the car cool off and to study the map. I had expected
to be near my objective by now, but everything still seemed alien to me.
I was only five when my father had taken me abroad, and that we eighteen
years ago. When my mother had died after a tragic accident, he did not
quickly recover from the shock and loneliness. Everything around him was
full of her presence, continually reopening the wound. So he decided to
emigrate. In the new country he became absorbed in making a new life for
the two of us, so that he gradually ceased to grieve. He did not marry
again and I was brought up without a woman's care; but I lacked for
nothing, for he was both father and mother to me. He always meant to go
back on day, but not to stay. His roots and mine bad become too firmly
embedded in the new land. But he wanted to see the old folk again and to
visit my mother's grave. He became mortally ill a few months before we
had planned to go and, when he knew that he was dying, he made me
promise to go on my own.
I hired a car the day after landing and bought a comprehensive book of
maps, which I found most helpful on the cross-country journey, but which
I did not think I should need on the last stage. It was not that I
actually remembered anything at all. But my father had described over
and over again what we should see at every milestone, after leaving the
nearest town, so that I was positive I should recognize it as familiar
territory. Well, I had been wrong, for I was now lost.
I looked at the map and then at the millimeter. I had come ten miles
since leaving the town, and at this point, according to my father, I
should be looking at farms and cottages in a valley, with the spire of
the church of our village showing in the far distance. I could see no
valley, no farms, no cottages and no church spire -- only a lake. I
decided that I must have taken a wrong turning somewhere. So I drove
back to the town and began to retrace the route, taking frequent glances
at the map. I landed up at the same corner. The curious thing was that
the lake was not marked on the map. I left as if I had stumbled into a
nightmare country, as you sometimes do in dreams. And, as in a
nightmare, there was nobody in sight to help me. Fortunately for me, as
I was wondering what to do next, there appeared on the horizon a man on
horseback, riding in my direction. I waited till he came near, then I
asked him the way to our old village. He said that there was now no
village. I thought he must have misunderstood me, so I repeated its
name. This time he pointed to the lake. The village no longer existed
because it had been submerged, and all the valley too. The lake was not
a natural one, but a man-made reservoir.
alien adj. 
emigrate v. 
absorb v. 
embedded adj. 
mortally adv. 
comprehensive adj. 
milestone n. 
territory n. 
milometer n. 
spire n. 
retrace v. 
stumble v. 
horizon n. 
reservoir n. 
518
10
** Lesson 58 A spot of bother
What did the old lady find when she got home?
The old lady was glad to be back at the block of flats where she lived.
Her shopping had tired her and her basket ad grown heavier with every
step of the way home. In the life her thoughts were on lunch and a good
rest; but when she got out at her own floor, both were forgotten in her
sudden discovery that her front door was open. She was thinking that she
must reprimand her home help the next morning for such a monstrous piece
of negligence, when she remembered that she had gone shopping after the
home help had left and she knew that she had turned both keys in their
locks, She walked slowly into the hall and at once noticed that all the
room doors were open, yet following her regular practice she had shut
them before going out. Looking into the drawing room, she saw a scene of
confusion over by her writing desk. It was as clear as daylight then
that burglars had forced an entry during her absence. Her first impulse
was to go round all the rooms looking for the thieves, but then she
decided that at her age it might be more prudent to have someone with
her, so she went to fetch the porter from his basement. By this time her
legs were beginning to tremble, so she sat down and accepted a cup of
very strong tea, while he telephoned the police. Then, her composure
regained, she was ready to set off with the porter's assistance to
search for nay intruders who might still be lurking in her flat.
They went through the rooms, being careful to touch nothing, as they did
not want to hinder the police in their search for fingerprints. The
chaos was inconceivable. She had lived in the flat for thirty years and
was a veritable magpie at hoarding; and it seemed as though everything
she possessed had been tossed out and turned over and over. At least
sorting out the things she should have discarded years ago was now being
made easier for her. Then a police inspector arrived with a constable
and she told them of her discovery of the ransacked flat. The inspector
began to look for fingerprints, while the constable checked that the
front door locks had not been forced, thereby proving that the burglars
had either used skeleton keys or entered over the balcony. There was no
trace of fingerprints, but the inspector found a dirty red bundle that
contained jewellery which the old lady said was not hers. So their entry
into this flat was apparently not the burglars' first job that day and
they must have been disturbed. The inspector then asked the old lady to
try to check what was missing by the next day and advised her not to
stay alone in the flat for a few nights. The old lady though the was a
fussy creature, but since the porter agreed with him, she rang up her
daughter and asked for her help in what she described as a little spot
of bother.
life n. 
monstrous adj. 
negligence n. 
lurk v. 
hinder v. 
fingerprint n. 
chaos n. 
inconceivable adj. 
veritable adj. 
magpie n. 
prudent adj. 
composure n. 
intruder n. 
toss v. 
discard v. 
discard v. 
constable n. 
ransack v. 
balcony n. 
fussy adj. 
30
** Lesson 59 Collecting
What in particular does a person gain when he or she becomes a serious
collector?
People tend to amass possessions, sometimes without being aware of doing
so. Indeed they can have a delightful surprise when they find something
useful which they did not know they owned. Those who never have to move
house become indiscriminate collectors of what can only be described as
clutter. They leave unwanted objects in drawers, cupboards and attics
for years, in the belief that they may one day need just those very
things. As they grow old, people also accumulate belongings for two
other reasons, lack of physical and mental energy, both of which are
essential in turning out and throwing away, and sentiment. Things owned
for a long time are full associations with the past, perhaps with
relatives who are dead, and so they gradually acquire a value beyond
their true worth.
Some things are collected deliberately in the home in an attempt to
avoid waste. Among these I would list string and brown paper, kept by
thrifty people when a parcel has been opened, to save buying these two
requisites. Collecting small items can easily become a mania. I know
someone who always cuts sketches out from newspapers of model clothes
that she would like to buy if she had the money. As she is not rich, the
chances that she will ever be able to afford such purchases are remote;
but she is never sufficiently strong-minded to be able to stop the
practice. It is a harmless bait, but it litters up her desk to such an
extent that every time she opens it, loose bits of paper fall out in
every direction.
Collecting as a serous hobby is quite different and has many advantages.
It provides relaxation for leisure hours, as just looking at one's
treasures is always a joy. One does not have to go outside for
amusement, since the collection is housed at home. Whatever it consists
of, stamps, records, first editions of books china, glass, antique
furniture, pictures, model cars, stuffed birds, toy animals, there is
always something to do in connection with it, from finding the right
place for the latest addition, to verifying facts in reference books.
This hobby educates one not only in the chosen subject, but also in
general matters which have some bearing on it. There are also other
benefits. One wants to meet like-minded collectors, to get advice, to
compare notes, to exchange articles, to show off the latest find. So
one's circle of friends grows. Soon the hobby leads to travel, perhaps
to a meeting in another town, possibly a trip abroad in search of a rare
specimen, for collectors are not confined to any one country. Over the
years, one may well become a authority on one's hobby and will very
probably be asked to give informal talks to little gatherings and then,
if successful, to larger audiences. In this way self-confidence grows,
first from mastering a subject, then from being able to take about it.
Collecting, by occupying spare time so constructively, makes a person
contented, with no time for boredom.
amass v. 
indiscriminate adj. 
clutter n. 
string n. 
requisite n. 
mania n. 
sketch n. 
remote adj. 
strong-minded adj. 
relaxation n. 
verify v. 
bearing n. 
like-minded adj. 
specimen n. 
constructively adv. 
contented adj. 
boredom n. 
** Lesson 60 Too early and too late
Why did the young girl miss the train?
Punctuality is a necessary habit in all public affairs in civilized
society. Without it, nothing could ever be brought to a conclusion;
everything would be in state of chaos. Only in a sparsely-populated
rural community is it possible to disregard it. In ordinary living,
there can be some tolerance of unpunctuality. The intellectual, who is
working on some abstruse problem, has everything coordinated and
organized for the matter in hand. He is therefore forgiven if late for a
dinner party. But people are often reproached for unpunctuality when
their only fault is cutting things fine. It is hard for energetic,
quick-minded people to waste time, so they are often tempted to finish a
job before setting out to keep an appointment. If no accidents occur on
the way, like punctured tires, diversions of traffic, sudden descent of
fog, they will be on time. They are often more industrious, useful
citizens than those who are never late. The over-punctual can be as much
a trial to others as the unpunctual. The guest who arrives half an hour
too soon is the greatest nuisance. Some friends of my family had this
irritating habit. The only thing to do was ask them to come half an hour
later than the other guests. Then they arrived just when we wanted them.
If you are citing a train, it is always better to be comfortably early
than even a fraction of a minted too late. Although being early may mean
wasting a little time, this will be less than if you miss the train and
have to wait an hour or more for the next one; and you avoid the
frustration of arriving at the very moment when the train is drawing out
of the station and being unable to get on it. An even harder situation
is to be on the platform in good time for a train and still to see it go
off without you. Such an experience befell a certain young girl the
first time she was traveling alone.
She entered the station twenty minutes before the train was due, since
her parents had impressed upon her that it would be unforgivable to miss
it and cause the friends with whom she was going to stay to make two
journeys to meet her. She gave her luggage to a porter and showed him
her ticket. To her horror he said that she was two hours too soon. She
felt inhere handbag for the piece of paper on which her father had
written down al the details of the journey and gave it to the porter. He
agreed that a train did come into the station at the time on the paper
and that it did stop, but only to take on mail, not passengers. The girl
asked to see a timetable, feeling sure that her father could not have
made such a mistake. The porter went to fetch one and arrive back with
the station master, who produced it with a flourish and pointed out a
microscopic 'o' beside the time of the arrival of the train at his
station; this little 'o' indicated that the train only stopped for mail.
Just as that moment the train came into the station. The girl, tears
streaming down her face, begged to be allowed to slip into the guard's
van. But the station master was adamant: rules could not be broken and
she had to watch that train disappear towards her destination while she
was left behind.
punctuality n. 
rural adv. 
disregard v. 
intellectual n. 
abstruse adj. 
coordinate v. 
reproach v. 
puncture v. 
diversion n. 
trial n. 
fraction n. 
flourish n. 
microscopic adj. 
adamant adj. 
20
