* New Concept English 1
*** Lesson 1 Excuse me!
Listen to the tape then answer this question. Whose handbag is it?
Excuse me!
Yes?
Is this your handbag?
Pardon?
Is this your handbag?
Yes, it is.
Thank you very much.
New Word and expressions 
excuse
v. 
me
pron.()
yes
adv. 
is
v. be 
this
pron.
your
possessive adjective 
handbag
n. 
pardon
int. 
it
pron.
thank you
very much
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter2.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 3 Sorry, sir.
Listen to the tape then answer this question.
My coat and my umbrella please.
Here is my ticket.
Thank you, sir.
Number five.
Here's your umbrella and your coat.
This is not my umbrella.
Sorry sir.
Is this your umbrella?
No, it isn't.
Is this it?
Yes, it is.
Thank you very much.
New words and Expressions 
umbrella
n. 
please
int. 
here
adv. 
my
possessive adjective 
ticket
n. 
number
n. 
five
num. 
sorry
adj. 
sir
n. 
cloakroom
n. 
5
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter3.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 5 Nice to meet you
Listen to the tape then answer this question. Is Chang-woo Chinese?
MR. BLAKE: Good morning.
STUDENTS: Good morning, Mr. Blake.
MR. BLAKE: This is Miss Sophie Dupont.
Sophie is a new student.
She is French.
MR. BLAKE: Sophie, this is Hans.
He is German.
HANS: Nice to meet you.
MR. BLAKE: And this is Naoko.
She's Japanese.
NAOKO: Nice to meet you.
MR. BLAKE: And this is Chang-woo.
He's Korean.
CHANG-WOO: Nice to meet you.
MR. BLAKE: And this is Luming.
He is Chinese.
LUMNG: Nice to meet you.
MR. BLAKE: And this is Xiaohui.
She's Chinese, too.
XIAOHUI: Nice to meet you.
New Word and expressions 
Mr.
good
adj. 
Miss
new
adj. 
student
n. 
French
adj. & n. 
German
adj. & n. 
nice
adj. 
meet
v. 
Japanese
adj. & n. 
Korean
adj. & n. 
Chinese
adj. & n. 
too
adv. 
.
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter4.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 7 Are you a teacher?
Listen to the tape then answer this question. What is Rober's job?
ROBERT: I am a new student.
My name's Robert.
SOPHIE: Nice to meet you.
My name's Sophie.
ROBERT: Are you French?
SOPHIE: Yes, I am.
SOPHIE: Are you French too?
ROBERT: No, I am not.
SOPHIE: What nationality are you?
ROBERT: I'm Italian.
ROBERT: Are you a teacher?
SOPHIE: No, I'm not.
ROBERT: What's your job?
SOPHIE: I'm a keyboard operator.
SOPHIE: What's your job?
ROBERT: I'm an engineer.
New Word and expressions 
I
pron.
am
v. be 
are
v. be 
name
n. 
what
adj. & pron. 
nationality
n. 
job
n. 
keyboard
n. 
operator
n. 
engineer
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter5.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 9 How are you today?
Listen to the tape then answer this question. How is Emma?
STEVEN: Hello, Helen.
HELEN: Hi, Steven.
STEVEN: How are you today?
HELEN: I'm very well, thank you.
And you?
STEVEN: I'm fine, thanks.
STEVEN: How is Tony?
HELEN: He's fine, thanks.
How's Emma?
STEVEN: She's very well, too, Helen.
STEVEN: Goodbye, Helen.
Nice to see you.
HELEN: Nice to see you, too, Steven.
Goodbye.
New Word and expressions 
hello
int. 
hi
int. 
how
adv. 
well
adj. 
fine
adj. 
thanks
int. 
goodbye
int. 
see
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter6.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 11 Is this your shirt?
Listen to the tape then answer this question. Whose shirt is white?
HEACHERWhose shirt is that?
HEACHERIs this your shirt, Dave?
DAVE: No. Sir.
It's not my shirt.
DAVE: This is my shirt.
My shirt's blue.
TEACHER: Is this shirt Tim's?
DAVE: Perhaps it is, sir.
Tim's shirt's white.
HEACHERTim!
TIM: Yes, sir?
HEACHERIs this your shirt?
TIM: Yes, sir.
HEACHERHere you are.
Catch!
TIM: Thank you, sir.
New Word and expressions 
whose
pron.
blue
adj. 
perhaps
adv. 
white
adj. 
catch
v. 
: 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter7.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 13 A new dress
Listen to the tape then answer this question. What colour is Anna's hat?
LOUISE: What colour's your new dress?
ANNA: It's green.
ANNA: Come upstairs and see it.
LOUISE: Thank you.
ANNA: Look!
Here it is!
LOUISE: That's nice dress.
It's very smart.
ANNA: My hat's new, too.
LOUISE: What colour is it?
ANNA: It's the same colour.
It's green, too.
LOUISE: That is a lovely hat!
New Word and expressions 
colour
n. 
green
adj. 
come
v. 
upstairs
adv. 
smart
adj. 
hat
n. 
same
adj. 
lovely
adj. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter8.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 15 your passports, please.
Listen to the tape then answer this question. Is there a problem with
the Customs officer?
CUSTOMS OFFICER: Are you Swedish?
GIRLS: No, we are not.
We are Danish.
CUSTOMS OFFICER: Are your friends Danish, too?
GIRLS: No, they aren't.
They are Norwegian.
CUSTOMS OFFICER: Your passports, please.
GIRLS: Here they are.
CUSTOMS OFFICER: Are these your cases?
GIRLS: No, they aren't.
GIRLS: Our cases are brown.
Here they are.
CUSTOMS OFFICER: Are you tourists?
GIRLS: Yes, we are.
CUSTOMS OFFICER: Are your friends tourists too?
GIRLS: Yes, they are.
CUSTOMS OFFICER: That's fine.
GIRLS: Thank you very much.
New Word and expressions 
customs
n. 
officer
n. 
girl
n. 
Danish
adj.& n. 
friend
n. 
Norwegian
adj. & n. 
passport
n. 
brown
adj. 
tourist
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter9.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 17 How do you do?
Listen to the tape then answer this question. What are Michael Maker and
Jeremy Short's jobs?
..
MR. JACKSON: Come and meet our
employees, Mr.Richards.
MR. RICHARDS: Thank you, Mr. Jackson.
MR. JACKSON: This is Nicola Grey,
and this is Claire Taylor.
MR. RICHARDS: How do you do?
MR. RICHARDS: Those women are very hard-working.
What are their jobs?
MR. JACKSON: They're keyboard operators.
MR. Jackson: This is Michael Baker,
and this is Jeremy Short.
MR. RICHARDS: How do you do?
MR. RICHARDS: They aren't very busy!
What are their jobs?
MR. JACKSON: They're sales reps.
They're very lazy.
MR. RICHARDS: Who is this young man?
MR. JACKSON: This is Jim.
He's our office assistant.
New Word and expressions 
employee
n. 
hard-working
adj. 
sales reps
man
n. 
office
n. 
assistant
n. 
.
.
.
.
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter10.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 19 Tired and thirsty
Listen to the tape then answer this question. Why do the children thank
their mother?
MOTHER: What's the matter, children?
GIRL: We're tired ...
BOY: ... and thirsty, Mum.
MOTHER: Sit down here.
MOTHER: Are you all right now?
BOY: No, we aren't.
MOTHER: Look!
There's an ice cream man.
MOTHER: Two ice cream please.
MOTHER: Here you are, children.
CHILDREN: Thanks, Mum.
GIRL: These ice creams are nice.
MOTHER: Are you all right now?
CHILDREN: Yes, we are, thank you!
New Word and expressions 
matter
n. 
children
n. child
tired
adj. ,
boy
n. 
thirsty
adj. 
Mum
n. 
sit down
right
adj. 
ice cream
......
......
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter11.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 21 Which book?
Listen to the tape then answer this question. Which book does the man
want?
MAN: Give me a book please, Jane.
WOMAN: Which book?
WOMAN: This one?
MAN: No, not that one. The red one.
WOMAN: This one?
MAN: Yes, please.
WOMAN: Here you are.
MAN: Thank you.
New Word and expressions 
give
v. 
one
pron.
which
question word 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter12.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 23 Which glasses?
Listen to the tape then answer this question. Which glasses does the man
want?
MAN: Give me some glasses please, Jane.
WOMAN: Which glasses?
WOMAN: These glasses?
MAN: No, not those.
The one on the shelf.
WOMAN: These?
MAN: Yes, please.
WOMAN: Here you are.
MAN: Thanks.
New Word and expressions 
on
prep.......
shelf
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter13.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 25 Mrs. Smith's Kitchen
Listen to the tape then answer this question. What colour is the
electric cooker?
Mrs. Smith's kitchen is small.
There is a refrigerator in the kitchen.
The refrigerator is white.
It is on the right.
There is an electric cooker in the kitchen.
The cooker is blue.
It is on the left.
There is a table in the middle of the room.
There is a bottle on the table.
The bottle is empty.
There is a cup on the table, too.
The cup is clean.
New Word and expressions 
Mrs.
kitchen
n. 
refrigerator
n. 
right
n. 
electric
adj. 
left
n. 
cooker
n. 
middle
n. 
of
prep.......
room
n. 
cup
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter15.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 27 Mrs. Smith's living room
Listen to the tape then answer this question. Where are the books?
Mrs. Smith's living room is large.
There is a television in the room.
The television is near the window.
There are some magazines on the television.
There is a table in the room.
There are some newspapers on the table.
There are some armchairs in the room.
The armchairs are near the table.
There is a stereo in the room.
The stereo is near the door.
There are some books on the stereo.
There are some pictures in the room.
The pictures are on the wall.
New Word and expressions 
living room
near
prep.
widow
n. 
armchair
n. 
door
n. 
picture
n. 
wall
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter16.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 29 Come in, Amy.
Listen to the tape then answer this question. How must Amy clean the
floor?
MRS. JONES: Come in, Amy.
MRS. JONES: Shut the door, please.
MRS. JONES: This bedroom's very untidy.
MAY: What must I do, Mrs. Jones?
MRS. JONES: Open the window and air the room.
MRS. JONES: Then put these clothes in the wardrobe.
MRS. JONES: Then make the bed.
MRS. JONES: Dust the dressing table.
MRS. JONES: Then sweep the floor.
New Word and expressions 
shut
v. 
bedroom
n. 
untidy
adj. 
must
modal verb 
open
v. 
air
v.  ... 
put
v. 
clothes
n. 
wardrobe
n. 
dust
v. 
sweep
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter17.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 31 Where's Sally?
Listen to the tape then answer this question. Is the cat climbing the
tree?
JEAN: Where's Sally, Jack?
JACK: She's in the garden, Jean.
JEAN: What's the doing?
JACK: She's sitting under the tree.
JEAN: Is Tim in the garden, too?
JACK: Yes, he is.
He's climbing the tree.
JEAN: I beg your pardon?
Who's climbing the tree?
JACK: Tim is.
JEAN: What about the dog?
JACK: The dog's in the garden, too.
It's running across the grass.
It's running after a cat.
New Word and expressions 
garden
n. 
under
prep.......
tree
n. 
climb
v. 
who
pron.
run
v. 
grass
n. 
after
prep.......
across
prep.
cat
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter18.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 33 A fine day
Listen to the tape then answer this question. Where is the Jones family?
It is a fine day today.
There are some clouds in the sky,
but the sun is shining.
Mr. Jones is with his family.
They are walking over the bridge.
There are some boats on the river.
Mr. Jones and his wife are looking at them.
Sally is looking at a big ship.
The ship is going under the bridge.
Tim is looking at an aeroplane.
The aeroplane is flying over the river.
New Word and expressions 
day
n. 
cloud
n. 
sky
n. 
sun
n. 
shine
v. 
with
prep. ......
family
n. 
walk
v. , 
over
prep.......
bridge
n. 
boat
n. 
river
n. 
ship
n. 
aeroplane
n. 
fly
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter19.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 35 Our village
Listen to the tape then answer this question. Are the children coming
out of the park or going into it?
This is a photograph of our village.
Our village is in a valley.
It is between two hills.
The village is on a river.
Here is another photograph of the village.
My wife and I are walking
along the banks of the river.
We are on the left.
There is a boy in the water.
He is swimming across the river.
Here is another photograph.
This is the school building.
It is beside a park.
The park is on the right.
Some children are coming out of the building.
Some of them are going to the park.
New Word and expressions 
photograph
n. 
village
n. 
valley
n. 
between
prep.......
hill
n. 
another
det. 
wife
n. 
along
prep.
bank
n. 
water
n. 
swim
v. 
building
n. 
park
n. 
into
prep.
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter20.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 37 Making a bookcase
Listen to the tape then answer this question. What is Susan's favourite
colour?
DAN: You're working hard, George.
What are you doing?
GEORGE: I'm making a bookcase.
GEORGE: Give me that hammer please, Dan.
DAN: Which hammer?
This one?
GEORGE: No, not that one.
The big one.
DAN: Here you are.
GEORGE: Thanks, Dan.
DAN: What are you doing to do now,
George?
GEORGE: I'm going to paint it.
DAN: What colour are you going
to pain it?
GEORGE: I'm going to paint it pink.
DAN: Pink!
GEORGE: This bookcase isn't for me.
It's for my daughter, Susan.
Pink's her favourite colour.
New Word and expressions 
work
v. 
hard
adv. 
make
v. 
bookcase
n. 
hammer
n. 
paint
v. 
pink
n.& adj. 
favourite
adj. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter21.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 39 Don't drop it!
Listen to the tape then answer this question. Where does Sam put the
vase in the end?
SAM: What are you going to do with
that vase, Penny?
PENNY: I'm going to put it on this
table, Sam.
SAM: Don't do that.
Give it to me.
PENNY: What are you going to do with it?
SAM: I'm going to put it here,
in front of the window.
PENNY: Be careful!
Don't drop it!
PENNY: Don't put there, Sam.
Put it here,
on this shelf.
SAM: There we are!
It's a lovely vase.
PENNY: Those flowers are lovely, too.
New Word and expressions 
front
n. 
in front of
......
careful
adj. 
vase
n. 
drop
v. 
flower
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter22.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 41 Penny's bag
Listen to the tape then answer this question. Who is the tin of tobacco
for?
SAN: Is that bag heavy, Penny?
PENNY: Not very.
SAN: Here!
Put it on this chair.
What's in it?
PENNY: A piece of cheese.
A loaf of bread.
A bar of soap.
A bar of Chocolate.
A bottle of milk.
A pound of sugar.
Half a pound of coffee.
A quarter of pound of tea.
And a tin of tobacco.
SAN: Is that tin of tobacco for me?
PENNY: Well, it's certainly not for me!
New Word and expressions 
cheese
n. 
bread
n. 
soap
n. 
chocolate
n. 
sugar
n. 
coffee
n. 
tea
n. 
tobacco
n. 
1/4 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter23.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 43 Hurry up!
Listen to the tape then answer this question. How do you know Sam
doesn't make the tea very often?
PENNY: Can you make the tea, Sam?
SAM: Yes, of course I can, Penny.
SAM: Is there any water in this
kettle?
PENNY: Yes, there is.
SAM: Where's the tea?
PENNY: It's over there,
behind the teapot.
PENNY: Can you see it?
SAM: I can see the teapot,
but I can't see the tea.
PENNY: There it is!
It's in front of your!
SAM: Ah yes, I can see it now.
SAM: Where are the cups?
PENNY: There are some in the cupboard.
PENNY: Can you find them?
SAM: Yes. Here they are.
PENNY: Hurry up, Sam!
The kettle's boiling!
New Word and expressions 
of course
kettle
n. 
behind
prep.......
teapot
n. 
now
adv. 
find
v. 
boil
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter24.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 45 The boss's letter
Listen to the tape then answer this question. Why can't Pamela type the
letter?
THE BOSS: Can you come here a minute
please, Bob?
BOB: Yes, sir?
THE BOSS: Where's Pamela?
BOB: She's next door.
She's in her office, sir.
THE BOSS: Can she type
this letter for me?
Ask her please.
BOB: Yes, sir.
BOB: Can you type this letter
for the boss please, Pamela?
PAMELA: Yes, of course I can.
BOB: Here you are.
PAMELA: Thank you, Bob.
PAMELA: Bob!
BOB: Yes?
What's the letter.
PAMELA: I can't type this letter.
PAMELA: I can't read it!
The boss's handwriting is
terrible!
New Word and expressions 
can
modal verb 
boss
n. 
minute
n. 
ask
v. 
handwriting
n. 
terrible
adj. 
: 
: 
: 
: 
: 
: 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter25.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 47 A cup of coffee
Listen to the tape then answer this question. How does Ann like her
coffee?
CHRISTINE: Do you like coffee, Ann?
ANN: Yes, I do.
CHRISTINE: Do you want a cup?
ANN: Yes, please, Christine.
CHRISTINE: Do you want any sugar?
ANN: Yes, please.
CHRISTINE: Do you want any milk?
ANN: No, thank you.
I don't like milk in my coffee.
I like black coffee.
CHRISTINE: Do you like biscuits?
ANN: Yes. I do.
CHRISTINE: Do you want one?
ANN: Yes, please.
New Word and expressions 
like
v. 
want
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter26.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 49 At the butcher's
Listen to the tape then answer this question. What does Mr. Bird like?
BUTCHER: Do you want any meat today.
Mrs. Bird?
MRS.BIRD: Yes, please.
BUTCHER: Do you want beef or lamb?
MRS.BIRD: Beef, please.
BUTCHER: This lamb's very good.
MRS.BIRD: I like lamb,
but my husband doesn't.
BUTCHER: What about some steak?
This is a nice piece.
MRS.BIRD: Give me that piece, please.
MRS.BIRD: And a pound of mince, too.
BUTCHER: Do you want a chicken,
Mrs. Bird?
They 're very nice.
MRS.BIRD: No, thank you.
MRS.BIRD: My husband likes steak,
but he doesn't like chicken.
BUTCHER: To tell you the truth,
Mrs. Bird,
I don't like chicken either!
New Word and expressions 
butcher
n. 
meat
n. 
beef
n. 
lamb
n. 
husband
n. 
steak
n. 
mince
n. 
chicken
n. 
tell
v. 
truth
n. 
either
adv. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter27.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 51 A pleasant climate
Listen to the tape then answer this question. Does it ever snow In
Greece?
HANS: Where do you come from?
DIMITRI: I come from Greece.
HANS: What's the climate like
in your country?
DIMITRI: It's very pleasant.
HANS: What's the weather
like in spring?
DIMITRI: It's often windy in March.
It's always warm in April
and May,
but it rains sometimes.
HANS: What's it like in summer?
DIMITRI: It's always hot
in June, July and August.
The sun shines every day.
HANS: Is it cold or warm in autumn?
DIMITRI: It's always warm
in September and October.
It's often cold in November
and it rains sometimes.
HANS: Is it very cold in winter?
DIMITRI: It's often cold
in December, January
and February.
It snows sometimes.
New Word and expressions 
Greece
n. 
climate
n. 
country
n. 
pleasant
adj. 
weather
n. 
spring
n. 
windy
adj. 
warm
adj. 
rain
v. 
sometimes
adv. 
summer
n. 
autumn
n. 
winter
n. 
snow
v. 
January
n. 1
February
n. 2
March
n. 3
April
n. 4
May
n. 5
June
n. 6
July
n. 7
August
n. 8
September
n. 9
October
n. 10
November
n. 11
December
n. 12
3
45
678
910
11
1212
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter29.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 53 An interesting climate
Listen to the tape then answer this question. What is the favourite
subject of conversation in England?
HANS: Where do you come from?
JIM: I come from England.
HANS: What's the climate like in your
country?
JIM: It's mild,
but it's not always pleasant.
JIM: The weather's often cold
in North and windy in the East.
It's often wet in the West
and sometimes warm in the south.
HANS: Which seasons do you like best?
JIM: I like spring and summer.
The days are long and the night
are short.
The sun rises early and sets late.
JIM: I don't like autumn and winter.
The days are short
and the nights are long.
The sun rises late
and set early.
Our climate is not very good,
but it's certainly interesting.
It's our favourite subject
of conversation.
New Word and expressions 
mild
adj. 
always
adv. 
north
n. 
east
n. 
wet
adj. 
west
n. 
south
n. 
season
n. 
best
adv. 
night
n. 
rise
v. 
early
adv. 
set
v. 
late
adv. 
interesting
adj. 
subject
n. 
conversation
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter30.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 55 The Sawyer family
Listen to the tape then answer this question. When do the children do
their homework?
The Sawyer live at 87 King Street.
In the morning, Mr. Sawyer goes to work and the children go to school.
Mrs. Sawyer stays at home every day. She does the housework.
She always eats her lunch at noon.
In the afternoon, she usually sees her friends. They often drink tea
together.
In the evening, the children come home from school. They arrive home
early.
Mr. Sawyer comes home from work. He arrives home late.
At night, the children always do their homework. Then they go to bed.
Mr. Sawyer usually reads his newspaper, but sometimes he and his wife
watch television.
New Word and expressions 
live
v. 
stay
v. 
home
n. 
adv. 
housework
n. 
lunch
n. 
afternoon
n. 
usually
adv. 
together
adv. 
evening
n. 
arrive
v. 
night
n. 
87
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter31.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 57 An unusual day
Listen to the tape then answer this question. What is Mr. Sawyer doing
tonight?
It is eight o'clock. The children go to school by car every day, but
today, they are going to school on foot.
It is ten o'clock. Mrs. Sawyer usually stays at home in the morning, but
this morning, she is going to the shops.
It is four o'clock. In the afternoon, Mrs. Sawyer usually drinks tea in
the living room. But this after, she is drinking tea in the garden.
It is six o'clock. In the evening, the children usually do their
homework, but this evening, they are not doing their homework. At the
moment, they are playing in the garden.
It is nine o'clock. Mr. Sawyer usually reads his newspaper at night. But
he's not reading his newspaper tonight. At the moment, he's reading an
interesting book.
New Word and expressions 
o'clock
adv. 
shop
n. 
moment
n. 
8
10
4
6
9
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter32.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 59 Is that all?
Listen to the tape then answer this question. Does the lady buy and
chalk?
LADY: I want some envelopes,
please.
SHOP ASSISTANT: Do you want the
large size or the
small size?
LADY: The large size, please.
LADY: Do you have any
writing paper?
SHOP ASSISTANT: Yes, we do.
SHOP ASSISTANT: I don't have any small
pads. I only have large
one. Do you want a pad?
LADY: Yes, please.
LADY: And I want some glue.
SHOP ASSISTANT: A bottle of glue.
LADY: And I want a large box
of chalk, too.
SHOP ASSISTANT: I only have small boxes.
Do you want one?
LADY: No, thank you.
SHOP ASSISTANT: Is that all?
LADY: That's all, thank you.
SHOP ASSISTANT: What else do you want?
LADY: I want my change.
New Word and expressions 
envelope
n. 
writing paper
shop assistant
size
n. 
pad
n. 
glue
n. 
chalk
n. 
change
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter33.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 61 A bad cold
Listen to the tape then answer this question. What is good news for
Jimmy?
MR. WILLIAMS: Where's Jimmy?
MRS. WILLIAMS: He's in bed.
MR. WILLIAMS: What's the matter
with him?
MRS. WILLIAMS: He feels ill.
MR. WILLIAMS: He looks ill.
MRS. WILLIAMS: We must call the doctor.
MR. WILLIAMS: Yes, we must.
MR. WILLIAMS: Can you remember
the doctor's telephone
number?
MRS. WILLIAMS: Yes.
It's 09754.
DOCTOR: Open your mouth, Jimmy.
Show me your tongue.
Say, "Ah'.
MR. WILLIAMS: What's the matter with
him, doctor?
DOCTOR: He has a bad cold,
Mr. Williams,
so he must stay in bed
for a week.
MRS. WILLIAMS: That's good new for
Jimmy.
DOCTOR: Good news?
Why?
MR. WILLIAMS: Because he doesn't like
school!
New Word and expressions 
feel
v. 
look
v. 
must
modal verb 
call
v. 
doctor
n. 
telephone
n. 
remember
v. 
mouth
n. 
tongue
n. 
bad
adj. 
cold
n. 
news
n. 
09754
------
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter34.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 63 Thank you, doctor.
Listen to the tape then answer this question. Who else is in bed today?
Why?
DOCTOR: How's Jimmy today?
MRS. WILLIAMAS: Better. Thank you,
Doctor.
DOCTOR: Can I see him please,
Mrs. Williams?
MRS. WILLIAMAS: Certainly, doctor.
Come upstairs.
DOCTOR: You look very well,
Jimmy. You are better
now, but you mustn't
get up yet. You must
stay in bed for another
two days.
DOCTOR: The boy mustn't
go to school yet,
Mr. Williams.
And he mustn't
eat rich food.
MRS. WILLIAMAS: Does he have a
temperature, doctor?
DOCTOR: No, he doesn't.
MRS. WILLIAMAS: Must he stay in bed?
DOCTOR: Yes.
He must remain in bed
for another two days.
He can get up
for about two hours
each day, but you must
keep the room warm.
DOCTOR: Where's Mr. Williams
this evening?
MRS. WILLIAMAS: He's in bed, doctor.
Can you see him please?
He has a bad cold, too!
New Word and expressions 
better
adj. well
certainly
adv. 
get up
yet
adv. 
rich
adj. 
food
n. 
remain
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter35.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 65 Not a baby
Listen to the tape then answer this question. Does Jill take the key to
the front door?
FATHER: What are you going to do
this evening. Jill?
JILL: I'm going to meet some friends.
Dad.
FATHER: You mustn't come home late.
You must be home at half past
ten.
JILL: I can't get home so early, Dad!
JILL: Can I have the key
to the front door please?
FATHER: No, you can't.
MOTHER: Jill's eighteen years old, Tom.
She's not a baby.
Give her the key.
She always comes home early.
FATHER: Oh, all right!
FATHER: Here you are.
But you mustn't come home
after a quarter past eleven.
Do you hear?
JILL: Yes. Dad.
JILL: Thanks, Mum.
MOTHER: That's all right.
Goodbye.
Enjoy yourself!
JILL: We always enjoy ourselves, Mum.
Bye-bye.
New Word and expressions 
Dad
n. 
key
n. 
baby
n. 
hear
v. 
enjoy
v. 
yourself
rpon.
ourselves
pron.
mum
n. 
10
18
111
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter36.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 67 The weekend
Listen to the tape then answer this question. What are the Johnsons
going to do at the weekend?
MRS.JOHNSON: Hello.
Where you at the butcher's?
MRS.WILLIAMS:Yes. I was.
Were you at butcher's, too?
MRS.JOHNSON: No, I wasn't.
I was at the greengrocer's.
How's Jimmy today?
MRS.WILLIAMS:He's very well, thank you.
MRS.JOHNSON: Was he absent from school
last week?
MRS.WILLIAMS:Yes, he was.
He was absent on Monday,
Tuesday,
Wednesday and Tuesday.
How are you all keeping?
MRS.JOHNSON: Very well, thank you.
We're going to spend
three days in the country.
We're going to stay at my
mother's for the weekend.
MRS.WILLIAMS:Friday, Saturday and Sunday
in the country!
Aren't you lucky!
New Word and expressions 
greengrocer
n. 
absent
adj. 
Monday
n. 
Tuesday
n. 
Wednesday
n. 
Thursday
n. 
keep
v. 
spend
v. 
weekend
n. 
Friday
n. 
Saturday
n. 
Sunday
n. 
country
n. 
lucky
adj. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter37.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 69 The car race
Listen to the tape then answer this question. Which car was the winner
in 1995?
1995
There is a car race near our town every year. In 1995, there was a very
big race.
There were hundreds of people there. My wife and I were at the race. Our
friends Julie and Jack were there, too. You can see us in the crowd. We
are standing on the left.
There were twenty cars in the race. There were English cars, French
cares, German cars. Italian cars. American cars and Japanese cars.
It was an exciting finish. The winner was Billy Stewart. He was in car
number fifteen. Five other cars were just behind him.
On the way home, my wife said to me, 'Don't drive so quickly! You're not
Billy Stewart!'
New Word and expressions 
year
n. 
race
n. 
town
n. 
crowd
n. 
stand
v. 
exciting
adj. 
just
adv. 
finish
n. 
winner
n. 
behind
prep.......
way
n. 
1995
20
.155
.
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter38.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 71 He's awful!
Listen to the tape then answer this question. How did Pauline answer the
telephone at nine o'clock?
9
JANE: What's Ron Marston like,
Pauline?
PAULINE: He's awful!
He telephoned me four times
Yesterday, and three times
the day before yesterday.
PAULINE: He telephoned the office
yesterday morning and
yesterday afternoon.
My boss answered the telephone.
JANE: What did your boss say to him?
PAULINE: He said, "Pauline is typing
typing letters. She can't
speak to you now!"
PAULINE: Then I arrived home
at six o'clock yesterday
evening. He telephoned again.
But I didn't answer the phone!
JANE: Did he telephone again
last night?
PAULINE: Yes, he did.
He telephoned at nine o'clock.
JANE: What did you say to him?
PAULINE: I said, 'This is Pauline's
mother. Please don't telephone
my daughter again!'
JANE: Did he telephone again?
PAULINE: No, he didn't!
New Word and expressions 
awful
adj. 
telephone
v. & n. 
time
n. 
answer
v. 
last
adj. 
phone
n. =telephone
again
adv. 
say (said/sed/)
v. 
.
4
3
6
9
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter39.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 73 The way to King Street
Listen to the tape then answer this question. Why did the man need a
phrasebook?
Last week Mrs. Mills went to London. She does not know London very well,
and she lost her way.
Suddenly, she saw a man near a bus stop. 'I can ask him the way.' she
said to herself.
'Excuse me,' she said. 'Can you tell me the way to King Street, please?'
The man smiled pleasantly. He did not understand English! He spoke
German. He was a tourist.
Then he put his hand into pocket, and took out a phrasebook.
He opened the book and found a phrase. He read the phrase slowly. 'I am
sorry,' he said. 'I do not speak English.'
New Word and expressions 
week
n. 
London
n. 
suddenly
adv. 
bus stop
smile
v. 
pleasantly
adv. 
understand (understood)
v. 
speak (spoke)
v. 
hand
n. 
pocket
n. 
phrasebook
n. 
phrase
n. 
slowly
adv. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter40.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 75 Uncomfortable shoes
Listen to the tape then answer this question. What's wrong with the
fashionable shoes?
LADY: Do you have any shoes
like these?
SHOP ASSISTANT: What size?
LADY: Black.
SHOP ASSISTANT: I'm sorry.
We don't have any.
LADY: But my sister bought
this pair last month.
SHOP ASSISTANT: Did she buy them here?
LADY: No, she bought them
in the U.S.
SHOP ASSISTANT: We had some shoes like
those a month ago,
but we don't have any
now.
LADY: Can you get a pair for
me, please?
SHOP ASSISTANT: I'm afraid that I can't.
They were in fashion
last year and the year
before last.
But they're not in
fashion this year.
SHOP ASSISTANT: These shoes are in
fashion now.
LADY: They look very
uncomfortable.
SHOP ASSISTANT: They are very
uncomfortable. But
women always wear
uncomfortable shoes!
New Word and expressions 
ago
adv. 
buy(bough)
v. 
pair
n. 
fashion
n. 
uncomfortable
adj. 
wear
v. 
5
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter41.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 77 Terrible toothache
Listen to the tape then answer this question. What time of day is it, do
you think? How do you know?
NURSE: Good morning. Mr. Croft.
MR. CROFT: Good morning, nurse.
I was to see the dentist,
please.
NURSE: Do you have an appointment?
MR. CROFT: No, I don't.
NURSE: Is it urgent?
MR. CROFT: Yes, it is.
It's very urgent.
I feel awful.
I have a terrible toothache.
NURSE: Can you come at 10 a.m.
on Monday, April 24th?
MR. CROFT: I must see the dentist now,
nurse.
NURSE: The dentist is very busy
at the moment.
Can you come at 2 p.m.?
MR. CROFT: That's very late.
Can the dentist see me now?
NURSE: I'm afraid that he can't,
Mr. Croft.
Can't you wait till this
afternoon?
MR. CROFT: I can wait, but my toothache
can't!
New Word and expressions 
appointment
n. 
urgent
adj. 
till
prep.......
42410
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter43.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 79 Carol's shopping list
Listen to the tape then answer this question. What is Carol not going to
buy?
TOM: What are you doing, Carol?
CAROL: I'm making a shopping list, Tom.
TOM: What do we need?
CAROL: We need a lot of thing this week.
CAROL: I must go to the grocer's.
We haven't got much tea or
coffee, and we haven't got any
sugar or jam.
TOM: What about vegetables?
CAROL: I must go to the greengrocer's.
We haven't got many tomatoes,
but we've got a lot of potatoes.
CAROL: I must go to the butcher's, too.
We need some meat.
We haven't got any meat at all.
TOM: Have we got any beer and wine?
And I'm not going to get any!
TOM: I hope that you've got some
money.
CAROL: I haven't got much.
TOM: Well, I haven't got much either!
New Word and expressions 
shopping
n. 
list
n. 
vegetable
n. 
need
v. 
hope
v. 
thing
n. 
money
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter44.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 81 Roast beef and potatoes
Listen to the tape then answer this question. Why is Carol disappointed?
SAM: Hi, Carol!
Where's Tom?
CAROL: He's upstairs.
He's having a bath.
CAROL: Tom!
TOM: Yes?
CAROL: Sam's here.
TOM: I'm nearly ready.
TOM: Hello, Sam.
Have a cigarette.
SAM: No, thanks, Tom.
TOM: Have a glass of whisky then.
SAM: OK. Thanks.
TOM: Is dinner ready, Carol?
CAROL: It's nearly ready.
We can have dinner at seven
o'clock.
TOM: Sam and I had lunch together
today. We went to a restaurant.
CAROL: What did you have?
TOM: We had roast beef and potatoes.
CAROL: Oh!
TOM: What's the matter, Carol?
CAROL: Well, you're going to have
roast beef and potatoes
again tonight!
New Word and expressions 
bath
n. 
nearly
adv. 
ready
adj. 
dinner
n. 
roast
adj. 
7
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter45.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 83 Going on holiday
Listen to the tape then answer this question. Where did Sam go for his
holiday this year?
CAROL: Hello, Sam.
Come in.
TOM: Hi, Sam.
We're having lunch.
Do you want to have lunch with
us?
SAM: No, thank you. Tom.
I've already had lunch.
I had at half past twelve.
CAROL: Have a cup of coffee then.
SAM: I've just had a cup, thank you.
I had one after my lunch.
TOM: Let's go into the living room,
Carol.
We can have our coffee there.
CAROL: Excuse the mess, Sam.
This room's very untidy.
We're packing our suitcases.
We're going to leave tomorrow.
Tom and I are going to have a
holiday.
SAM: Aren't you lucky!
TOM: When are you going to have
a holiday, Sam?
SAM: I don't know.
I've already had my holiday
this year.
CAROL: Where did you go?
SAM: I stayed at home!
New Word and expressions 
mess
n. 
pack
v. 
suitcase
n. 
leave
v. 
already
adv. 
12
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter46.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 85 Pairs in the spring
Listen to the tape then answer this question. At what time of year did
Ken visit Paris?
GEORGE: Hello, Ken.
KEN: Hi, George.
GEORGE: Have you just been to the
cinema?
KEN: Yes, I have.
GEORGE: What's on?
KEN: 'Paris in the spring'.
GEORGE: Oh, I've already seen it.
I saw it
on television last year.
It's an old film,
but it's very good.
KEN: Paris is a beautiful city.
GEORGE: I've never been there.
Have you ever been there, Ken?
KEN: Yes, I have.
I was there in April.
GEORGE: Pairs in the spring, eh?
KEN: It was spring,
but the weather was awful.
It rained all the time.
GEORGE: Just like London!
New Word and expressions 
Paris
n. 
cinema
n. 
film
n. 
beautiful
adj. 
city
n. 
never
adv. 
ever
adv. 
4
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter47.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 87 A car crash
Listen to the tape then answer this question. Can the mechanics repair
Mr. Wood's car?
MR. WOOD: Is my car ready yet?
ATTENDANT: I don't know. sir.
What's the number
of your car?
MR. WOOD: It's is LFZ 312G.
ATTENDANT: When did you bring it to us?
MR. WOOD: I brought it here three
days ago.
ATTENDANT: Ah, yes, I remember now.
MR. WOOD: Have your mechanics
finished yet?
ATTENDANT: No, they're still working on
it. Let's go into the
garage and have a look at it.
ATTENDANT: Isn't that your car?
MR. WOOD: Well, it was my car.
ATTENDANT: Didn't you have a crash?
MR. WOOD: That's right.
I drove it into a lamp-post.
Can your mechanics repair it?
ATTENDANT: Well,
they're trying to repair it,
sir.
But to tell you the truth.
you need a new car!
New Word and expressions 
attendant
n. 
bring(brought, brought)
v. 
garage
n. 
crash
n. 
lamp-post
repair
v. 
try
v. 
LFZ312G
3
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter48.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 89 For sale
Listen to the tape then answer this question. Why couldn't Nigel decide?
NIGELGood afternoon.
I believe that this is house is
for sale.
IAN: That's right.
NIGELMay I have a look at it, please?
IAN: Yes, of course. Come in.
NIGELHow long have you lived here?
IAN: I've live here for twenty years.
NIGELTwenty year!
That's long time.
IAN: Yes, I've been here since 1976.
NIGELThen why do you want to sell it?
IAN: Because I've just retired.
I want to buy
a small house in the country.
NIGELHow much does this house cost?
IAN: $68,500.
NIGELWell, I like the house.
but I can't decide yet.
My wife must see it first.
IAN: Women always have the last word.
New Word and expressions 
believe
v. 
may
modal verb 
how long
since
prep.
why
adv. 
sell (sold, sold)
v. 
because
conj.
retire
v. 
cost (cost, cost)
v. 
pound
n. 
worth
prep.......
penny
n. 
: 
: 
: 20
20
: 1976
: 
: 
: 68,500
: 
: 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter49.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 91 Poor Ian!
Listen to the tape then answer this question. Who wanted to sell the
house?
CATHERING: Has Ian sold his house yet?
JENNY: Yes, he has.
He sold it last week.
CATHERING: Has he moved to his new
house yet?
JENNY: No, not yet.
He's still here.
He's going to move tomorrow.
CATHERING: When? Tomorrow afternoon.
JENNY: No. Tomorrow afternoon.
I'll miss him.
He has always been a good
neighbour.
LIDA: He's a very nice person.
We'll all miss him.
CATHERING: When will the new people
move into this house?
JENNY: I think that they'll move in
the day after tomorrow.
LINDA: Will you see Ian today,
Jenny?
JENNY: Yes, I will.
LINDA: Please give him my regards.
CATHERING: Poor Ian!
He didn't want to leave
this house.
JENNY: No, he didn't want to leave.
but his wife did!
New Word and expressions 
still
adv. 
move
v. 
miss
v. 
neighbor
n. 
person
n. 
people
n. 
poor
adj. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter50.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 93 Our new neighbour
Listen to the tape then answer this question. Why is Nigel a lucky man?
Nigel is our new next-door neighbour. He's a pilot.
He was in the R.A.F.
He will fly to New York next month.
The month after next he'll fly to Tokyo.
At the moment, he's in Madrid. He flew to Spain a week ago.
He'll return to London the week after next.
He's only forty-one years old, and he has already been to nearly every
country in the world.
Nigel is a very lucky man. But his wife isn't very lucky. She usually
stays at home!
New Word and expressions 
pilot
n. 
return
v. 
New York
n. 
Tokyo
n. 
Madrid
n. 
fly (flew, flown)
v. 
41
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter51.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 95 Tickets, please.
Listen to the tape then answer this question. Why did George and Ken
miss the train?
GEORGE: Two return tickets to London,
please.
What time will the next train
leave?
ATTENDANT: At nineteen minutes past
eight.
GEORGE: Which platform?
ATTENDANT: Platform Two.
Over the bridge.
KEN: What time will the next train
leave?
GEORGE: At eight nineteen.
KEN: We've got plenty of time.
GEORGE: It's only three minutes
to eight.
KEN: Let's go and have a drink.
There's a bar
next door to the station.
GEORGE: We had better
go back to the station now,
Ken.
PORTER: Tickets, please.
GEORGE: We want to catch
the eight nineteen to London.
PORTER: You've just missed it!
GEORGE: What!
It's only eight fifteen.
PORTER: I'm sorry, sir.
That clock's ten minutes
slow.
GEORGE: When's the next train?
PORTER: In five hours' time!
New Word and expressions 
return
n. 
train
n. 
platform
n. 
plenty
n. 
bar
n. 
station
n. 
porter
n. 
catch (caught, caught)
v. 
miss
v. 
819
2
819
757
819
815
10
5
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter52.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 97 A small blue case
Listen to the tape then answer this question. Does Mr. Hall get his case
back?
MR. MALL: I left a suitcase
on the train to London
the other day.
ATTENDANT: Can you describe it, sir?
MR. MALL: It's a small blue case
and it's got a zip.
There's a label on the handle
with my name and address on
it.
ATTENDANT: Is this case yours?
MR. MALL: No, that's not mine.
ATTENDANT: What about this one?
This one's got a label.
MR. MALL: Let me see it.
ATTENDANT: What's your name and address?
MR. MALL: David Hall,
83, Bridge Street.
ATTENDANT: That's right.
D.N. Hall,
83, Bridge Street.
ATTENDANT: Three pounds fifty pence,
please.
MR. MALL: Here you are.
ATTENDANT: Thank you.
MR. MALL: Key!
ATTENDANT: What's matter?
MR. MALL: This case doesn't belong
to me!
You've given me the wrong
case!
New Word and expressions 
leave (left, left)
v. 
describe
v. 
zip
n. 
label
n. 
handle
n. 
address
n. 
pence
n. penny 
belong
v. 
.83
D.N.
83
350
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter53.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 99 Owl!
Listen to the tape then answer this question. Must Andy go to see the
doctor?
ANDY: Ow!
LUCY: What's the matter, Andy?
ANDY: I slipped and fell downstairs.
LUCY: Have you hurt yourself?
ANDY: Yes, I have.
I think that
I've hurt my back.
LUCY: Try and stand up.
Can you stand up?
Here.
Let me help you.
ANDY: I'm sorry, Lucy.
I'm afraid that
I can't get up.
LUCY: I think that
the doctor had better see you.
I'll phone Dr. Carter.
LUCY: The doctor says that
he will come at once.
I'm sure that
you need an X-ray, Andy.
New Word and expressions 
own
int. 
slip
v. 
fall (fell, fallen)
v. 
downstairs
adv. 
hurt (hurt, hurt)
v. 
back
n. 
stand up
help
v. 
at once
sure
adj. 
X-ray
n. X
X
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter54.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 101 A card from Jimmy
Listen to the tape then answer this question. Does Grandmother seem
pleased to get a card from Jimmy? Why/Why not?
/
GRANDMOTHER: Read Jimmy's card to me
please, penny.
PENNY: 'I have just arrive in
Scotland and I'm staying
at a Youth Hostel.'
GRANDMOTHER: Eh?
PENNY: He say he's just arrived
in Scotland. He says he's
staying at a Youth Hostel.
You know he's a member
of the Y.H.A.
GRANDMOTHER: The what?
PENNY: The Y.H.A., Mum.
The Youth Hostels
Association.
GRANDMOTHER: What else does he say?
PENNY: 'I'll write a letter soon.
I hope you all well.'
GRANDMOTHER: What?
Speak up. Penny.
I'm afraid I can't
hear you
PENNY: He say he'll write a letter
soon. He hopes we are all
well. 'Love, Jimmy.'
GRANDMOTHER: Is that all?
He doesn't say very much,
does he?
PENNY: He can't write very much
on a card, Mum.
New Word and expressions 
Scotland
n. 
card
n. 
youth
n. 
hostel
n. 
association
n. 
soon
adv. 
write (wrote, written)
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter55.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 103 The French test
Listen to the tape then answer this question. How long did the exam
last?
GARY: How was the exam, Richard?
RICHARD: Not too bad.
I think I passed in
English and Mathematics.
The questions were very easy.
How about you, Gary?
GARY: The English and Maths papers
weren't easy enough for me.
I hope I haven't failed.
RICHARD: I think I failed the French
paper.
I could answer sixteen of
the question.
They were very easy.
But I couldn't answer the rest.
They were too difficult for me.
GARY: French test are awful, aren't
they?
RICHARD: I hate them.
I'm sure I've got a low mark.
GARY: Oh, cheer up!
perhaps we didn't to do badly.
The guy next to me
Wrote his name
at the top of the paper.
RICHARD: Yes?
GARY: Then he sat there
and looked at it for three
hours! He didn't write a word!
New Word and expressions 
exam
n. 
pass
v. 
mathematics (maths)
n. 
question
n. 
easy
adj. 
enough
adv. 
paper
n. 
fail
v. 
answer
v. 
mark
n. 
rest
n. 
difficult
adj. 
hate
v. 
low
adj. 
cheer
v. 
guy
n. 
top
n. 
16
3
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter57.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 105 Full of mistakes
Listen to the tape then answer this question. What was Sandra's present?
THE BOSSWhere's Sandra, Bob?
I want her.
BOB: Do you want to speak to her?
THE BOSSYes, I do.
I want her to come to
my office.
Tell her to come at once.
SANDRA: Did you want to see me?
THE BOSSAh, yes, Sandra.
How do you spell
"intelligent'?
Can you tell me?
SANDRA: I-N-T-E-L-L-I-G-E-N-T.
THE BOSSThat's right.
You've typed it with only one
'L'. This letter's full of
mistakes. I want you to type
it again.
SANDRA: Yes, I'll do that.
I'm sorry about that.
THE BOSSAnd here's a little present
for you.
SANDRA: What's it?
THE BOSSIt's a dictionary.
I hope it'll help you.
New Word and expressions 
spell
v. 
intelligent
adj. 
mistake
n. 
present
n. 
dictionary
n. 
"intelligent"
I-N-T-E-L-L-I-G-E-N-T
1L
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter58.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 107 It's too small.
Listen to the tape then answer this question. What kind of dress does
the lady want?
ASSISTANT: Do you like this dress,
madam?
LADY: I like the colour very much.
It's lovely dress,
but it's too small for me.
ASSISTANT: What about this one?
It's lovely dress.
It's very smart.
Short skirts are in fashion
now.
Would you like to try it?
LADY: All right.
LADY: I'm afraid this green dress
it too small for me as well.
It's smaller than the blue
one.
LADY: I don't like the colour
either. It doesn't suit me
at all. I think the blue
dress is prettier.
LADY: Could you show me another
blue dress? I want a dress
like that one, but it must
be my size.
ASSISTANT: I'm afraid I haven't got
a larger dress.
This is the largest dress
in the shop.
New Word and expressions 
madam
n. 
smart
adj. 
as well
suit
v. 
pretty
adj. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter59.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 109 A good idea
Listen to the tape then answer this question. What does Jane have with
her coffee?
CHARLOTTE: Shall I make some coffee,
Jane?
JANE: That's a good idea,
Charlotte.
CHARLOTTE: It's ready.
Do you want any milk?
JANE: Just a little, please.
CHARLOTTE: What about some sugar?
Two teaspoonfuls?
JANE: No, less than that.
One and a half teaspoonfuls,
please.
That's enough for me.
JANE: That was very nice.
CHARLOTTE: Would you like some more?
JANE: Yes, please.
JANE: I'd like a cigarette, too.
May I have one?
CHARLOTTE: Of course.
I think there are a few in
that box.
JANE: I'm afraid it's empty.
CHARLOTTE: What a pity!
JANE: It doesn't matter.
CHARLOTTE: Have a biscuit instead.
Eat more and smoke less!
JANE: That's very good advice!
New Word and expressions 
idea
n. 
a little
teaspoonful
n. 
less
adj. (little )
a few
pity
n. 
instead
adv. 
advice
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter60.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 111 The most expensive model
Listen to the tape then answer this question. Can Mr. Frith buy the
television on instalments? How does it work?
MR. FRITH: I like television very much.
How much does it cost?
ASSISTANT: It's the most expensive
model in the shop.
It costs five hundred pounds.
MR. FRITH: That's too expensive for us.
We can't afford all that
money.
ASSISTANT: This model's less expensive
than that one.
It's only three hundred
pounds. But, of course,
it's not as good as the
expensive one.
MR. FRITH: I don't like the model.
The other model's more
expensive, but it's
worth the money.
MR. FRITH: Can we buy it on instalments?
ASSISTANT: Of course.
You can pay a deposit of
thirty pounds, and then
fourteen pounds a month for
three years.
MR. FRITH: Do you like it, dear?
MRS. FRITH:I certainly do,
but I don't like the price.
You always want the best,
but we can't afford it.
Sometimes you think
you're a millionaire!
MR. FRITH: Millionaires don't buy
things on instalments!
New Word and expressions 
model
n. 
afford
v. 
deposit
n. 
instalment
n. 
price
n. 
millionaire
n. 
500
300
]
30
14,3
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter61.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 113 Small change
Listen to the tape then answer this question. Who has got some change?
CONDUCTOR: Fares, please!
MAN: Trafalgar Square,
please.
CONDUCTOR: I'm sorry, sir.
I can't change a
ten-pound note.
Haven't you got any
small change?
MAN: I've got no small change,
I am afraid.
CONDUCTOR: I'll ask some of the
passengers.
CONDUCTOR: Have you any small
change, sir?
1st PASSENGER: I'm sorry.
I've got none.
2nd PASSENGER: I haven't got any either.
CONDUCTOR: Can you change
this ten-pound note,
madam?
3rd PASSENGER: I'm afraid I can't.
4th PASSENGER: Neither can I.
CONDUCTOR: I'm very sorry, sir.
You must get off the bus.
None of our passengers
can change this note.
They're all millionaires!
TWO TRAMPS: Except us.
1sth TRAMP: I've got some small
change.
2nd TRAMP: So have I.
New Word and expressions 
conductor
n. 
fare
n. , 
change
v. 
note
n. 
passenger
n. 
none
pron.
neither
adv. 
get off
tramp
n. 
except
prep.......
10
1 
2 
10
3 
4 
1 
2 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter62.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 115 Knock, knock!
Listen to the tape then answer this question. What does Jim have to
drink?
HELEN: Isn't there anyone at home?
JIM: I'll knock again, Helen.
Everything's very quiet.
I'm sure there's no one at home.
HELEN: But that's impossible.
Carol and Tom invited us to
lunch.
Look through the window.
HELEN: Can you see anything?
JIM: Nothing at all.
HELEN: Let's try the back door.
JIM: Look! Everyone's in the garden.
CAROL: Hello, Helen. Hello, Jim.
TOM: Everybody wants to have lunch
in the garden.
It's nice and warm out here.
CAROL: Come and have something to drink.
JIM: Thanks, Carol.
May I have a glass of beer
please?
CAROL: Beer?
There's none left.
You can have some lemonade.
JIM: Lemonade!
TOM: Don't believe her, Jim.
She's only joking.
Have some beer!
New Word and expressions 
anyone
pron.
knock
v. 
everything
pron.
quiet
adj. 
impossible
adj. 
invite
v. 
anything
pron.
nothing
pron.
lemonade
n. 
joke
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter63.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 117 Tommy's breakfast
Listen to the tape then answer this question. What does she mean by
'change in the last sentence?
change" 
When my husband was going into the dining room this morning, he dropped
some coins on the floor.
There were coins everywhere. We looked for them, but we could not find
them all.
While we were having breakfast, our little boy, Tommy, found two small
coins on the floor.
He put them both into his mouth. We both tried to get the coins, but it
was too late. Tommy had already swallowed them!
Late that morning, when I was doing the housework, My husband phoned me
from the office.
'How's Tommy?' he asked. 'I don't know,' I answered, 'Tommy's been to
the toilet three times this morning, but I haven't had any change yet!'
New Word and expressions 
dinning room
coin
n. 
mouth
n. 
swallow
v. 
later
adv. 
toilet
n. 
3
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter64.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 119 A true story
Listen to the tape then answer this question. Who called out to the
thieves in the dark?
Do you like stories? I want to tell you a true story. It happened to a
friend of mine a year ago.
While my friend, George, was reading in bed, two thieves climbed into
his kitchen.
After they had entered the house, they went into the dining room. It was
very dark, so they turned on a torch.
Suddenly, they heard a voice behind them. "What's up? What's up?"
someone called. The thieves dropped the torch and ran away as quickly as
they could.
George heard the noise and came downstairs quickly.
He turned on the light, but he couldn't see anyone. The thieves had
already gone.
But George's parrot, Henry, was still there. "What's up, George?" the
called. 'Nothing, Henry,' George said and smiled. 'Go back to sleep.'
New Word and expressions 
story
n. 
happen
v. 
thief
n. 
enter
v. 
dark
adj. 
torch
n. 
voice
n. 
parrot
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter65.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 121 The man in a hat
Listen to the tape then answer this question. Why didn't Caroline
recognize the customer straight away?
CUSTOMER: I bought two expensive
dictionaries here half
and hour ago, but I forgot
to take them with me.
MANAGER: Who served you, sir?
CUSTOMER: The lady who is standing
behind the counter.
MANAGER: Which books did you buy?
CUSTOMER: The books which are on
the counter.
MANAGER: Did you serve this gentleman
half an hour ago, Caroline?
He says he's the man who
bought these books.
CUSTOMER: I can't remember.
The man who I served was
wearing a hat.
MANAGER: Have you got a hat, sir?
CUSTOMER: Yes, I have.
MANAGER: Would you put it on, please?
CUSTOMER: All right.
MANAGER: Is this the man that you
served, Caroline?
CUSTOMER: Yes.
I recognize him now.
New Word and expressions 
customer
n. 
forget (forgot, forgotten)
v. 
manager
n. 
serve
v. 
counter
n. 
recognize
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter66.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 123 A trip to Australia
Listen to the tape then answer this question. Who is the man with the
beard?
MIKE: Look, Scott.
This is a photograph I took
during my trip to Australia.
SCOTT: Let me see it, Mike.
SCOTT: This is a good photograph.
Who are these people?
MIKE: They're people I met during the
trip.
MIKE: That's the ship we travelled on.
SCOTT: What a beautiful ship!
SCOTT: Who's this?
MIKE: That's the man I told you about.
Remember?
SCOTT: Ah yes.
The one who offered you a job
in Australia.
MIKE: That's right.
SCOTT: Who's this?
MIKE: Guess!
SCOTT: It's not you, is it?
MIKE: That's right.
MIKE: I grew a beard during the trip.
but I shaved it off
when I came home.
SCOTT: Why did you shave it off?
MIKE: My wife didn't like it!
New Word and expressions 
during
prep.......
trip
n. 
travel
v. 
offer
v. 
job
n. 
guess
v. 
grow (grew, grown)
v. ......
beard
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter67.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 125 Tea for two
Listen to the tape then answer this question. Does Susan have tea by
herself?
SUSAN: Can't you come in and have tea
now, Peter?
PETER: Not yet.
I must water the garden first.
SUSAN: Do you have to water it now?
PETER: I'm afraid I must.
Look at it!
It's terribly dry.
SUSAN: What a nuisance!
PETER: Last summer it was very dry, too.
Don't you remember?
I had to water it every day.
SUSAN: Well, I'll have tea by myself.
SUSAN: That was quick!
Have you finished already?
PETER: Yes.
Look out of the window.
SUSAN: It's raining!
That means
You don't need to water
the garden.
PERTR: That was a pleasant surprise.
It means I can have tea,
instead.
New Word and expressions 
water
v. 
terribly
adv. 
dry
adj. 
nuisance
n. 
mean (meant, meant)
v. 
surprise
n. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter68.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 127 A famous actress
Listen to the tape then answer this question. Who is only twenty-nine,
and why is it so unclear?
29
KATE: Can you recognize that woman,
Liz?
LIZ: I think I can, Kate.
It must be Karen Marsh,
the actress.
KATE: I though so.
Who's that beside her?
LIZ: That must be Conrad Reeves.
KATE: Conrad Reeves, the actor?
It's can't be.
Let me have another look.
I think you're right!
Isn't he her third husband?
LIZ: No. He must be her fourth or
fifth.
KATE: Doesn't Karen Marsh look old!
LIZ: She does, doesn't she!
I read she's twenty-nine,
but she must be at least forty.
KATE: I'm sure she is.
LIZ: She was a famous actress
When I was still at school.
KATE: That was a long time ago,
wasn't it?
LIZ: Not that long ago!
I'm not more than twenty-nine
myself.
New Word and expressions 
famous
adj. 
actress
n. 
at least
actor
n. 
read (read, read)
v. 
.
.
.
3
45
2940
40
29
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter69.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 129 Seventy miles an hour
70
Listen to the tape then answer this question. What does Ann advise her
husband to do next time?
ANN: Look, Gary!
That policeman's waving to
you.
He wants you to stop.
POLICEMAN: Where do you think you are?
On a race track?
You must have been driving
at seventy miles an hour.
GARY: I can't have been.
POLICEMAN: I was doing eighty
when I overtook you.
POLICEMAN: Didn't you see the speed
limit?
GARY: I'm afraid I didn't, officer.
I must have been dreaming.
ANN: He wasn't dreaming, officer.
I was telling him to drive
slowly.
GARY: That's why I didn't see the
sign.
POLICEMAN: Let me see your driving
licence.
POLICEMAN: I won't charge you this time.
But you'd better not do it
again!
GARY: Thank you.
I'll certainly be more
careful.
ANN: I told you to drive slowly,
Gary.
GARY: You always tell me to drive
slowly, darling.
ANN: Well, next time
you'd better take my advice!
New Word and expressions 
wave
v. 
track
n. 
mile
n. 
overtake (overtook, overtaken)
v. 
speed limit
dream
v. 
sign
n. 
driving licence
charge
v. 
darling
n. 
70
80
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter71.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 131 Don't be so sure!
Listen to the tape then answer this question. What's the problem about
deciding on a holiday?
MARTIN: Where are you going to
spend your holidays this year,
Gary?
GARY: We may go abroad.
I'm not sure.
My wife wants go to Egypt.
I'd like to there, too.
We can't make up our minds.
MARTIN: Will you travel by sea or air?
GARY: We may travel by sea.
MARTIN: It's cheaper, isn't it?
GARY: It may be cheaper.
but it takes a long time.
MARTIN: I'm sure you'll enjoy
yourselves.
GART: Don't be so sure.
We might not go anywhere.
My wife always worries too much.
Who's going to look after the
dog?
Who's going to look after the
house?
Who's going to look after the
garden?
We have this problem every year.
in the end, we stay at home
and look after everything!
New Word and expressions 
Egypt
n. 
abroad
adv. 
worry
v. 
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter72.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 133 Sensational news!
Listen to the tape then answer this question. What reason did Karen
Marsh give for wanting to retire?
.
REPORTER: Have you just made a
new film, Miss Marsh?
MISS MARSH: Yes, I have.
REPORTER: Are you going to make a
another?
MISS MARSH: No, I'm not.
I'm going to retire.
I feel very tired.
I don't want to make
another film for a
long time.
KATE: Let's buy a newspaper, Liz.
Listen to this!
'Karen Marsh: Sensational
News! By our reporter,
Alan Jones. Karen Marsh
arrived at London Airport
today. She was wearing a
blue dress and a mink coat.
She told me she had just
made a new film.
she said she was not going
to make another.
She said she was going to
retire.
She told reporters she felt
very tired and didn't want
to make another film for
a long time.'
LIZ: I wonder why!
New Word and expressions 
reporter
n. 
sensational
adj. 
mink coat
.
.
.
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter73.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 135 The latest report
Listen to the tape then answer this question. Is Karen Marsh going to
retire, do you think?
.
REPORTER: Are you really
going to retire, miss Marsh?
MISS MARSH: I may.
I can't make up my mind.
I will have to ask
my future husband.
He won't let me make
another film.
REPORTER: Your future husband,
Miss Marsh?
MISS MARSH: Yes. Let me introduce him
to you. His name is Carlos.
We're going to get married
next week.
KATE: Look, Liz!
Here's another report about
Karen Marsh.
Listen: 'Karen Marsh: The
latest. At her London Hotel
today Miss Marsh told
reporters she might retire.
She said she couldn't make
up her mind. She said she
would have to ask her
future husband. She said
her future husband would
not let her make another
film.
Then she introduced us to
Carlos and told us they
would get married next
week'.
LIZ: That's sensational news,
isn't it, Kate?
KATE: It certainly is.
He'll be her sixth husband!
New Word and expressions 
future
n. 
get married
hotel
n. 
latest
adj. 
introduce
v. 
..
6
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter74.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 137 A pleasant dream
Listen to the tape then answer this question. What would Julie like to
do, if she had the money?
JULIE: Are you doing the football
pools, Brain?
BRIAN: Yes, I've nearly finished, Julie.
Julie. I'm sure we'll win
something this week.
JULIE: You always say that,
but we never win anything!
What will you do
if you win a lot of money?
BRIAN: If I win a lot of money
I'll buy you a mink coat.
JULIE: I don't want a mink coat!
I want to see the world.
BRIAN: All right.
If we win a lot of money
We'll travel round the world
and we'll stay at the best
hotels. Then we'll return home
and buy a big house in the
country. We'll have a beautiful
garden and ...
JULIE: But if we spend all that money
we'll be poor again.
What'll we do then?
BRIAN: If we spend all the money
we'll try and win the football
pools again.
JULIE: It's a pleasant dream
but everything depends on 'if'!
New Word and expressions 
football
n. 
pool
n. 
win (won, won)
v. 
world
n. 
poor
adj. 
depend
v. on
......
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter75.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 139 Is that you, John?
Listen to the tape then answer this question. Which John Smith does
Graham Turner think he is talking to?
..
GRAHAM TURNER: Is that you, John?
JOHN SMITH: Yes, speaking.
GRAHAM TURNER: Tell Mary we'll be late
for dinner this evening.
JOHN SMITH: I'm afraid I don't
understand.
GRAHAM TURNER: Hasn't Mary told you?
She invited Charlotte
and me to dinner this
evening. I said I would
be at your house at six
o'clock, but the boss
want me to do some extra
work. I'll have to stay
at the office. I don't
know when I'll finish.
Oh, and by the way,
my wife wants to know
if Mary needs any help.
JOHN SMITH: I don't know what you're
talking about.
GRAHAM TURNER: That is John Smith,
isn't it?
JOHN SMITH: Yes, I'm John Smith.
GRAHAM TURNER: You are John Smith,
the engineer,
aren't you?
JOHN SMITH: That's right.
GRAHAM TURNER: You work for the
Overseas Engineering
Company, don't you?
JOHN SMITH: No, I don't
I'm John Smith the
telephone engineer
and I'm repairing
your telephone line.
New Word and expressions 
extra
adj. 
overseas
adj. 
engineering
n. 
company
n. 
line
n. 
.
. 
.
. 
.
6
. 
..
.  .
..
. 
.
. 
.
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter76.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 141 Sally's first train ride
Listen to the tape then answer this question. Why was the mother
embarrassed?
Last week, my four-year-old daughter, Sally, was invited to a children's
party. I decided to take her by train. Sally was very excited because
she had never travelled on a train before. She sat near the window and
asked questions about everything she saw. Suddenly, a middle-age lady
got on the train and sat opposite Sally. 'Hello, little girl,' she said.
Sally did not answer, but looked at her curiously. The lady was dressed
in a blue coat and a large, funny hat. After the train had left the
station, the lady opened her handbag and took to her power compact. She
then began to make up her face. 'Why are you doing that?' Sally asked.
'To make myself beautiful,' the lady answered. She put away her compact
and smiled kindly. 'But you are still ugly,' Sally said. Sally was
amused, but I was very embarrassed!
New Word and expressions 
excited
adj. 
get on
middle-aged
adj. 
opposite
prep.......
curiously
adv.
funny
adj. 
powder
n. 
compact
n. 
kindly
adv. 
ugly
adj. 
amused
adj. 
smile
v. 
embarrassed
adj. 
4
#+BEGIN_HTML
</div>
#+END_HTML
<<chapter77.html>>
#+BEGIN_HTML
<div>
#+END_HTML
*** Lesson 143 A walk through the woods
Listen to the tape then answer this question. What was so funny about
the words on the sign?
I live in a very old town which is surrounded by beautiful woods. It is
a famous beauty spot. On Sundays, hundreds of people come from the city
to see our town and to walk through the woods. Visitors have been asked
to keep the woods clean and tidy. Litter baskets have been placed under
the trees, but people still throw their rubbish everywhere. Last
Wednesday, I went for a walk in the woods. What I saw made me very sad.
I counted seven old cars and three old refrigerators. The little baskets
were empty and the ground was covered with pieces of paper, cigarette
ends, old tyres, empty bottles and rusty tins. Among the rubbish, I
found a sign which said, 'Anyone who leaves litter in these woods will
be prosecuted!'
New Word and expressions 
surround
v. 
wood
n. 
beauty spot
hundred
n. 
city
n. 
through
prep.
visitor
n. 
tidy
adj. 
litter
n. 
litter basket
place
v. 
throw( threw; thrown)
v. 
rubbish
n. 
count
v. 
cover
v. 
piece
n. 
tyre
n. 
rusty
adj. 
among
prep.......
prosecute
v. 
73
#+BEGIN_HTML
</div>
#+END_HTML
