* /Expressions & Sayings/

* ~ L ~

--------------

#+BEGIN_HTML
  <div align="center">
#+END_HTML

* La-di-da* * - // /affectedly refined, especially in speech/\\
 Originally slang, either an imitation of affected speech or from 'Lard' or 'Lardy', 18th century foppish pronunciation of 'Lord' as a mild oath. The word gained more general currency through a popular and mocking music-hall song of 1880, 'He wears a penny flower in his coat, la-di-da!'. It is now informal rather than slang, and applied to behaviour as well as speech.
* Lady Bountiful\\
 A wealthy and good-natured lady in /The Beaux' Strategem/ (1707), the comedy by George Farquhar (1678-1707). She has somehow passed undeservedly into popular metaphor as the personification of disagreeably patronising or ostentatious charity.
* Laissez-faire - // /non-intervention by government in economic (or other) matters/\\
 /Laissez faire et laissez passer/ (roughly, let people do as they think best and let things move as seems necessary) was the maxim of a school of French economists of the 18th century, notably Gournay. The philosophy was advocated in England by Adam Smith, the exponent of free trade, and Jeremy Bentham, advocate of individualism. The shortened form of the French slogan, sometimes with an r in place of the z to indicate an infinitive rather than an imperative, is still used in political language.
* Lamb to the slaughter - /helpless, innocent or naive victim of sacrifice or catastrophe/\\
 The phrase is originally scriptural (/Isaiah/, 53: 7), from a passage normally interpreted as a prophecy of the humiliation and suffering of Christ. The sacrifice of lambs was a feature of Jewish ritual and references to Christ as 'the Lamb of God' point to his own sacrificial death. These religious senses are absent from modern uses of the expression.
* Lame duck - /person or thing (often commercial operation) unable to succeed because of irremediable handicap/\\
 Originally stock exchange slang from the mid-18th century for someone unable to meet their financial obligations. In nautical slang, a damaged ship was known as a /lame duck/ because neither can make good progress in the water. Perhaps stock exchange language absorbed the terminology from marine insurers at nearby Lloyds.
* Land of Nod - /sleep/\\
 A jocular reference to the land to which Cain was exiled after his fratricide: 'And Cain went out from the presence of the Lord, and dwelt in the land of Nod, on the east of Eden' (/Genesis/, 4: 16). Jonathan Swift first made the pun on the familiar verb /nod/ (show drowsiness) in his /Complete Collection of Polite and Ingenious Conversation/ (1738).
* Lark (about) - /(enjoy) piece of fun or mischief/\\
 Almost certainly not from the bird, which is not a specially frolicsome one, but from a dialect word /lake/ (play) still found in Yorkshire, originally from Scandinavia.\\
 * ...Skylarking, a more recent variant of /larking about/, may have had the same derivation. However, as it seems to have originated in nautical slang for horseplay by seamen up in the rigging, there could additionally be a punning reference to the bird, known for its soaring.
* Last ditch (effort) - a final, often desperate, attempt at something\\
 Originally a military term, the /last ditch/ of your defences would be the final rallying point, your last chance to avoid defeat. William III of England (1689-1702) is supposed to have claimed 'I will die in the last ditch', and during the American War of Independence, the Citizens of Westmoreland issued a grandiloquent proclamation in 1798 saying, 'In War We know but one additional Obligation, To die in the Last Ditch or uphold our Nation'. The expression was being used figuratively by the 1820s.
* Last laugh (the) - /final success, usually at someone's expense, after previous or apparent defeat/\\
 A reference to a proverb variously expressed since the 15th century but currently He who laughs last laughs longest.
* Last/Final straw - // /in a series of calamities, the final (perhaps small) blow which makes matters insupportable/\\
 A quotation from chapter 2 of Charles Dickens' /Dombey and Son/ (1848): 'As the last straw breaks the laden camel's back, this piece of underground information crushed the sinking spirits of Mr Dombey'. This colourful variant of the older 'last feather that breaks the horse's back' is now proverbial as 'it is the [last] straw that breaks the camel's back'. The reference is to the carrying of loads by animals.
* Laugh up one's sleeve - /laugh secretly, often in mockery or self-satisfaction, usually nastily/\\
 This may allude to the time when sleeves were wide enough to hide the face if required (the phrase is first recorded in 1546), or it may merely be a fanciful description of the action of covering a smile with the hand as if actually laughing up one's sleeve.
* Law is an ass, the - /the law is silly/\\
 Mr Bumble actually said 'If the law supposes that, ... the law is a ass, a idiot' (Dickens, /Oliver Twist/ 1837-8), but it would be pedantic to insist on accurate quotation of the wording, which was intended to prick the speaker's pomposity. There is a line in /Revenge for Honour/ by George Chapman (1559-1634), 'I am ashamed the law is such an ass', but it is Dickens' use that accounts for the currency of the expression.
* Law of the jungle - /rules for surviving or succeeding in competition by fighting for oneself/\\
 As law exists to define and safeguard people's rights, the use of /law/ in this expression is inexact in that the spirit of 'everyone for himself' is incompatible with fairness or regard for others. There is no such sense in the original coinage by Rudyard Kipling in /The Jungle Book/ (1894), which sentimentally portrays the jungle, where the boy Mowgli is educated by animals, as having a rather more caring ethos. Like may expressions, this one has changed its meaning since it was first formulated.
* Law unto oneself - /person who follows their own rules, not normal conventions/\\
 Biblical, from /Romans/, 2: 14.
* Lay it on with a trowel - /flatter grossly; spread thickly/\\
 An image from bricklaying, in which a /trowel/ is used for laying on mortar. It was first used by Shakespeare (/As You Like It/, I, 2, line 94). The underlying idea is that mortar will not do its work if spread too thinly and that a /trowel/ is a tool not used with much finesse.
* Lead by the nose\\
 See [[http://users.tinyonline.co.uk/gswithenbank/sayingsp.htm#Pay%20through%20the%20nose][Pay through the nose]].
* Lead on, Macduff\\
 A catchphrase used as a jocular invitation to someone to go first. It is an inveterate misquotation of Macbeth's 'Lay on, Macduff', i.e. 'Come on, attack me', in a sword-fight (V, 8, line 33).
* Lead up the garden path* * - /entice, lead on, deceive/\\
 A cynical reinterpretation - for reasons which can only be guessed at - of a romantic original or poetic cliché, a garden being traditionally thought of as a suitable place for courtship, as in Tennyson's 'Come into the garden, Maud'.
* Leading question* * - /question that suggests a desired answer/\\
 A legal term for the sort of question not permitted in a court of law in certain circumstances because it puts an answer into the mouth of a witness, i.e. it 'leads' him or her to a particular answer. The term is, however, widely and wrongly used as if it meant 'difficult question'.
* Leap in the dark - /something done without knowledge of the consequences/\\
 The dying words of the philosopher Thomas Hobbes (1588-1679) are usually quoted as 'I am going to take a great leap into obscurity', though some authorities quote him as saying '... a fearful leap in the dark'. The phrase became better known through Sir John Vanbrugh's comedy /The Provok'd Wife/ (1697): 'Now I am in for Hobbes' voyage, a great leap in the dark'.
* Leave in the lurch - /leave (person) in adverse circumstances; abandon in a vulnerable position/\\
 /Lurch/ was an old game resembling backgammon. The word also came to be used, in a number of games, to denote a score in which the winner was far ahead of the opponent; in cribbage, for example, one was said to be /in the lurch/ if the winner scored the full 61 before one had turned the corner of the board by scoring 31. From this idea of disadvantage, the now familiar meaning of the term emerged over 400 years ago.\\
 ...It is impossible to explain the connection between /lurch/ as the name of a game and the use of the word to mean a decisive defeat. Both usages are lost in the mists of time. /Lurch/ itself, like several terms in sports and games, is from the French. No doubt, the expression survived because of its neat alliteration, a feature of many popular terms.
* Leave no stone unturned - /search everywhere; try by all means/\\
 This was the advice of the oracle at Delphi when consulted by Polycrates, who had failed to find the hidden treasure of the Persian general defeated at the Battle of Plataea (479 BC). The advice was successfully followed.
* Leopard can't change his spots, a\\
 In the Old Testament, God used Jeremiah to show his people how deeply entrenched in sin they had become that, without God's help, change was nearly impossible. /Jeremiah/ 13:23 says, 'Can the Ethiopian change his skin, or the leopard his spots?'.
* Let the cat out of the bag - /disclose a secret/\\
 A dishonest farmer, claiming to be selling a young pig, might substitute a cat or some other valueless animal in a tied bag. A circumspect buyer would examine the purchase on the spot; an unwary one would not do so until it was too late. Either way the cat would then be let out of the bag and the truth would be known.\\
 ...The best explanation of how this practice originated dates it from the 18th century, when southern Europe was invaded by Muslims, who held that pork was unclean and prohibited its sale. Any traffic in pigs among non-Muslims had therefore to be secret, which lends some credibility to the idea of animals being sold in sacks. If transactions additionally had to take place at night it would be easier for swindlers to make a surreptitious switch of animals, even after a sale had been agreed.\\
 ...The phrase has also been explained by reference to sharp practice at English country fairs. There might well have been cheating of this kind on those occasions, but the lack of any conditions requiring secrecy makes this explanation less persuasive.\\
 ...To be sold a pup (swindled) is a variant of this expression; perhaps some tricksters used a dog instead of a cat. A pig in a poke is obviously related; /poke/ is an old word for a small sack and the whole expression means 'something bought or received without prior examination or knowledge'.
* Let the dead bury their dead* * - /past problems, quarrels, etc. are best forgotten/\\
 A biblical reference to Matthew 8:22, in which Jesus said, 'Follow me and let the dead bury their dead'.
* Level best - /one's very best effort/\\
 This expression is said to have originated in the California goldfields in the 19th century. People panning for gold would shake the matter in the pans until it was level, the better to spot the fragments of gold. It was well established in the USA by the middle of the 19th century, and in the UK by the end.
* Lick and a promise* * - // /something done hurriedly, especially a quick wash/\\
 Probably a fanciful reference to the way in which a cat licks its paw and passes it over the face as if promising to have a more thorough wash later.
* Lick into shape - /put into proper form or condition/\\
 The widespread old belief that bear-cubs are born shapeless and have to be literally licked into their familiar shape by their parents is first recorded in English in /The Pilgrimage of Souls/ (1413): 'Bears be brought forth all foul and transformed and after that by licking of the father and the mother they be brought into their kindly [natural] shape'. The same idea occurs in writings as various as those of the 4th century Roman grammarian Donatus and the 11th century Arab physician Avicenna.
* Like a house on fire - // /very well/\\
 Originally, very quickly or vigorously; the simile made better sense in the old days when houses were of wooden construction and had thatched roofs, etc.
* Like billy-o(h)/billio - /vigorously/\\
 Variously identified as the zealous Joseph Billio, the first Nonconformist minister of Maldon, Essex, in the late 17th century; Nino Biglio, a dashing officer in Garibaldi's army, reputed to have always been urging his men to fight 'like Biglio'; the famous steam locomotive 'Puffing Billy' (1813) which was energetic by contemporary standards in mechanical engineering; and the devil, not because he was ever known as Billy but because some people may have wanted a polite alternative to 'like the devil' (vigorously) and chose /Billy/ at random. The date of the expression (late 19th century) points to Puffing Billy as the likeliest contender: it was employed in hauling coal wagons, was more efficient than previous engines in being the first not to use cogs and rack-rails, and achieved celebrity.
* Like Caesar's wife\\
 See [[http://users.tinyonline.co.uk/gswithenbank/sayingsc.htm#Caesar's%20wife%20must%20be%20above%20suspicion][Caesar's wife must be above suspicion]].
* Like Topsy - /growing of its own accord/\\
 The original Topsy was the little slave-girl in Harriet Beecher Stowe's /Uncle Tom's Cabin/ (1852): 'Do you know who made you?' 'Nobody, as I knows on,' said the child, with a short laugh ... 'I 'spect I grow'd'.
* Lily-livered - /cowardly or weak/\\
 The ancient Greeks used to sacrifice an animal before battle. The liver of the animal was regarded as a prime omen; if it was red then all was fine but if it was pale then this signified bad tidings. By extension, the liver of a coward was thought to be as pale as a lily. So, a coward was regarded as lily-livered.
* Lion's share - /largest portion/\\
 Aesop tell the story of a hunt by a lion and an ass at the end of which the lion divides the spoils into three. He claims the first as king of the animals and the second as equal partner with the ass. As for the third, he advises the ass that it will get him into trouble unless he makes himself scarce.
* Lip service\\
 If you pay service to something with your lips, but not your inner self, then you are either not going to do it, or are insincere in your intentions. The expression comes from the Bible, from /Isaiah/ 29:13 (and is echoed at /Matthew/ 15:8): 'this people draw near me with their mouth, and with their lips do honour me, but have removed their heart far from me'.
* Lips are sealed, one's\\
 A seal is a device, such as a heraldic design or monogram, impressed on a piece of melted wax which then hardens. It is attached to or used to close up a document as evidence of genuineness, or as a mark of ratification or approval. Its use, once everyday, is now rare but is recalled in /one's lips are sealed/ (one reveals nothing, one's mouth being closed as with a seal), seal one's fate (decide it irrevocably), set the seal on (mark or distinguish with a final characteristic act) and seal of approval (a sign of official recognition and approval).
* Little bird told me, a - /refuse to disclose the source of one's information/\\
 This has gradually evolved, reaching its present form in the 19th century, from the Old Testament: 'Curse not the King, no not in thy thought; and curse not the rich in thy bedchamber: for a bird of the air shall carry the voice, and that which hath wings shall tell the matter' (/Ecclesiastes/, 10: 20).
* Live off the fat of the land - /have the best that is obtainable/\\
 In modern English this is the only expression in which /fat/ survives with this old meaning of 'the richest part of anything'. It is a quotation from Pharaoh's words to Joseph in /Genesis/, 45: 18: 'I will give you the gold of the land of Egypt, and ye shall eat the fat of the land'.
* Live the life of Riley - // /live in a comfortable and carefree existence/\\
 First found in /My Name is Kelly/, a music-hall song with an Irish flavour written in 1919 by H. Pease: 'Faith, and my name is Kelly, Michael Kelly, / But I'm living the life of Reilly just the same'. This would not have made much sense unless the audience was expected to recognise or be amused by the mention of Reilly. The reference is probably to an earlier popular song, /Is that Mr Reilly?/ which describes what Reilly would do if he ever made his fortune: 'Is that Mr Reilly that owns the hotel?/Well if that's Mr Reilly they speak of so highly/Upon my soul, Reilly, you're doing quite well!'.
* Live to fight another day - /survive an ordeal/\\
 'He that fights and runs away may live to fight another day' is an old saying known in various forms in English since 1250 but found also in Greek, perhaps originating with the orator Demosthenes in the 4th century BC.
* Load of cobblers, a - /complete rubbish or nonsense/\\
 The origin is in Cockney rhyming slang, the full term is 'cobbler's awls'. An awl is a pointed tool for making holes in things; it is an essential part of a shoemaker's (cobbler's) toolkit. The rhyming links 'cobbler's awls' with 'balls', i.e. slang for testicles. /Cobblers/ then came to be used in the same way as /balls./ A load of old cobblers is an extension of the saying.
* Load of codswallop, a - /a load of rubbish/\\
 A slang expression for beer much used in the 19th century and still current today is /wallop./ In 1872, a certain Victorian businessman called Codd went into the manufacture of lemonade. It was sold in green glass bottles sealed with glass marble stoppers and was jokingly referred to as Codd's wallop. Its poor quality, when compared to beer, although not perhaps with other lemonades, gave rise to the derogatory implications of the phrase. As above, a load of old codswallop is an extension of the saying.
* Load the dice against (someone) - /to arrange things so that (someone) has no chance of success/\\
 Refers to a method of cheating in gambling by putting lead or similar heavy material in a dice so that only certain numbers will come up.
* Lock, stock and barrel - /completely/\\
 The three principal components that make up an entire firearm: the /lock/ is the firing mechanism, the /stock/ is the handle or wooden shoulder-piece to which it is attached, and the /barrel/ is the tube down which the bullet is fired.
* Long in the tooth\\
 See [[http://users.tinyonline.co.uk/gswithenbank/sayingsd.htm#Don't%20look%20a%20gift-horse%20in%20the%20mouth][Don't look a gift-horse in the mouth]].
* Long shot\\
 A /long shot/, a vain attempt, unlikely prospect or a wild guess, is originally military, from the lack of success to be expected when firing at a distant target. By a long shot (by a considerable amount) comes from the same source. A shot in the dark (guess) is related, perhaps a coinage by George Bernard Shaw (1895). A shot in the arm (stimulus, encouragement) is medical, from a hypodermic injection, while a shot across the bows (warning, sometimes called warning shot) is naval, from the practice of firing across a ship's course to warn, intimidate or bring to a halt, but not to damage.
* Long time no see\\
 Catchphrase used on meeting someone after a long time. It apparently comes from the USA, but far from being jocular or Hollywood parody of the limited English of the American Indians, as has been suggested, it is a direct translation of the Chinese equivalent and obviously originated among Chinese immigrant communities learning to speak English in the United States.
* Look as though one has stepped out of a bandbox* * - /looking very neat and elegant/\\
 Refers to a lightweight box formerly used for holding small articles of clothing such as hats.
* Look to one's laurels\\
 See [[http://users.tinyonline.co.uk/gswithenbank/sayingsr.htm#Rest%20on%20one's%20laurels][Rest on one's laurels]].
* Loose cannon - /someone who is out of control, unpredictable, who may cause damage/\\
 On sailing ships that had cannons, it was important that they be secured. Cannons being very heavy, a loose cannon on a ship's deck in a rough sea could be thrown about in an unpredictable fashion, causing a great deal of damage and inconvenience. Further, cannons needed to be secured during use, otherwise when they were fired; the recoil would send the cannon careering backwards across the ship, causing injury or damage on its way.
* Lose one's bottle* * - /lose one's courage/\\
 Cockney rhyming slang: bottle = bottle and glass =arse. To /lose one's bottle/ = lose one's arse, i.e. bowel movement = show extreme fear = lose courage. Therefore, to have bottle is to have courage; to bottle out is to show cowardice.\\
 ...Alternatively, bottle = bottle and glass = class = merit or distinction which, in Cockney terms, would include an ability to stand up for oneself.\\
 ...Those who find these explanations over-elaborate prefer to locate the origin in the bottle-holder who acted as a second for a prize-fighter, using both the contents of the bottle and other skills to keep up his man's fighting spirit during a bout.\\
 ...The simplest and probably the best explanation is that /bottle/ originally stood for the courage that comes out of a bottle and has gradually come to mean genuine courage.
* Lose one's rag\\
 See [[http://users.tinyonline.co.uk/gswithenbank/sayingsc.htm#Chew%20the%20rag][Chew the rag]].
* Lotus-eater* * - // /person living in dreamy indolence, detached from reality/\\
 Travelling homeward from Troy, Odysseus and his followers came to the North African land of the Lotophagi or lotus-eaters, a people who lived on the fruit of the lotus, which induced dreamy forgetfulness. When Odysseus sent out a search party its members tasted the lotus, became oblivious to friends and homes, lost all desire to leave the country and had to be forcibly brought back to the ship (Homer, /Odyssey/, IX, line 90ff). This legend, later popularised by Tennyson's poem /The Lotos-Eaters/ (1833), is the origin of the phrase, which now sometimes has overtones of luxurious ease.
* Lynch law\\
 Believed to be derived from the name of one of two men called Lynch, both operating in Virginia, USA, in the late 18th century. One of them was Charles (1736-96), a magistrate who presided over extra-legal trials of Tories during the war of independence. The more popular candidate is a Captain or Colonel William Lynch (1742-1820), known to have formed squads of vigilantes who took the law into their own hands. He first organised illegal judicial tribunals in 1780 and is believed to have originated the so-called /Lynch law/, i.e. law as defined by an unconstitutional court, though the term now usually means rule by the mob.\\
 ...Some have objected that neither man was famous for hanging people, an important part of the modern definition of lynching. That is immaterial: in its original definition, a lynching was a summary punishment by a self-constituted body without legal authority; it was not necessarily a hanging - whipping and tarring and feathering were also used. Historically, /Lynch law/ came first, then the verb lynch, then the association with hanging.

#+BEGIN_HTML
  </div>
#+END_HTML

#+BEGIN_HTML
  <div align="center">
#+END_HTML

